/*
 * solveint_bqf_parametric.c
 *
 * Part of the Solve[..., Integers] engine; split out of solveint.c.
 * See solveint_internal.h for the shared SICtx/SearchState substrate.
 *
 * Unbounded parametric families of the general binary quadratic
 *
 *     A x^2 + B x y + C y^2 + D x + E y + F == 0
 *
 * for the two conic types the diagonal Pell paths (solveint_pell.c /
 * solveint_genpell.c) do not reach because of the cross term B x y:
 *
 *   - PARABOLIC  (delta = B^2 - 4AC == 0): the quadratic part is a perfect
 *     square, so the curve is a parabola with integer points given by a finite
 *     union of one-parameter families  {x -> quad(t), y -> quad(t)}.  Found by
 *     the classical congruence method (a residue u mod |_c| per family).
 *
 *   - HYPERBOLIC (delta > 0, not a perfect square): a Pell conic.  Its
 *     automorphism group is generated by the fundamental unit (t,u) of
 *     X^2 - delta Y^2 = 1 acting as the integer matrix
 *        M = [[ t - B u,  -2 C u ],
 *             [   2 A u,   t + B u ]]   (det 1),
 *     so every solution orbit is  M^k * (x0, y0).  The finitely many base
 *     solutions (orbit-minimal in the constrained region) are found by a bounded
 *     search; each yields one closed-form ConditionalExpression family in the
 *     fundamental unit, exactly as the diagonal Pell path does.  Scope: the
 *     homogeneous quadratic part plus a constant (D == E == 0) with x>0 && y>0.
 *
 * delta < 0 (ellipse) and a perfect-square delta > 0 (a hyperbola with rational
 * asymptotes) both have FINITELY many points and are handled by the bounded
 * conic / elliptic paths -- declined here.
 */
#include "solveint.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <gmp.h>

#include "eval.h"
#include "expr.h"
#include "poly/mpoly.h"
#include "solveint_internal.h"


/* Extract A,B,C,D,E,F over the two active variables (Xv, Yv).  Returns false on
 * any total-degree > 2 term or a term touching a third variable. */
static bool bqf_extract(const MPoly* eq, int n, int Xv, int Yv,
                        mpz_t A, mpz_t B, mpz_t C, mpz_t D, mpz_t E, mpz_t F) {
    mpz_set_ui(A,0); mpz_set_ui(B,0); mpz_set_ui(C,0);
    mpz_set_ui(D,0); mpz_set_ui(E,0); mpz_set_ui(F,0);
    for (size_t t = 0; t < eq->n_terms; t++) {
        const int* ex = eq->exps + t * (size_t)n;
        for (int v = 0; v < n; v++) if (v != Xv && v != Yv && ex[v] != 0) return false;
        int ix = ex[Xv], iy = ex[Yv];
        if      (ix == 2 && iy == 0) mpz_set(A, eq->coefs[t]);
        else if (ix == 1 && iy == 1) mpz_set(B, eq->coefs[t]);
        else if (ix == 0 && iy == 2) mpz_set(C, eq->coefs[t]);
        else if (ix == 1 && iy == 0) mpz_set(D, eq->coefs[t]);
        else if (ix == 0 && iy == 1) mpz_set(E, eq->coefs[t]);
        else if (ix == 0 && iy == 0) mpz_set(F, eq->coefs[t]);
        else return false;                                /* total degree > 2 */
    }
    return true;
}


/* Build  c2 t^2 + c1 t + c0  as an Expr in the parameter C[1] (dropping zero
 * coefficients).  Owns the returned Expr. */
static Expr* bqf_quad_in_t(const mpz_t c2, const mpz_t c1, const mpz_t c0) {
    Expr* terms[3]; int nt = 0;
    if (mpz_sgn(c2)) terms[nt++] = mk_fn2("Times", mk_mpz(c2),
        mk_fn2("Power", mk_fn1("C", mk_int(1)), mk_int(2)));
    if (mpz_sgn(c1)) terms[nt++] = mk_fn2("Times", mk_mpz(c1), mk_fn1("C", mk_int(1)));
    if (mpz_sgn(c0)) terms[nt++] = mk_mpz(c0);
    if (nt == 0) return mk_int(0);
    if (nt == 1) return terms[0];
    return expr_new_function(mk_sym("Plus"), terms, nt);
}


/* ---- Parabolic  delta == 0. ---- */
static Expr* bqf_parabolic(SICtx* c, int Xv, int Yv,
                           mpz_t A, mpz_t B, mpz_t C, mpz_t D, mpz_t E, mpz_t F) {
    /* Only fully unconstrained (the finite / bounded parabola is enumerated by
     * the leaf search). */
    if (c->has_lo[Xv] || c->has_hi[Xv] || c->has_lo[Yv] || c->has_hi[Yv]) return NULL;

    /* Need A != 0; swap x<->y when only C is nonzero. */
    if (mpz_sgn(A) == 0 && mpz_sgn(C) != 0) {
        mpz_swap(A, C); mpz_swap(D, E); int tmp = Xv; Xv = Yv; Yv = tmp;
    }
    if (mpz_sgn(A) == 0) return NULL;                     /* A == C == 0: not our case */

    mpz_t g, a1, c1, sqa, sqc, sb, cc, tmp, yn, xn;
    mpz_inits(g, a1, c1, sqa, sqc, sb, cc, tmp, yn, xn, NULL);
    /* g = sign(A) * gcd(A, C);  A/g and C/g are perfect squares. */
    mpz_gcd(g, A, C); if (mpz_sgn(A) < 0) mpz_neg(g, g);
    mpz_divexact(a1, A, g); mpz_divexact(c1, C, g);
    Expr* result = NULL;
    bool ok = (mpz_sgn(a1) > 0 && mpz_perfect_square_p(a1)
               && mpz_sgn(c1) >= 0 && (mpz_sgn(c1) == 0 || mpz_perfect_square_p(c1)));
    if (ok) {
        mpz_sqrt(sqa, a1); mpz_sqrt(sqc, c1);
        mpz_set_si(sb, mpz_sgn(B) >= 0 ? 1 : -1);         /* sign of B (0 -> +1) */
        /* _c = sb*sqc*D - sqa*E. */
        mpz_mul(cc, sb, sqc); mpz_mul(cc, cc, D);
        mpz_mul(tmp, sqa, E); mpz_sub(cc, cc, tmp);
        if (mpz_sgn(cc) == 0) { ok = false; }             /* degenerate: parallel lines */
        if (ok) {
            mpz_t absc; mpz_init(absc); mpz_abs(absc, cc);
            long ncap = 0;
            if (!mpz_fits_slong_p(absc) || mpz_cmp_ui(absc, 200000) > 0) ok = false;
            else ncap = mpz_get_si(absc);
            Expr** tuples = ok ? (Expr**)malloc(sizeof(Expr*) * (size_t)(ncap + 1)) : NULL;
            int ntup = 0;
            mpz_t u, cy2, cy1, cy0, cx2, cx1, cx0, sg, ssc, sscF, sqaF;
            mpz_inits(u, cy2, cy1, cy0, cx2, cx1, cx0, sg, ssc, sscF, sqaF, NULL);
            mpz_mul(sg, sqa, g);                           /* sqa*g */
            mpz_mul(ssc, sb, sqc); mpz_mul(ssc, ssc, g);   /* sb*sqc*g */
            mpz_mul(sscF, sb, sqc); mpz_mul(sscF, sscF, F);/* sb*sqc*F (no g) */
            mpz_mul(sqaF, sqa, F);                         /* sqa*F   (no g) */
            for (long uu = 0; ok && uu < ncap; uu++) {
                mpz_set_si(u, uu);
                /* yn = sqa*g*u^2 + D*u + sqa*F ; need _c | yn. */
                mpz_mul(yn, sg, u); mpz_mul(yn, yn, u);
                mpz_mul(tmp, D, u); mpz_add(yn, yn, tmp);
                mpz_add(yn, yn, sqaF);
                if (!mpz_divisible_p(yn, cc)) continue;
                /* xn = sb*sqc*g*u^2 + E*u + sb*sqc*F ; need _c | xn. */
                mpz_mul(xn, ssc, u); mpz_mul(xn, xn, u);
                mpz_mul(tmp, E, u); mpz_add(xn, xn, tmp);
                mpz_add(xn, xn, sscF);
                if (!mpz_divisible_p(xn, cc)) continue;
                /* y(t) = sqa*g*_c t^2 + (D + 2 sqa*g u) t + yn/_c. */
                mpz_mul(cy2, sg, cc);
                mpz_mul(cy1, sg, u); mpz_mul_ui(cy1, cy1, 2); mpz_add(cy1, cy1, D);
                mpz_divexact(cy0, yn, cc);
                /* x(t) = -sb*sqc*g*_c t^2 - (E + 2 sb*sqc*g u) t - xn/_c. */
                mpz_mul(cx2, ssc, cc); mpz_neg(cx2, cx2);
                mpz_mul(cx1, ssc, u); mpz_mul_ui(cx1, cx1, 2); mpz_add(cx1, cx1, E); mpz_neg(cx1, cx1);
                mpz_divexact(cx0, xn, cc); mpz_neg(cx0, cx0);
                Expr* rules[SI_MAX_VARS]; for (int i = 0; i < c->n; i++) rules[i] = NULL;
                rules[Xv] = mk_rule(expr_copy(c->var[Xv]), bqf_quad_in_t(cx2, cx1, cx0));
                rules[Yv] = mk_rule(expr_copy(c->var[Yv]), bqf_quad_in_t(cy2, cy1, cy0));
                Expr* rl[SI_MAX_VARS]; int nr = 0;
                for (int i = 0; i < c->n; i++) if (rules[i]) rl[nr++] = rules[i];
                tuples[ntup++] = mk_list(rl, (size_t)nr);
            }
            mpz_clears(u, cy2, cy1, cy0, cx2, cx1, cx0, sg, ssc, sscF, sqaF, NULL);
            mpz_clear(absc);
            if (ok) result = eval_and_free(mk_list(tuples, (size_t)ntup)); /* {} if none: a proof */
            else if (tuples) for (int i = 0; i < ntup; i++) expr_free(tuples[i]);
            free(tuples);
        }
    }
    mpz_clears(g, a1, c1, sqa, sqc, sb, cc, tmp, yn, xn, NULL);
    return result;
}


/* ---- Hyperbolic  delta > 0 non-square, D == E == 0, x>0 && y>0. ---- */

/* Build one closed-form family for base (x0,y0), fundamental unit (t, uu)
 * (uu = +u forward, -u backward), of the conic A x^2 + B x y + C y^2 + F == 0.
 * X0 = 2A x0 + B y0, Y0 = y0;  X_k = (P eps^k + Pbar epsbar^k)/2,
 * Y_k = (P eps^k - Pbar epsbar^k)/(2 sqrt(delta)),  eps = t + uu sqrt(delta),
 * then y -> Y_k,  x -> (X_k - B Y_k)/(2A).  ConditionalExpression on C[1] >= 0. */
static Expr* bqf_hyp_family(SICtx* c, int Xv, int Yv, const mpz_t A, const mpz_t B,
                            const mpz_t x0, const mpz_t y0, const mpz_t t,
                            const mpz_t uu, const mpz_t delta) {
    mpz_t X0, Y0, nuu, nY0; mpz_inits(X0, Y0, nuu, nY0, NULL);
    mpz_mul_ui(X0, A, 2); mpz_mul(X0, X0, x0);            /* 2A x0 */
    { mpz_t bt; mpz_init(bt); mpz_mul(bt, B, y0); mpz_add(X0, X0, bt); mpz_clear(bt); } /* + B y0 */
    mpz_set(Y0, y0); mpz_neg(nuu, uu); mpz_neg(nY0, Y0);

    Expr* sqrtD = mk_fn1("Sqrt", mk_mpz(delta));
    Expr* P    = mk_fn2("Plus", mk_mpz(X0), mk_fn2("Times", mk_mpz(Y0),  expr_copy(sqrtD)));
    Expr* Pbar = mk_fn2("Plus", mk_mpz(X0), mk_fn2("Times", mk_mpz(nY0), expr_copy(sqrtD)));
    Expr* eps    = mk_fn2("Plus", mk_mpz(t), mk_fn2("Times", mk_mpz(uu),  expr_copy(sqrtD)));
    Expr* epsbar = mk_fn2("Plus", mk_mpz(t), mk_fn2("Times", mk_mpz(nuu), expr_copy(sqrtD)));
    Expr* epsC    = mk_fn2("Power", eps,    mk_fn1("C", mk_int(1)));
    Expr* epsbarC = mk_fn2("Power", epsbar, mk_fn1("C", mk_int(1)));
    Expr* Pe    = mk_fn2("Times", P, epsC);
    Expr* Pbare = mk_fn2("Times", Pbar, epsbarC);
    /* X_k = (Pe + Pbare)/2. */
    Expr* Xk = mk_fn2("Times", mk_fn2("Plus", expr_copy(Pe), expr_copy(Pbare)),
                      mk_fn2("Power", mk_int(2), mk_int(-1)));
    /* Y_k = (Pe - Pbare)/(2 sqrt(delta)). */
    Expr* Yk = mk_fn2("Times",
        mk_fn2("Plus", Pe, mk_fn2("Times", mk_int(-1), Pbare)),
        mk_fn2("Power", mk_fn2("Times", mk_int(2), expr_copy(sqrtD)), mk_int(-1)));
    expr_free(sqrtD);

    /* x = (X_k - B Y_k)/(2A). */
    mpz_t twoA; mpz_init(twoA); mpz_mul_ui(twoA, A, 2);
    Expr* xval = mk_fn2("Times",
        mk_fn2("Plus", expr_copy(Xk), mk_fn2("Times", mk_mpz(B), mk_fn2("Times", mk_int(-1), expr_copy(Yk)))),
        mk_fn2("Power", mk_mpz(twoA), mk_int(-1)));
    mpz_clear(twoA);
    Expr* yval = Yk;                                       /* y = Y_k */

    Expr* cond = mk_fn2("GreaterEqual", mk_fn1("C", mk_int(1)), mk_int(0));
    Expr* cex = mk_fn2("ConditionalExpression", xval, expr_copy(cond));
    Expr* cey = mk_fn2("ConditionalExpression", yval, cond);
    expr_free(Xk);

    Expr* rules[SI_MAX_VARS]; for (int i = 0; i < c->n; i++) rules[i] = NULL;
    rules[Xv] = mk_rule(expr_copy(c->var[Xv]), cex);
    rules[Yv] = mk_rule(expr_copy(c->var[Yv]), cey);
    Expr* rl[SI_MAX_VARS]; int nr = 0;
    for (int i = 0; i < c->n; i++) if (rules[i]) rl[nr++] = rules[i];
    mpz_clears(X0, Y0, nuu, nY0, NULL);
    return mk_list(rl, (size_t)nr);
}

/* Apply the (integer, det-1) automorphism M or M^{-1} to (x,y) in place.
 * M   = [[t - B u, -2 C u],[2 A u, t + B u]]
 * Minv= [[t + B u,  2 C u],[-2 A u, t - B u]] */
static void bqf_aut(mpz_t x, mpz_t y, const mpz_t A, const mpz_t B, const mpz_t C,
                    const mpz_t t, const mpz_t u, bool inverse) {
    mpz_t m00, m01, m10, m11, nx, ny, tmp;
    mpz_inits(m00, m01, m10, m11, nx, ny, tmp, NULL);
    mpz_mul(tmp, B, u);                                    /* B u */
    if (!inverse) { mpz_sub(m00, t, tmp); mpz_add(m11, t, tmp); }
    else          { mpz_add(m00, t, tmp); mpz_sub(m11, t, tmp); }
    mpz_mul(m01, C, u); mpz_mul_ui(m01, m01, 2); if (!inverse) mpz_neg(m01, m01);  /* -2Cu / +2Cu */
    mpz_mul(m10, A, u); mpz_mul_ui(m10, m10, 2); if (inverse) mpz_neg(m10, m10);   /* +2Au / -2Au */
    mpz_mul(nx, m00, x); mpz_mul(tmp, m01, y); mpz_add(nx, nx, tmp);
    mpz_mul(ny, m10, x); mpz_mul(tmp, m11, y); mpz_add(ny, ny, tmp);
    mpz_set(x, nx); mpz_set(y, ny);
    mpz_clears(m00, m01, m10, m11, nx, ny, tmp, NULL);
}

/* Advance a candidate integer point (x0,y0) into the positive quadrant (x>=1,
 * y>=1) by at most a few automorphism steps (the point comes from a Nagell-bounded
 * (X,Y) representative, so its orbit enters the quadrant within one or two steps),
 * then reduce to the orbit-minimal positive base.  On success writes the base to
 * (px,py), the growth direction to *dir (+1 forward M, -1 backward M^-1), and
 * returns true.  Bounded (never blows up): the advance is capped, the reduce only
 * ever shrinks. */
static bool bqf_pos_base(const mpz_t x0, const mpz_t y0, const mpz_t A, const mpz_t B,
                         const mpz_t C, const mpz_t t, const mpz_t u,
                         mpz_t px, mpz_t py, int* dir) {
    mpz_set(px, x0); mpz_set(py, y0);
    if (!(mpz_sgn(px) >= 1 && mpz_sgn(py) >= 1)) {
        mpz_t qx, qy; mpz_inits(qx, qy, NULL);
        bool ok = false;
        for (int sign = 0; sign < 2 && !ok; sign++) {         /* forward then backward */
            mpz_set(qx, x0); mpz_set(qy, y0);
            for (int g = 0; g < 16; g++) {
                bqf_aut(qx, qy, A, B, C, t, u, sign == 1);
                if (mpz_sgn(qx) >= 1 && mpz_sgn(qy) >= 1) { mpz_set(px, qx); mpz_set(py, qy); ok = true; break; }
            }
        }
        mpz_clears(qx, qy, NULL);
        if (!ok) return false;                                /* orbit misses the quadrant */
    }
    /* Reduce to the orbit-minimal positive point. */
    { mpz_t qx, qy, sum, nsum; mpz_inits(qx, qy, sum, nsum, NULL);
      for (int guard = 0; guard < 100000; guard++) {
        bool reduced = false;
        mpz_add(sum, px, py);
        for (int inv = 1; inv >= 0 && !reduced; inv--) {      /* try M^-1 then M */
            mpz_set(qx, px); mpz_set(qy, py);
            bqf_aut(qx, qy, A, B, C, t, u, inv == 1);
            mpz_add(nsum, qx, qy);
            if (mpz_sgn(qx) >= 1 && mpz_sgn(qy) >= 1 && mpz_cmp(nsum, sum) < 0) {
                mpz_set(px, qx); mpz_set(py, qy); reduced = true;
            }
        }
        if (!reduced) break;
      }
      mpz_clears(qx, qy, sum, nsum, NULL); }
    /* Direction that keeps the orbit positive + growing. */
    *dir = 0;
    { mpz_t qx, qy; mpz_init_set(qx, px); mpz_init_set(qy, py);
      bqf_aut(qx, qy, A, B, C, t, u, false);
      if (mpz_sgn(qx) >= 1 && mpz_sgn(qy) >= 1) *dir = 1;
      else { mpz_set(qx, px); mpz_set(qy, py);
             bqf_aut(qx, qy, A, B, C, t, u, true);
             if (mpz_sgn(qx) >= 1 && mpz_sgn(qy) >= 1) *dir = -1; }
      mpz_clears(qx, qy, NULL); }
    return true;
}

static Expr* bqf_hyperbolic(SICtx* c, int Xv, int Yv,
                            mpz_t A, mpz_t B, mpz_t C, mpz_t D, mpz_t E, mpz_t F,
                            const mpz_t delta) {
    if (mpz_sgn(D) != 0 || mpz_sgn(E) != 0) return NULL;   /* scope: homogeneous + const */
    bool posx = c->has_lo[Xv] && c->lo[Xv] >= 1;
    bool posy = c->has_lo[Yv] && c->lo[Yv] >= 1;
    bool unbounded = !c->has_hi[Xv] && !c->has_hi[Yv];
    if (!(posx && posy && unbounded)) return NULL;

    mpz_t t, u, bx, by, one; mpz_inits(t, u, bx, by, one, NULL); mpz_set_ui(one, 1);
    if (!si_pell_cf(delta, one, t, u, bx, by)) { mpz_clears(t,u,bx,by,one,NULL); return NULL; }
    mpz_clear(one);

    enum { CAP = 4096 };
    mpz_t bxs[CAP], bys[CAP]; int bdir[CAP]; int nb = 0;   /* dir: +1 forward, -1 backward */
    for (int i = 0; i < CAP; i++) { mpz_init(bxs[i]); mpz_init(bys[i]); }

    mpz_t N, twoA, Y, S, Xroot, X, num, x0, px, py, Ymaxz, absN, nnum, nden;
    mpz_inits(N, twoA, Y, S, Xroot, X, num, x0, px, py, Ymaxz, absN, nnum, nden, NULL);
    mpz_mul_ui(twoA, A, 2);
    /* Reduce  A x^2 + B x y + C y^2 + F == 0  to the Pell equation
     * X^2 - delta Y^2 == N  via  X = 2A x + B y,  Y = y,  N = -4 A F. */
    mpz_mul(N, A, F); mpz_mul_ui(N, N, 4); mpz_neg(N, N);

    bool declined = false;
    if (mpz_sgn(N) == 0) {
        /* Homogeneous form, delta non-square: only the excluded trivial point. */
        Expr* empty = mk_list(NULL, 0);
        for (int i = 0; i < CAP; i++) { mpz_clear(bxs[i]); mpz_clear(bys[i]); }
        mpz_clears(N, twoA, Y, S, Xroot, X, num, x0, px, py, Ymaxz, absN, nnum, nden, NULL);
        mpz_clears(t, u, bx, by, NULL);
        return empty;
    }

    /* Nagell bound: every solution class of  X^2 - delta Y^2 == N  has a
     * representative with  0 <= Y <= u*sqrt(|N|/(2(t±1))) -- INDEPENDENT of the
     * size of the fundamental unit (t,u).  This is the whole point: a large-
     * discriminant form has a huge unit, so the direct (x,y) search explodes,
     * but the Y-range that has to be scanned here stays small. */
    mpz_abs(absN, N);
    mpz_mul(nnum, u, u); mpz_mul(nnum, nnum, absN);          /* u^2 |N| */
    if (mpz_sgn(N) > 0) mpz_add_ui(nden, t, 1); else mpz_sub_ui(nden, t, 1);
    mpz_mul_ui(nden, nden, 2);                              /* 2(t±1) */
    if (mpz_sgn(nden) <= 0) mpz_set_ui(Ymaxz, 0);
    else { mpz_fdiv_q(nnum, nnum, nden); mpz_sqrt(Ymaxz, nnum); mpz_add_ui(Ymaxz, Ymaxz, 4); }
    if (!mpz_fits_slong_p(Ymaxz) || mpz_cmp_ui(Ymaxz, 50000000UL) > 0) declined = true;
    long ymax = declined ? 0 : mpz_get_si(Ymaxz);

    /* For each Y in [0, Ymax] with  delta Y^2 + N  a perfect square, both signs of
     * X give a Pell representative (X,Y); map it to (x,y) = ((X - B Y)/(2A), Y),
     * advance into the positive quadrant and reduce to the orbit base. */
    for (long yy = 0; yy <= ymax && !declined; yy++) {
        mpz_set_si(Y, yy);
        mpz_mul(S, delta, Y); mpz_mul(S, S, Y); mpz_add(S, S, N);   /* delta Y^2 + N */
        if (mpz_sgn(S) < 0 || !mpz_perfect_square_p(S)) continue;
        mpz_sqrt(Xroot, S);
        for (int sx = 1; sx >= -1; sx -= 2) {
            if (sx < 0 && mpz_sgn(Xroot) == 0) continue;
            mpz_set(X, Xroot); if (sx < 0) mpz_neg(X, X);
            mpz_mul(num, B, Y); mpz_sub(num, X, num);          /* X - B Y */
            if (!mpz_divisible_p(num, twoA)) continue;
            mpz_divexact(x0, num, twoA);                       /* candidate x, with y = Y */
            int dir;
            if (!bqf_pos_base(x0, Y, A, B, C, t, u, px, py, &dir)) continue;
            if (dir == 0) continue;                            /* isolated (shouldn't occur) */
            bool dup = false;
            for (int i = 0; i < nb; i++)
                if (mpz_cmp(bxs[i], px) == 0 && mpz_cmp(bys[i], py) == 0) { dup = true; break; }
            if (!dup && nb < CAP) { mpz_set(bxs[nb], px); mpz_set(bys[nb], py); bdir[nb] = dir; nb++; }
        }
    }

    Expr* result = NULL;
    if (!declined && nb > 0) {
        /* One closed-form family per orbit base. */
        Expr** tuples = (Expr**)malloc(sizeof(Expr*) * (size_t)nb);
        int ntup = 0;
        for (int i = 0; i < nb; i++) {
            mpz_t uu; mpz_init(uu);
            if (bdir[i] > 0) mpz_set(uu, u); else mpz_neg(uu, u);
            tuples[ntup++] = bqf_hyp_family(c, Xv, Yv, A, B, bxs[i], bys[i], t, uu, delta);
            mpz_clear(uu);
        }
        result = eval_and_free(mk_list(tuples, (size_t)ntup));
        free(tuples);
    }

    for (int i = 0; i < CAP; i++) { mpz_clear(bxs[i]); mpz_clear(bys[i]); }
    mpz_clears(N, twoA, Y, S, Xroot, X, num, x0, px, py, Ymaxz, absN, nnum, nden, NULL);
    mpz_clears(t, u, bx, by, NULL);
    return result;
}


/* General binary-quadratic parametric entry.  Returns an owned family List / {},
 * or NULL to decline. */
Expr* si_solve_bqf_parametric(SICtx* c) {
    if (c->neq != 1) return NULL;
    const MPoly* eq = c->eq[0]; int n = c->n;
    int act[SI_MAX_VARS], ka = 0;
    for (int v = 0; v < n; v++) if (mpoly_deg_var(eq, v) >= 1) act[ka++] = v;
    if (ka != 2) return NULL;
    if (c->n_ord != 0 || c->n_neq != 0 || c->n_abs_ord != 0 || !c->all_captured) return NULL;

    int Xv = act[0], Yv = act[1];
    mpz_t A, B, C, D, E, F, delta, tmp;
    mpz_inits(A, B, C, D, E, F, delta, tmp, NULL);
    Expr* result = NULL;
    if (bqf_extract(eq, n, Xv, Yv, A, B, C, D, E, F)) {
        mpz_mul(delta, B, B); mpz_mul(tmp, A, C); mpz_submul_ui(delta, tmp, 4);  /* B^2 - 4AC */
        if (mpz_sgn(delta) == 0) {
            result = bqf_parabolic(c, Xv, Yv, A, B, C, D, E, F);
        } else if (mpz_sgn(delta) > 0 && !mpz_perfect_square_p(delta)) {
            result = bqf_hyperbolic(c, Xv, Yv, A, B, C, D, E, F, delta);
        }
        /* delta < 0 (ellipse) / perfect-square delta (finite hyperbola): decline. */
    }
    mpz_clears(A, B, C, D, E, F, delta, tmp, NULL);
    return result;
}
