(* CRCIntegralsCorpus.m
 *
 * Test corpus for src/internal/CRCMathTablesIntegrals.m.  Each entry
 * is a {integrand, var} pair that exercises one CRC table rule with
 * concrete parameter values.  The corpus runner (tests/test_crc_corpus.c)
 * dispatches each pair through Integrate[..., Method -> "CRCTable"]
 * and validates the result via D[r, x] - integrand == 0 (under
 * Simplify[Cancel[Together[...]]]).
 *
 * Coverage: every IntegrateTable rule in the CRC file gets at least
 * one entry, with three concrete instantiations per rule whenever the
 * pattern admits them.  Rules are grouped by formula number with
 * inline comments showing which rule each block targets.  Each block
 * is generated by substituting small integer constants (2, 3, 5, ...)
 * for the pattern parameters in a way that satisfies the rule's
 * `FreeQ` / sign / integer constraints.
 *
 * The harness checks correctness via differential check, so the order
 * of entries does NOT matter for correctness — entries are arranged in
 * formula-number order purely for readability.
 *)

{
  (* ============================================================ *)
  (* SECTION 1: Elementary forms + a + b x (Formulas 23-42)        *)
  (* ============================================================ *)

  (* Elementary: constant *)
  {5, x},
  {Pi, x},
  {a, x},

  (* Elementary: a*f *)
  {3 Sin[x], x},
  {7 x^2, x},
  {2 Exp[x], x},

  (* Elementary: f + g *)
  {x + x^2, x},
  {Sin[x] + Cos[x], x},
  {x^3 + 2 x, x},

  (* Elementary: x^n *)
  {x^2, x},
  {x^5, x},
  {x^7, x},

  (* Elementary: 1/x *)
  {1/x, x},

  (* Elementary: Exp[a x] *)
  {Exp[2 x], x},
  {Exp[x], x},
  {Exp[5 x], x},

  (* Elementary: b^(a x) *)
  {2^(3 x), x},
  {5^x, x},
  {3^(2 x), x},

  (* Elementary: Log[a x] *)
  {Log[2 x], x},
  {Log[x], x},
  {Log[7 x], x},

  (* Elementary: 1/(x^2 + a), a > 0 *)
  {1/(x^2 + 4), x},
  {1/(x^2 + 9), x},
  {1/(x^2 + 2), x},

  (* Elementary: 1/(a - x^2), a > 0 *)
  {1/(4 - x^2), x},
  {1/(9 - x^2), x},
  {1/(16 - x^2), x},

  (* Elementary: 1/(x^2 + a), a < 0 *)
  {1/(x^2 - 4), x},
  {1/(x^2 - 9), x},
  {1/(x^2 - 1), x},

  (* Elementary: 1/Sqrt[a - x^2], a > 0 *)
  {(4 - x^2)^(-1/2), x},
  {(9 - x^2)^(-1/2), x},
  {(25 - x^2)^(-1/2), x},

  (* Elementary: 1/Sqrt[x^2 + a] *)
  {(x^2 + 4)^(-1/2), x},
  {(x^2 + 9)^(-1/2), x},
  {(x^2 - 4)^(-1/2), x},

  (* Elementary: 1/Sqrt[x^2 - a] *)
  {(x^2 - 9)^(-1/2), x},
  {(x^2 - 1)^(-1/2), x},
  {(x^2 - 25)^(-1/2), x},

  (* Elementary: 1/(x Sqrt[x^2 - a]) *)
  {1/x (x^2 - 4)^(-1/2), x},
  {1/x (x^2 - 9)^(-1/2), x},
  {1/x (x^2 - 16)^(-1/2), x},

  (* Elementary: 1/(x Sqrt[b x^2 + a]) *)
  {1/x (2 x^2 + 4)^(-1/2), x},
  {1/x (x^2 + 9)^(-1/2), x},
  {1/x (3 x^2 + 1)^(-1/2), x},

  (* Formula 23: (b x + a)^n *)
  {(2 x + 3)^4, x},
  {(5 x - 1)^3, x},
  {(x + 7)^6, x},

  (* Formula 24: x (b x + a)^n *)
  {x (2 x + 1)^3, x},
  {x (3 x + 2)^4, x},
  {x (x - 5)^5, x},

  (* Formula 25: x^2 (b x + a)^n *)
  {x^2 (2 x + 1)^3, x},
  {x^2 (x + 3)^4, x},
  {x^2 (3 x - 2)^2, x},

  (* Formula 26 (Form 1): x^m (b x + a)^n, n > 0 *)
  {x^3 (2 x + 1)^2, x},
  {x^2 (x + 5)^3, x},
  {x^4 (3 x + 1)^1, x},

  (* Formula 27: 1/(a + b x) *)
  {1/(3 + 2 x), x},
  {1/(x + 5), x},
  {1/(1 + 4 x), x},

  (* Formula 28: 1/(a + b x)^2 *)
  {1/(3 + 2 x)^2, x},
  {1/(x + 1)^2, x},
  {1/(5 + 4 x)^2, x},

  (* Formula 29: 1/(a + b x)^3 *)
  {1/(2 + x)^3, x},
  {1/(3 + 2 x)^3, x},
  {1/(1 + 5 x)^3, x},

  (* Formula 30: x/(a + b x) *)
  {x/(2 + 3 x), x},
  {x/(1 + x), x},
  {x/(5 + 2 x), x},

  (* Formula 31: x/(a + b x)^2 *)
  {x/(2 + 3 x)^2, x},
  {x/(1 + x)^2, x},
  {x/(5 + 2 x)^2, x},

  (* Formula 32: x/(a + b x)^n, n != 1,2 *)
  {x/(2 + 3 x)^3, x},
  {x/(1 + x)^4, x},
  {x/(3 + 2 x)^5, x},

  (* Formula 33: x^2/(a + b x) *)
  {x^2/(2 + 3 x), x},
  {x^2/(1 + x), x},
  {x^2/(5 + 2 x), x},

  (* Formula 34: x^2/(a + b x)^2 *)
  {x^2/(2 + 3 x)^2, x},
  {x^2/(1 + x)^2, x},
  {x^2/(5 + 2 x)^2, x},

  (* Formula 35: x^2/(a + b x)^3 *)
  {x^2/(2 + 3 x)^3, x},
  {x^2/(1 + x)^3, x},
  {x^2/(5 + 2 x)^3, x},

  (* Formula 36: x^2/(a + b x)^n, n != 1,2,3 *)
  {x^2/(2 + 3 x)^4, x},
  {x^2/(1 + x)^5, x},
  {x^2/(3 + 2 x)^6, x},

  (* Formula 37: 1/(x (a + b x)) *)
  {1/(x (2 + 3 x)), x},
  {1/(x (1 + x)), x},
  {1/(x (5 + 2 x)), x},

  (* Formula 38: 1/(x (a + b x)^2) *)
  {1/(x (2 + 3 x)^2), x},
  {1/(x (1 + x)^2), x},
  {1/(x (5 + 2 x)^2), x},

  (* Formula 39: 1/(x (a + b x)^3) *)
  {1/(x (2 + 3 x)^3), x},
  {1/(x (1 + x)^3), x},
  {1/(x (5 + 2 x)^3), x},

  (* Formula 40: 1/(x^2 (a + b x)) *)
  {1/(x^2 (2 + 3 x)), x},
  {1/(x^2 (1 + x)), x},
  {1/(x^2 (5 + 2 x)), x},

  (* Formula 41: 1/(x^3 (a + b x)) *)
  {1/(x^3 (2 + 3 x)), x},
  {1/(x^3 (1 + x)), x},
  {1/(x^3 (5 + 2 x)), x},

  (* Formula 42: 1/(x^2 (a + b x)^2) *)
  {1/(x^2 (2 + 3 x)^2), x},
  {1/(x^2 (1 + x)^2), x},
  {1/(x^2 (5 + 2 x)^2), x},

  (* ============================================================ *)
  (* SECTION 2: c^2 +/- x^2, x^2 - c^2 (Formulas 43-51)             *)
  (* ============================================================ *)

  (* Formula 43: 1/(c^2 + x^2) *)
  {1/(4 + x^2), x},
  {1/(9 + x^2), x},
  {1/(25 + x^2), x},

  (* Formula 44: 1/(c^2 - x^2) *)
  {1/(4 - x^2), x},
  {1/(9 - x^2), x},
  {1/(16 - x^2), x},

  (* Formula 45: 1/(x^2 - c^2) *)
  {1/(x^2 - 4), x},
  {1/(x^2 - 9), x},
  {1/(x^2 - 25), x},

  (* Formula 46 (+): x/(c^2 + x^2) *)
  {x/(4 + x^2), x},
  {x/(9 + x^2), x},
  {x/(16 + x^2), x},

  (* Formula 46 (-): x/(c^2 - x^2) *)
  {x/(4 - x^2), x},
  {x/(9 - x^2), x},
  {x/(25 - x^2), x},

  (* Formula 47 (+): x/(c^2 + x^2)^m *)
  {x/(4 + x^2)^2, x},
  {x/(9 + x^2)^3, x},
  {x/(16 + x^2)^4, x},

  (* Formula 47 (-): x/(c^2 - x^2)^m *)
  {x/(4 - x^2)^2, x},
  {x/(9 - x^2)^3, x},
  {x/(25 - x^2)^4, x},

  (* Formula 48 (+): 1/(c^2 + x^2)^n *)
  {1/(4 + x^2)^2, x},
  {1/(9 + x^2)^2, x},
  {1/(16 + x^2)^3, x},

  (* Formula 48 (-): 1/(c^2 - x^2)^n *)
  {1/(4 - x^2)^2, x},
  {1/(9 - x^2)^2, x},
  {1/(25 - x^2)^3, x},

  (* Formula 49: 1/(x^2 - c^2)^n *)
  {1/(x^2 - 4)^2, x},
  {1/(x^2 - 9)^2, x},
  {1/(x^2 - 16)^3, x},

  (* Formula 50: x/(x^2 - c^2) *)
  {x/(x^2 - 4), x},
  {x/(x^2 - 9), x},
  {x/(x^2 - 25), x},

  (* Formula 51: x/(x^2 - c^2)^m *)
  {x/(x^2 - 4)^2, x},
  {x/(x^2 - 9)^3, x},
  {x/(x^2 - 16)^4, x},

  (* ============================================================ *)
  (* SECTION 3: a + b x and c + d x (Formulas 52-100)               *)
  (* ============================================================ *)

  (* Formula 52: 1/((a + b x)(c + d x)) *)
  {1/((1 + 2 x)(3 + 5 x)), x},
  {1/((2 + x)(1 + 3 x)), x},
  {1/((4 + 3 x)(1 + 2 x)), x},

  (* Formula 53: x/((a + b x)(c + d x)) *)
  {x/((1 + 2 x)(3 + 5 x)), x},
  {x/((2 + x)(1 + 3 x)), x},
  {x/((4 + 3 x)(1 + 2 x)), x},

  (* Formula 54: 1/((a + b x)^2 (c + d x)) *)
  {1/((1 + 2 x)^2 (3 + 5 x)), x},
  {1/((2 + x)^2 (1 + 3 x)), x},
  {1/((4 + 3 x)^2 (1 + 2 x)), x},

  (* Formula 55: x/((a + b x)^2 (c + d x)) *)
  {x/((1 + 2 x)^2 (3 + 5 x)), x},
  {x/((2 + x)^2 (1 + 3 x)), x},
  {x/((4 + 3 x)^2 (1 + 2 x)), x},

  (* Formula 56: x^2/((a + b x)^2 (c + d x)) *)
  {x^2/((1 + 2 x)^2 (3 + 5 x)), x},
  {x^2/((2 + x)^2 (1 + 3 x)), x},
  {x^2/((4 + 3 x)^2 (1 + 2 x)), x},

  (* Formula 58: (a + b x)/(c + d x) *)
  {(1 + 2 x)/(3 + 5 x), x},
  {(2 + x)/(1 + 3 x), x},
  {(4 + 3 x)/(1 + 2 x), x},

  (* Formula 60: 1/(a + b x^2), a b > 0 *)
  {1/(2 + 3 x^2), x},
  {1/(5 + x^2), x},
  {1/(1 + 4 x^2), x},

  (* Formula 61: 1/(a + b x^2), a b < 0 *)
  {1/(2 - 3 x^2), x},
  {1/(5 - x^2), x},
  {1/(-1 + 4 x^2), x},

  (* Formula 62: 1/(a^2 + b^2 x^2) *)
  {1/(4 + 9 x^2), x},
  {1/(1 + 16 x^2), x},
  {1/(25 + 4 x^2), x},

  (* Formula 63: x/(a + b x^2) *)
  {x/(2 + 3 x^2), x},
  {x/(1 + x^2), x},
  {x/(5 + 2 x^2), x},

  (* Formula 64: x^2/(a + b x^2) *)
  {x^2/(2 + 3 x^2), x},
  {x^2/(1 + x^2), x},
  {x^2/(5 + 2 x^2), x},

  (* Formula 65: 1/(a + b x^2)^2 *)
  {1/(2 + 3 x^2)^2, x},
  {1/(1 + x^2)^2, x},
  {1/(5 + 2 x^2)^2, x},

  (* Formula 66: 1/(a^2 - b^2 x^2) *)
  {1/(4 - 9 x^2), x},
  {1/(1 - 16 x^2), x},
  {1/(25 - 4 x^2), x},

  (* Formula 67: 1/(a + b x^2)^m, m > 1 *)
  {1/(2 + 3 x^2)^3, x},
  {1/(1 + x^2)^3, x},
  {1/(5 + 2 x^2)^4, x},

  (* Formula 68: x/(a + b x^2)^m *)
  {x/(2 + 3 x^2)^3, x},
  {x/(1 + x^2)^4, x},
  {x/(5 + 2 x^2)^2, x},

  (* Formula 69: x^2/(a + b x^2)^m, m > 1 *)
  {x^2/(2 + 3 x^2)^2, x},
  {x^2/(1 + x^2)^3, x},
  {x^2/(5 + 2 x^2)^2, x},

  (* Formula 70: 1/(x (a + b x^2)) *)
  {1/(x (2 + 3 x^2)), x},
  {1/(x (1 + x^2)), x},
  {1/(x (5 + 2 x^2)), x},

  (* Formula 71: 1/(x^2 (a + b x^2)) *)
  {1/(x^2 (2 + 3 x^2)), x},
  {1/(x^2 (1 + x^2)), x},
  {1/(x^2 (5 + 2 x^2)), x},

  (* Formula 72: 1/(x (a + b x^2)^n), n > 1 *)
  {1/(x (2 + 3 x^2)^2), x},
  {1/(x (1 + x^2)^2), x},
  {1/(x (5 + 2 x^2)^3), x},

  (* Formula 73: 1/(x^2 (a + b x^2)^n), n > 1 *)
  {1/(x^2 (2 + 3 x^2)^2), x},
  {1/(x^2 (1 + x^2)^2), x},
  {1/(x^2 (5 + 2 x^2)^3), x},

  (* Formula 74: 1/(a + b x^3) *)
  {1/(8 + x^3), x},
  {1/(27 + x^3), x},
  {1/(1 + 8 x^3), x},

  (* Formula 75: x/(a + b x^3) *)
  {x/(8 + x^3), x},
  {x/(27 + x^3), x},
  {x/(1 + 8 x^3), x},

  (* Formula 76: x^2/(a + b x^3) *)
  {x^2/(8 + x^3), x},
  {x^2/(1 + x^3), x},
  {x^2/(5 + 2 x^3), x},

  (* Formula 77 (+): 1/(a + b x^4), a b > 0 *)
  {1/(4 + x^4), x},
  {1/(16 + x^4), x},
  {1/(1 + 4 x^4), x},

  (* Formula 77 (-): 1/(a + b x^4), a b < 0 *)
  {1/(4 - x^4), x},
  {1/(16 - x^4), x},
  {1/(-1 + 4 x^4), x},

  (* Formula 78 (+): x/(a + b x^4), a b > 0 *)
  {x/(4 + x^4), x},
  {x/(16 + x^4), x},
  {x/(1 + 4 x^4), x},

  (* Formula 79 (-): x/(a + b x^4), a b < 0 *)
  {x/(4 - x^4), x},
  {x/(16 - x^4), x},
  {x/(-1 + 4 x^4), x},

  (* Formula 80 (+): x^2/(a + b x^4), a b > 0 *)
  {x^2/(4 + x^4), x},
  {x^2/(16 + x^4), x},
  {x^2/(1 + 4 x^4), x},

  (* Formula 81 (-): x^2/(a + b x^4), a b < 0 *)
  {x^2/(4 - x^4), x},
  {x^2/(16 - x^4), x},
  {x^2/(-1 + 4 x^4), x},

  (* Formula 82: x^3/(a + b x^4) *)
  {x^3/(4 + x^4), x},
  {x^3/(1 + x^4), x},
  {x^3/(5 + 2 x^4), x},

  (* Formula 83: 1/(x (a + b x^n)) *)
  {1/(x (2 + 3 x^5)), x},
  {1/(x (1 + x^4)), x},
  {1/(x (5 + 2 x^6)), x},

  (* Formula 88 (+): 1/(c^3 + x^3) *)
  {1/(8 + x^3), x},
  {1/(27 + x^3), x},
  {1/(64 + x^3), x},

  (* Formula 88 (-): 1/(c^3 - x^3) *)
  {1/(8 - x^3), x},
  {1/(27 - x^3), x},
  {1/(64 - x^3), x},

  (* Formula 89 (+): 1/(c^3 + x^3)^2 *)
  {1/(8 + x^3)^2, x},
  {1/(27 + x^3)^2, x},
  {1/(64 + x^3)^2, x},

  (* Formula 89 (-): 1/(c^3 - x^3)^2 *)
  {1/(8 - x^3)^2, x},
  {1/(27 - x^3)^2, x},
  {1/(64 - x^3)^2, x},

  (* Formula 90 (+): 1/(c^3 + x^3)^n, n > 1 *)
  {1/(8 + x^3)^3, x},
  {1/(27 + x^3)^3, x},
  {1/(64 + x^3)^4, x},

  (* Formula 90 (-): 1/(c^3 - x^3)^n, n > 1 *)
  {1/(8 - x^3)^3, x},
  {1/(27 - x^3)^3, x},
  {1/(64 - x^3)^4, x},

  (* Formula 91 (+): x/(c^3 + x^3) *)
  {x/(8 + x^3), x},
  {x/(27 + x^3), x},
  {x/(64 + x^3), x},

  (* Formula 91 (-): x/(c^3 - x^3) *)
  {x/(8 - x^3), x},
  {x/(27 - x^3), x},
  {x/(64 - x^3), x},

  (* Formula 92 (+): x/(c^3 + x^3)^2 *)
  {x/(8 + x^3)^2, x},
  {x/(27 + x^3)^2, x},
  {x/(64 + x^3)^2, x},

  (* Formula 92 (-): x/(c^3 - x^3)^2 *)
  {x/(8 - x^3)^2, x},
  {x/(27 - x^3)^2, x},
  {x/(64 - x^3)^2, x},

  (* Formula 93 (+): x/(c^3 + x^3)^n, n > 1 *)
  {x/(8 + x^3)^3, x},
  {x/(27 + x^3)^3, x},
  {x/(64 + x^3)^4, x},

  (* Formula 93 (-): x/(c^3 - x^3)^n, n > 1 *)
  {x/(8 - x^3)^3, x},
  {x/(27 - x^3)^3, x},
  {x/(64 - x^3)^4, x},

  (* Formula 94 (+): x^2/(c^3 + x^3) *)
  {x^2/(8 + x^3), x},
  {x^2/(27 + x^3), x},
  {x^2/(64 + x^3), x},

  (* Formula 94 (-): x^2/(c^3 - x^3) *)
  {x^2/(8 - x^3), x},
  {x^2/(27 - x^3), x},
  {x^2/(64 - x^3), x},

  (* Formula 95 (+): x^2/(c^3 + x^3)^n *)
  {x^2/(8 + x^3)^2, x},
  {x^2/(27 + x^3)^3, x},
  {x^2/(64 + x^3)^4, x},

  (* Formula 95 (-): x^2/(c^3 - x^3)^n *)
  {x^2/(8 - x^3)^2, x},
  {x^2/(27 - x^3)^3, x},
  {x^2/(64 - x^3)^4, x},

  (* Formula 96 (+): 1/(x (c^3 + x^3)) *)
  {1/(x (8 + x^3)), x},
  {1/(x (27 + x^3)), x},
  {1/(x (64 + x^3)), x},

  (* Formula 96 (-): 1/(x (c^3 - x^3)) *)
  {1/(x (8 - x^3)), x},
  {1/(x (27 - x^3)), x},
  {1/(x (64 - x^3)), x},

  (* Formula 97 (+): 1/(x (c^3 + x^3)^2) *)
  {1/(x (8 + x^3)^2), x},
  {1/(x (1 + x^3)^2), x},
  {1/(x (27 + x^3)^2), x},

  (* Formula 97 (-): 1/(x (c^3 - x^3)^2) *)
  {1/(x (8 - x^3)^2), x},
  {1/(x (27 - x^3)^2), x},
  {1/(x (64 - x^3)^2), x},

  (* Formula 98: 1/(x (c^3 +/- x^3)^n), n > 1 *)
  {1/(x (8 + x^3)^3), x},
  {1/(x (1 + x^3)^3), x},
  {1/(x (8 - x^3)^2), x},

  (* Formula 99 (+/-): 1/(x^2 (c^3 +/- x^3)) *)
  {1/(x^2 (8 + x^3)), x},
  {1/(x^2 (1 + x^3)), x},
  {1/(x^2 (27 - x^3)), x},

  (* Formula 100: 1/(x^2 (c^3 +/- x^3)^n), n > 1 *)
  {1/(x^2 (8 + x^3)^2), x},
  {1/(x^2 (1 + x^3)^2), x},
  {1/(x^2 (8 - x^3)^2), x},

  (* ============================================================ *)
  (* SECTION 4: x^4 forms and quadratic a + b x + c x^2 (101-121)  *)
  (* ============================================================ *)

  (* Formula 101: 1/(c^4 + x^4) *)
  {1/(1 + x^4), x},
  {1/(16 + x^4), x},
  {1/(81 + x^4), x},

  (* Formula 102: 1/(c^4 - x^4) *)
  {1/(1 - x^4), x},
  {1/(16 - x^4), x},
  {1/(81 - x^4), x},

  (* Formula 103: x/(c^4 + x^4) *)
  {x/(1 + x^4), x},
  {x/(16 + x^4), x},
  {x/(81 + x^4), x},

  (* Formula 104: x/(c^4 - x^4) *)
  {x/(1 - x^4), x},
  {x/(16 - x^4), x},
  {x/(81 - x^4), x},

  (* Formula 105: x^2/(c^4 + x^4) *)
  {x^2/(1 + x^4), x},
  {x^2/(16 + x^4), x},
  {x^2/(81 + x^4), x},

  (* Formula 106: x^2/(c^4 - x^4) *)
  {x^2/(1 - x^4), x},
  {x^2/(16 - x^4), x},
  {x^2/(81 - x^4), x},

  (* Formula 107: x^3/(c^4 +/- x^4) *)
  {x^3/(1 + x^4), x},
  {x^3/(16 + x^4), x},
  {x^3/(1 - x^4), x},

  (* Formula 108: 1/(a + b x + c x^2) with discriminant sign branches *)
  {1/(1 + x + x^2), x},
  {1/(2 + 3 x + x^2), x},
  {1/(1 + 2 x + 5 x^2), x},

  (* Formula 109: 1/(a + b x + c x^2)^2 *)
  {1/(1 + x + x^2)^2, x},
  {1/(2 + x + x^2)^2, x},
  {1/(1 + 3 x + 2 x^2)^2, x},

  (* Formula 110: 1/(a + b x + c x^2)^3 *)
  {1/(1 + x + x^2)^3, x},
  {1/(2 + x + x^2)^3, x},
  {1/(1 + 2 x + 3 x^2)^3, x},

  (* Formula 111: 1/(a + b x + c x^2)^n, n > 1 *)
  {1/(1 + x + x^2)^4, x},
  {1/(2 + x + x^2)^5, x},
  {1/(1 + 2 x + x^2)^4, x},

  (* Formula 112: x/(a + b x + c x^2) *)
  {x/(1 + x + x^2), x},
  {x/(2 + 3 x + x^2), x},
  {x/(1 + x + 2 x^2), x},

  (* Formula 113: x/(a + b x + c x^2)^2 *)
  {x/(1 + x + x^2)^2, x},
  {x/(2 + x + x^2)^2, x},
  {x/(1 + 3 x + 2 x^2)^2, x},

  (* Formula 114: x/(a + b x + c x^2)^n, n > 1 *)
  {x/(1 + x + x^2)^3, x},
  {x/(2 + x + x^2)^4, x},
  {x/(1 + 2 x + 3 x^2)^3, x},

  (* Formula 115: x^2/(a + b x + c x^2) *)
  {x^2/(1 + x + x^2), x},
  {x^2/(2 + 3 x + x^2), x},
  {x^2/(1 + x + 2 x^2), x},

  (* Formula 116: x^2/(a + b x + c x^2)^2 *)
  {x^2/(1 + x + x^2)^2, x},
  {x^2/(2 + x + x^2)^2, x},
  {x^2/(1 + 3 x + 2 x^2)^2, x},

  (* Formula 117: x^m/(a + b x + c x^2)^n, m > 1, n > 1 *)
  {x^2/(1 + x + x^2)^2, x},
  {x^3/(1 + x + x^2)^2, x},
  {x^2/(2 + x + 3 x^2)^3, x},

  (* Formula 118: 1/(x (a + b x + c x^2)) *)
  {1/(x (1 + x + x^2)), x},
  {1/(x (2 + 3 x + x^2)), x},
  {1/(x (1 + x + 2 x^2)), x},

  (* Formula 119: 1/(x^2 (a + b x + c x^2)) *)
  {1/(x^2 (1 + x + x^2)), x},
  {1/(x^2 (2 + 3 x + x^2)), x},
  {1/(x^2 (1 + x + 2 x^2)), x},

  (* Formula 120: 1/(x (a + b x + c x^2)^n), n > 1 *)
  {1/(x (1 + x + x^2)^2), x},
  {1/(x (2 + x + x^2)^2), x},
  {1/(x (1 + 2 x + 3 x^2)^3), x},

  (* Formula 121: 1/(x^m (a + b x + c x^2)^n), m > 1 *)
  {1/(x^2 (1 + x + x^2)^2), x},
  {1/(x^3 (2 + x + x^2)^2), x},
  {1/(x^2 (1 + 2 x + 3 x^2)^3), x},

  (* ============================================================ *)
  (* SECTION 5: Sqrt[a + b x] (Formulas 122-148)                   *)
  (* ============================================================ *)

  (* Formula 122: Sqrt[a + b x] *)
  {Sqrt[1 + x], x},
  {Sqrt[2 + 3 x], x},
  {Sqrt[5 + x], x},

  (* Formula 123: x Sqrt[a + b x] *)
  {x Sqrt[1 + x], x},
  {x Sqrt[2 + 3 x], x},
  {x Sqrt[5 + x], x},

  (* Formula 124: x^2 Sqrt[a + b x] *)
  {x^2 Sqrt[1 + x], x},
  {x^2 Sqrt[2 + 3 x], x},
  {x^2 Sqrt[5 + x], x},

  (* Formula 125: x^m Sqrt[a + b x] *)
  {x^3 Sqrt[1 + x], x},
  {x^4 Sqrt[2 + 3 x], x},
  {x^5 Sqrt[1 + x], x},

  (* Formula 126: Sqrt[a + b x]/x *)
  {Sqrt[1 + x]/x, x},
  {Sqrt[2 + 3 x]/x, x},
  {Sqrt[5 + x]/x, x},

  (* Formula 127: Sqrt[a + b x]/x^m, m > 1 *)
  {Sqrt[1 + x]/x^2, x},
  {Sqrt[2 + 3 x]/x^3, x},
  {Sqrt[5 + x]/x^2, x},

  (* Formula 128: 1/Sqrt[a + b x] *)
  {1/Sqrt[1 + x], x},
  {1/Sqrt[2 + 3 x], x},
  {1/Sqrt[5 + x], x},

  (* Formula 129: x/Sqrt[a + b x] *)
  {x/Sqrt[1 + x], x},
  {x/Sqrt[2 + 3 x], x},
  {x/Sqrt[5 + x], x},

  (* Formula 130: x^2/Sqrt[a + b x] *)
  {x^2/Sqrt[1 + x], x},
  {x^2/Sqrt[2 + 3 x], x},
  {x^2/Sqrt[5 + x], x},

  (* Formula 131: x^m/Sqrt[a + b x] *)
  {x^3/Sqrt[1 + x], x},
  {x^4/Sqrt[2 + 3 x], x},
  {x^5/Sqrt[1 + x], x},

  (* Formula 132: 1/(x Sqrt[a + b x]) sign-split branches *)
  {1/(x Sqrt[-1 + x]), x},
  {1/(x Sqrt[-4 + 3 x]), x},
  {1/(x Sqrt[4 + x]), x},

  (* Formula 133: 1/(x^2 Sqrt[a + b x]) *)
  {1/(x^2 Sqrt[1 + x]), x},
  {1/(x^2 Sqrt[2 + 3 x]), x},
  {1/(x^2 Sqrt[5 + x]), x},

  (* Formula 134: 1/(x^n Sqrt[a + b x]), n > 1 *)
  {1/(x^2 Sqrt[1 + x]), x},
  {1/(x^3 Sqrt[2 + 3 x]), x},
  {1/(x^4 Sqrt[5 + x]), x},

  (* Formula 135 & 136: (a + b x)^m *)
  {(1 + x)^3, x},
  {(2 + 3 x)^(5/2), x},
  {(1 + 2 x)^(-3), x},

  (* Formula 135b: x (a + b x)^m *)
  {x (1 + x)^3, x},
  {x (2 + 3 x)^(5/2), x},
  {x (1 + 2 x)^4, x},

  (* Formula 137: 1/(x (a + b x)^m), m > 1 integer *)
  {1/(x (1 + x)^2), x},
  {1/(x (2 + 3 x)^3), x},
  {1/(x (1 + 2 x)^2), x},

  (* Formula 138: (a + b x)^m / x, m > 0 integer *)
  {(1 + x)^2/x, x},
  {(2 + 3 x)^3/x, x},
  {(1 + 2 x)^4/x, x},

  (* Formula 139: 1/Sqrt[(a + b x)(c + d x)] both sign branches of b d *)
  {1/Sqrt[(1 + x) (2 + 3 x)], x},
  {1/Sqrt[(1 + 2 x) (3 + x)], x},
  {1/Sqrt[(1 + x) (2 - x)], x},

  (* Formula 140: Sqrt[(a + b x)(c + d x)] *)
  {Sqrt[(1 + x) (2 + 3 x)], x},
  {Sqrt[(1 + 2 x) (3 + x)], x},
  {Sqrt[(2 + x) (5 + 2 x)], x},

  (* Formula 141: 1/((a + b x) Sqrt[(a + b x)(c + d x)]) *)
  {1/((1 + x) Sqrt[(1 + x) (2 + 3 x)]), x},
  {1/((1 + 2 x) Sqrt[(1 + 2 x) (3 + x)]), x},
  {1/((2 + x) Sqrt[(2 + x) (5 + 2 x)]), x},

  (* Formula 142: x/Sqrt[(a + b x)(c + d x)] *)
  {x/Sqrt[(1 + x) (2 + 3 x)], x},
  {x/Sqrt[(1 + 2 x) (3 + x)], x},
  {x/Sqrt[(2 + x) (5 + 2 x)], x},

  (* Formula 143: 1/((c + d x) Sqrt[(a + b x)(c + d x)]) *)
  {1/((2 + 3 x) Sqrt[(1 + x) (2 + 3 x)]), x},
  {1/((3 + x) Sqrt[(1 + 2 x) (3 + x)]), x},
  {1/((5 + 2 x) Sqrt[(2 + x) (5 + 2 x)]), x},

  (* Formula 144: (c + d x)/Sqrt[(a + b x)(c + d x)] *)
  {(2 + 3 x)/Sqrt[(1 + x) (2 + 3 x)], x},
  {(3 + x)/Sqrt[(1 + 2 x) (3 + x)], x},
  {(5 + 2 x)/Sqrt[(2 + x) (5 + 2 x)], x},

  (* Formula 145: Sqrt[(c + d x)/(a + b x)] *)
  {Sqrt[(2 + 3 x)/(1 + x)], x},
  {Sqrt[(3 + x)/(1 + 2 x)], x},
  {Sqrt[(5 + 2 x)/(2 + x)], x},

  (* Formula 146: (c + d x)^m Sqrt[a + b x] *)
  {(2 + 3 x)^2 Sqrt[1 + x], x},
  {(3 + x)^3 Sqrt[1 + 2 x], x},
  {(5 + 2 x) Sqrt[2 + x], x},

  (* Formula 147: 1/((c + d x)^m Sqrt[a + b x]), m > 1 *)
  {1/((2 + 3 x)^2 Sqrt[1 + x]), x},
  {1/((3 + x)^3 Sqrt[1 + 2 x]), x},
  {1/((5 + 2 x)^2 Sqrt[2 + x]), x},

  (* Formula 148: (c + d x)^m/Sqrt[a + b x], m > 0 *)
  {(2 + 3 x)^1/Sqrt[1 + x], x},
  {(3 + x)^2/Sqrt[1 + 2 x], x},
  {(5 + 2 x)^3/Sqrt[2 + x], x},

  (* ============================================================ *)
  (* SECTION 6: Sqrt[x^2 +/- a^2] (Formulas 149-225)               *)
  (* ============================================================ *)

  (* Formula 149: Sqrt[x^2 +/- a^2] *)
  {Sqrt[x^2 + 1], x},
  {Sqrt[x^2 + 4], x},
  {Sqrt[x^2 - 9], x},

  (* Formula 150: 1/Sqrt[x^2 +/- a^2] *)
  {1/Sqrt[x^2 + 1], x},
  {1/Sqrt[x^2 + 4], x},
  {1/Sqrt[x^2 - 9], x},

  (* Formula 151: 1/(x Sqrt[x^2 - a^2]) *)
  {1/(x Sqrt[x^2 - 1]), x},
  {1/(x Sqrt[x^2 - 4]), x},
  {1/(x Sqrt[x^2 - 25]), x},

  (* Formula 152: 1/(x Sqrt[x^2 + a^2]) *)
  {1/(x Sqrt[x^2 + 1]), x},
  {1/(x Sqrt[x^2 + 4]), x},
  {1/(x Sqrt[x^2 + 9]), x},

  (* Formula 153: Sqrt[x^2 + a^2]/x *)
  {Sqrt[x^2 + 1]/x, x},
  {Sqrt[x^2 + 4]/x, x},
  {Sqrt[x^2 + 9]/x, x},

  (* Formula 154: Sqrt[x^2 - a^2]/x *)
  {Sqrt[x^2 - 1]/x, x},
  {Sqrt[x^2 - 4]/x, x},
  {Sqrt[x^2 - 1]/x, x},

  (* Formula 155: x/Sqrt[x^2 +/- a^2] *)
  {x/Sqrt[x^2 + 1], x},
  {x/Sqrt[x^2 + 9], x},
  {x/Sqrt[x^2 - 4], x},

  (* Formula 156: x Sqrt[x^2 +/- a^2] *)
  {x Sqrt[x^2 + 1], x},
  {x Sqrt[x^2 + 4], x},
  {x Sqrt[x^2 - 9], x},

  (* Formula 157: (x^2 +/- a^2)^(3/2) *)
  {(x^2 + 1)^(3/2), x},
  {(x^2 + 4)^(3/2), x},
  {(x^2 - 9)^(3/2), x},

  (* Formula 158: 1/(x^2 +/- a^2)^(3/2) *)
  {1/(x^2 + 1)^(3/2), x},
  {1/(x^2 + 4)^(3/2), x},
  {1/(x^2 - 9)^(3/2), x},

  (* Formula 159: x/(x^2 +/- a^2)^(3/2) *)
  {x/(x^2 + 1)^(3/2), x},
  {x/(x^2 + 4)^(3/2), x},
  {x/(x^2 - 9)^(3/2), x},

  (* Formula 160: x (x^2 +/- a^2)^(3/2) *)
  {x (x^2 + 1)^(3/2), x},
  {x (x^2 + 4)^(3/2), x},
  {x (x^2 - 9)^(3/2), x},

  (* Formula 161: x^2 Sqrt[x^2 +/- a^2] *)
  {x^2 Sqrt[x^2 + 1], x},
  {x^2 Sqrt[x^2 + 4], x},
  {x^2 Sqrt[x^2 - 9], x},

  (* Formula 162: x^3 Sqrt[x^2 + a^2] *)
  {x^3 Sqrt[x^2 + 1], x},
  {x^3 Sqrt[x^2 + 4], x},
  {x^3 Sqrt[x^2 + 9], x},

  (* Formula 163: x^3 Sqrt[x^2 - a^2] *)
  {x^3 Sqrt[x^2 - 1], x},
  {x^3 Sqrt[x^2 - 4], x},
  {x^3 Sqrt[x^2 - 25], x},

  (* Formula 164: x^2/Sqrt[x^2 +/- a^2] *)
  {x^2/Sqrt[x^2 + 1], x},
  {x^2/Sqrt[x^2 + 4], x},
  {x^2/Sqrt[x^2 - 9], x},

  (* Formula 165: x^3/Sqrt[x^2 +/- a^2] *)
  {x^3/Sqrt[x^2 + 1], x},
  {x^3/Sqrt[x^2 + 4], x},
  {x^3/Sqrt[x^2 - 9], x},

  (* Formula 166: 1/(x^2 Sqrt[x^2 +/- a^2]) *)
  {1/(x^2 Sqrt[x^2 + 1]), x},
  {1/(x^2 Sqrt[x^2 + 4]), x},
  {1/(x^2 Sqrt[x^2 - 9]), x},

  (* Formula 167: 1/(x^3 Sqrt[x^2 + a^2]) *)
  {1/(x^3 Sqrt[x^2 + 1]), x},
  {1/(x^3 Sqrt[x^2 + 4]), x},
  {1/(x^3 Sqrt[x^2 + 9]), x},

  (* Formula 168: 1/(x^3 Sqrt[x^2 - a^2]) *)
  {1/(x^3 Sqrt[x^2 - 1]), x},
  {1/(x^3 Sqrt[x^2 - 4]), x},
  {1/(x^3 Sqrt[x^2 - 1]), x},

  (* Formula 169: x^2 (x^2 +/- a^2)^(3/2) *)
  {x^2 (x^2 + 1)^(3/2), x},
  {x^2 (x^2 + 4)^(3/2), x},
  {x^2 (x^2 - 9)^(3/2), x},

  (* Formula 170: x^3 (x^2 +/- a^2)^(3/2) *)
  {x^3 (x^2 + 1)^(3/2), x},
  {x^3 (x^2 + 4)^(3/2), x},
  {x^3 (x^2 - 9)^(3/2), x},

  (* Formula 171: Sqrt[x^2 +/- a^2]/x^2 *)
  {Sqrt[x^2 + 1]/x^2, x},
  {Sqrt[x^2 + 4]/x^2, x},
  {Sqrt[x^2 - 9]/x^2, x},

  (* Formula 172: Sqrt[x^2 + a^2]/x^3 *)
  {Sqrt[x^2 + 1]/x^3, x},
  {Sqrt[x^2 + 4]/x^3, x},
  {Sqrt[x^2 + 9]/x^3, x},

  (* Formula 173: Sqrt[x^2 - a^2]/x^3 *)
  {Sqrt[x^2 - 1]/x^3, x},
  {Sqrt[x^2 - 4]/x^3, x},
  {Sqrt[x^2 - 1]/x^3, x},

  (* Formula 174: Sqrt[x^2 +/- a^2]/x^4 *)
  {Sqrt[x^2 + 1]/x^4, x},
  {Sqrt[x^2 + 4]/x^4, x},
  {Sqrt[x^2 - 9]/x^4, x},

  (* Formula 175: x^2/(x^2 +/- a^2)^(3/2) *)
  {x^2/(x^2 + 1)^(3/2), x},
  {x^2/(x^2 + 4)^(3/2), x},
  {x^2/(x^2 - 9)^(3/2), x},

  (* Formula 176: x^3/(x^2 +/- a^2)^(3/2) *)
  {x^3/(x^2 + 1)^(3/2), x},
  {x^3/(x^2 + 4)^(3/2), x},
  {x^3/(x^2 - 9)^(3/2), x},

  (* Formula 177: 1/(x (x^2 + a^2)^(3/2)) *)
  {1/(x (x^2 + 4)^(3/2)), x},
  {1/(x (x^2 + 9)^(3/2)), x},
  {1/(x (x^2 + 25)^(3/2)), x},

  (* Formula 178: 1/(x (x^2 - a^2)^(3/2)) *)
  {1/(x (x^2 - 4)^(3/2)), x},
  {1/(x (x^2 - 1)^(3/2)), x},
  {1/(x (x^2 - 4)^(3/2)), x},

  (* Formula 179: 1/(x^2 (x^2 +/- a^2)^(3/2)) *)
  {1/(x^2 (x^2 + 4)^(3/2)), x},
  {1/(x^2 (x^2 - 9)^(3/2)), x},
  {1/(x^2 (x^2 + 16)^(3/2)), x},

  (* Formula 180: 1/(x^3 (x^2 + a^2)^(3/2)) *)
  {1/(x^3 (x^2 + 4)^(3/2)), x},
  {1/(x^3 (x^2 + 9)^(3/2)), x},
  {1/(x^3 (x^2 + 25)^(3/2)), x},

  (* Formula 181: 1/(x^3 (x^2 - a^2)^(3/2)) *)
  {1/(x^3 (x^2 - 4)^(3/2)), x},
  {1/(x^3 (x^2 - 1)^(3/2)), x},
  {1/(x^3 (x^2 - 4)^(3/2)), x},

  (* Formula 182: x^m/Sqrt[x^2 +/- a^2], m > 1 *)
  {x^2/Sqrt[x^2 + 4], x},
  {x^3/Sqrt[x^2 + 9], x},
  {x^2/Sqrt[x^2 - 9], x},

  (* Formula 185: 1/(x^m Sqrt[x^2 +/- a^2]), m > 2 *)
  {1/(x^3 Sqrt[x^2 + 4]), x},
  {1/(x^4 Sqrt[x^2 + 9]), x},
  {1/(x^3 Sqrt[x^2 - 4]), x},

  (* Formula 189 & 190: 1/((x -/+ a) Sqrt[x^2 - a^2]) *)
  {1/((x - 2) Sqrt[x^2 - 4]), x},
  {1/((x + 3) Sqrt[x^2 - 9]), x},
  {1/((x - 5) Sqrt[x^2 - 25]), x},

  (* Formula 191: Sqrt[a^2 - x^2] *)
  {Sqrt[4 - x^2], x},
  {Sqrt[9 - x^2], x},
  {Sqrt[25 - x^2], x},

  (* Formula 192: 1/Sqrt[a^2 - x^2] *)
  {1/Sqrt[4 - x^2], x},
  {1/Sqrt[9 - x^2], x},
  {1/Sqrt[16 - x^2], x},

  (* Formula 193: 1/(x Sqrt[a^2 - x^2]) *)
  {1/(x Sqrt[4 - x^2]), x},
  {1/(x Sqrt[9 - x^2]), x},
  {1/(x Sqrt[25 - x^2]), x},

  (* Formula 194: Sqrt[a^2 - x^2]/x *)
  {Sqrt[4 - x^2]/x, x},
  {Sqrt[9 - x^2]/x, x},
  {Sqrt[16 - x^2]/x, x},

  (* Formula 195 & 196: x/Sqrt[a^2 - x^2] and x Sqrt[a^2 - x^2] *)
  {x/Sqrt[9 - x^2], x},
  {x Sqrt[4 - x^2], x},
  {x Sqrt[25 - x^2], x},

  (* Formula 197: (a^2 - x^2)^(3/2) *)
  {(4 - x^2)^(3/2), x},
  {(9 - x^2)^(3/2), x},
  {(16 - x^2)^(3/2), x},

  (* Formula 198 & 199: 1/(a^2 - x^2)^(3/2) and x/(a^2 - x^2)^(3/2) *)
  {1/(4 - x^2)^(3/2), x},
  {1/(9 - x^2)^(3/2), x},
  {x/(16 - x^2)^(3/2), x},

  (* Formula 200: x (a^2 - x^2)^(3/2) *)
  {x (4 - x^2)^(3/2), x},
  {x (9 - x^2)^(3/2), x},
  {x (25 - x^2)^(3/2), x},

  (* Formula 201: x^2 Sqrt[a^2 - x^2] *)
  {x^2 Sqrt[4 - x^2], x},
  {x^2 Sqrt[9 - x^2], x},
  {x^2 Sqrt[16 - x^2], x},

  (* Formula 202: x^3 Sqrt[a^2 - x^2] *)
  {x^3 Sqrt[4 - x^2], x},
  {x^3 Sqrt[9 - x^2], x},
  {x^3 Sqrt[25 - x^2], x},

  (* Formula 203: x^2 (a^2 - x^2)^(3/2) *)
  {x^2 (4 - x^2)^(3/2), x},
  {x^2 (9 - x^2)^(3/2), x},
  {x^2 (16 - x^2)^(3/2), x},

  (* Formula 204: x^3 (a^2 - x^2)^(3/2) *)
  {x^3 (4 - x^2)^(3/2), x},
  {x^3 (9 - x^2)^(3/2), x},
  {x^3 (25 - x^2)^(3/2), x},

  (* Formula 205: x^2/Sqrt[a^2 - x^2] *)
  {x^2/Sqrt[4 - x^2], x},
  {x^2/Sqrt[9 - x^2], x},
  {x^2/Sqrt[16 - x^2], x},

  (* Formula 206: 1/(x^2 Sqrt[a^2 - x^2]) *)
  {1/(x^2 Sqrt[4 - x^2]), x},
  {1/(x^2 Sqrt[9 - x^2]), x},
  {1/(x^2 Sqrt[25 - x^2]), x},

  (* Formula 207: Sqrt[a^2 - x^2]/x^2 *)
  {Sqrt[4 - x^2]/x^2, x},
  {Sqrt[9 - x^2]/x^2, x},
  {Sqrt[16 - x^2]/x^2, x},

  (* Formula 208: Sqrt[a^2 - x^2]/x^3 *)
  {Sqrt[4 - x^2]/x^3, x},
  {Sqrt[9 - x^2]/x^3, x},
  {Sqrt[25 - x^2]/x^3, x},

  (* Formula 209: Sqrt[a^2 - x^2]/x^4 *)
  {Sqrt[4 - x^2]/x^4, x},
  {Sqrt[9 - x^2]/x^4, x},
  {Sqrt[16 - x^2]/x^4, x},

  (* Formula 210: x^2/(a^2 - x^2)^(3/2) *)
  {x^2/(4 - x^2)^(3/2), x},
  {x^2/(9 - x^2)^(3/2), x},
  {x^2/(25 - x^2)^(3/2), x},

  (* Formula 211: x^3/Sqrt[a^2 - x^2] *)
  {x^3/Sqrt[4 - x^2], x},
  {x^3/Sqrt[9 - x^2], x},
  {x^3/Sqrt[16 - x^2], x},

  (* Formula 212: x^3/(a^2 - x^2)^(3/2) *)
  {x^3/(4 - x^2)^(3/2), x},
  {x^3/(9 - x^2)^(3/2), x},
  {x^3/(25 - x^2)^(3/2), x},

  (* Formula 213: 1/(x^3 Sqrt[a^2 - x^2]) *)
  {1/(x^3 Sqrt[4 - x^2]), x},
  {1/(x^3 Sqrt[9 - x^2]), x},
  {1/(x^3 Sqrt[16 - x^2]), x},

  (* Formula 214: 1/(x (a^2 - x^2)^(3/2)) *)
  {1/(x (4 - x^2)^(3/2)), x},
  {1/(x (9 - x^2)^(3/2)), x},
  {1/(x (25 - x^2)^(3/2)), x},

  (* Formula 215: 1/(x^2 (a^2 - x^2)^(3/2)) *)
  {1/(x^2 (4 - x^2)^(3/2)), x},
  {1/(x^2 (9 - x^2)^(3/2)), x},
  {1/(x^2 (16 - x^2)^(3/2)), x},

  (* Formula 216: 1/(x^3 (a^2 - x^2)^(3/2)) *)
  {1/(x^3 (4 - x^2)^(3/2)), x},
  {1/(x^3 (9 - x^2)^(3/2)), x},
  {1/(x^3 (25 - x^2)^(3/2)), x},

  (* Formula 217 & 220: x^m/Sqrt[a^2 - x^2] and 1/(x^m Sqrt[a^2 - x^2]) reductions *)
  {x^4/Sqrt[9 - x^2], x},
  {x^5/Sqrt[16 - x^2], x},
  {1/(x^4 Sqrt[4 - x^2]), x},

  (* Formula 223: 1/((b^2 - x^2) Sqrt[a^2 - x^2]), both branches *)
  {1/((4 - x^2) Sqrt[9 - x^2]), x},
  {1/((1 - x^2) Sqrt[4 - x^2]), x},
  {1/((9 - x^2) Sqrt[4 - x^2]), x},

  (* Formula 224: 1/((b^2 + x^2) Sqrt[a^2 - x^2]) *)
  {1/((4 + x^2) Sqrt[9 - x^2]), x},
  {1/((9 + x^2) Sqrt[16 - x^2]), x},
  {1/((1 + x^2) Sqrt[4 - x^2]), x},

  (* Formula 225: Sqrt[a^2 - x^2]/(b^2 + x^2) *)
  {Sqrt[4 - x^2]/(9 + x^2), x},
  {Sqrt[9 - x^2]/(4 + x^2), x},
  {Sqrt[16 - x^2]/(1 + x^2), x},

  (* ============================================================ *)
  (* SECTION 7: Sqrt[a + b x + c x^2] (Formulas 226-258)            *)
  (* ============================================================ *)

  (* Formula 226: 1/Sqrt[a + b x + c x^2], c > 0 and c < 0 branches *)
  {1/Sqrt[1 + 2 x + 3 x^2], x},
  {1/Sqrt[5 + 3 x + 2 x^2], x},
  {1/Sqrt[5 + 2 x - x^2], x},

  (* Formula 227 & 228: 1/(a + b x + c x^2)^(3/2) and ^(5/2) *)
  {1/(1 + 2 x + 3 x^2)^(3/2), x},
  {1/(5 + 3 x + 2 x^2)^(3/2), x},
  {1/(1 + 2 x + 3 x^2)^(5/2), x},

  (* Formula 229: 1/(X^n Sqrt[X]) reduction *)
  {1/((1 + 2 x + 3 x^2)^1 Sqrt[1 + 2 x + 3 x^2]), x},
  {1/((2 + 3 x + 5 x^2)^2 Sqrt[2 + 3 x + 5 x^2]), x},
  {1/((1 + x + x^2)^1 Sqrt[1 + x + x^2]), x},

  (* Formula 230-232: Sqrt[X], X^(3/2), X^(5/2) *)
  {Sqrt[1 + 2 x + 3 x^2], x},
  {(1 + 2 x + 3 x^2)^(3/2), x},
  {(2 + 3 x + 5 x^2)^(5/2), x},

  (* Formula 233: X^n Sqrt[X] reduction *)
  {(1 + 2 x + 3 x^2)^1 Sqrt[1 + 2 x + 3 x^2], x},
  {(2 + 3 x + 5 x^2)^2 Sqrt[2 + 3 x + 5 x^2], x},
  {(1 + x + x^2)^1 Sqrt[1 + x + x^2], x},

  (* Formula 234: x/Sqrt[a + b x + c x^2] *)
  {x/Sqrt[1 + 2 x + 3 x^2], x},
  {x/Sqrt[5 + 3 x + 2 x^2], x},
  {x/Sqrt[2 + x + x^2], x},

  (* Formula 235 & 236: x/(X)^(3/2) and x/(X^n Sqrt[X]) *)
  {x/(1 + 2 x + 3 x^2)^(3/2), x},
  {x/(5 + 3 x + 2 x^2)^(3/2), x},
  {x/((1 + 2 x + 3 x^2)^1 Sqrt[1 + 2 x + 3 x^2]), x},

  (* Formula 237-239: x^2/Sqrt[X], x^2/X^(3/2), x^2/(X^n Sqrt[X]) *)
  {x^2/Sqrt[1 + 2 x + 3 x^2], x},
  {x^2/(1 + 2 x + 3 x^2)^(3/2), x},
  {x^2/((2 + 3 x + 5 x^2)^1 Sqrt[2 + 3 x + 5 x^2]), x},

  (* Formula 240 & 241: x^3/Sqrt[X] and x^n/Sqrt[X] reduction *)
  {x^3/Sqrt[1 + 2 x + 3 x^2], x},
  {x^3/Sqrt[2 + 3 x + 5 x^2], x},
  {x^4/Sqrt[1 + 2 x + 3 x^2], x},

  (* Formula 242-245: x X^(3/2), x X^n Sqrt[X], x^2 Sqrt[X] *)
  {x (1 + 2 x + 3 x^2)^(3/2), x},
  {x (1 + 2 x + 3 x^2)^1 Sqrt[1 + 2 x + 3 x^2], x},
  {x^2 Sqrt[1 + 2 x + 3 x^2], x},

  (* Formula 246: 1/(x Sqrt[a + b x + c x^2]), a > 0 and a < 0 branches *)
  {1/(x Sqrt[2 + 3 x + 5 x^2]), x},
  {1/(x Sqrt[1 + 2 x + 3 x^2]), x},
  {1/(x Sqrt[-4 + 3 x + 5 x^2]), x},

  (* Formula 247-249: 1/(x^2 Sqrt[X]), Sqrt[X]/x, Sqrt[X]/x^2 *)
  {1/(x^2 Sqrt[1 + 2 x + 3 x^2]), x},
  {Sqrt[1 + 2 x + 3 x^2]/x, x},
  {Sqrt[2 + 3 x + 5 x^2]/x^2, x},

  (* Formula 250: Sqrt[2 a x - x^2] *)
  {Sqrt[4 x - x^2], x},
  {Sqrt[6 x - x^2], x},
  {Sqrt[10 x - x^2], x},

  (* Formula 251: 1/Sqrt[2 a x - x^2] *)
  {1/Sqrt[4 x - x^2], x},
  {1/Sqrt[6 x - x^2], x},
  {1/Sqrt[10 x - x^2], x},

  (* Formula 252: x^n Sqrt[2 a x - x^2] *)
  {x Sqrt[4 x - x^2], x},
  {x^2 Sqrt[6 x - x^2], x},
  {x^3 Sqrt[4 x - x^2], x},

  (* Formula 253: Sqrt[2 a x - x^2]/x^n *)
  {Sqrt[4 x - x^2]/x, x},
  {Sqrt[6 x - x^2]/x^2, x},
  {Sqrt[10 x - x^2]/x^3, x},

  (* Formula 254: x^n/Sqrt[2 a x - x^2] *)
  {x/Sqrt[4 x - x^2], x},
  {x^2/Sqrt[6 x - x^2], x},
  {x^3/Sqrt[10 x - x^2], x},

  (* Formula 255: 1/(x^n Sqrt[2 a x - x^2]) *)
  {1/(x Sqrt[4 x - x^2]), x},
  {1/(x^2 Sqrt[6 x - x^2]), x},
  {1/(x^3 Sqrt[10 x - x^2]), x},

  (* Formula 256: 1/(2 a x - x^2)^(3/2) *)
  {1/(4 x - x^2)^(3/2), x},
  {1/(6 x - x^2)^(3/2), x},
  {1/(10 x - x^2)^(3/2), x},

  (* Formula 257: x/(2 a x - x^2)^(3/2) *)
  {x/(4 x - x^2)^(3/2), x},
  {x/(6 x - x^2)^(3/2), x},
  {x/(10 x - x^2)^(3/2), x},

  (* Formula 258: 1/Sqrt[2 a x + x^2] *)
  {1/Sqrt[4 x + x^2], x},
  {1/Sqrt[6 x + x^2], x},
  {1/Sqrt[10 x + x^2], x},

  (* Formula 259: Sqrt[a x^2 + c], both a < 0 and a > 0 branches *)
  {Sqrt[-2 x^2 + 9], x},
  {Sqrt[3 x^2 + 4], x},
  {Sqrt[-5 x^2 + 16], x},

  (* Formula 260: Sqrt[(1+x)/(1-x)] *)
  {Sqrt[(1 + x)/(1 - x)], x},

  (* Formula 261: 1/(x Sqrt[a x^n + c]), c > 0 and c < 0 branches *)
  {1/(x Sqrt[2 x^3 + 9]), x},
  {1/(x Sqrt[3 x^2 + 4]), x},
  {1/(x Sqrt[2 x^3 - 9]), x},

  (* Formula 262: 1/Sqrt[a x^2 + c], a < 0 and a > 0 branches *)
  {1/Sqrt[-2 x^2 + 9], x},
  {1/Sqrt[3 x^2 + 4], x},
  {1/Sqrt[-5 x^2 + 16], x},

  (* Formula 263: (a x^2 + c)^m, integer m > 0 *)
  {(2 x^2 + 5)^2, x},
  {(3 x^2 + 7)^3, x},
  {(x^2 + 4)^3, x},

  (* Formula 264: x (a x^2 + c)^m *)
  {x (2 x^2 + 5)^3, x},
  {x (3 x^2 + 7)^(-2), x},
  {x (x^2 + 4)^4, x},

  (* Formula 265: (a x^2 + c)^m / x, integer m > 0 *)
  {(2 x^2 + 5)^2/x, x},
  {(3 x^2 + 7)^1/x, x},
  {(x^2 + 4)^3/x, x},

  (* Formula 266: 1/(a x^2 + c)^m, integer m > 1 *)
  {1/(2 x^2 + 5)^2, x},
  {1/(3 x^2 + 7)^3, x},
  {1/(x^2 + 4)^2, x},

  (* Formula 268: (1+x^2)/((1-x^2) Sqrt[1+x^4]) *)
  {(1 + x^2)/((1 - x^2) Sqrt[1 + x^4]), x},

  (* Formula 269: (1-x^2)/((1+x^2) Sqrt[1+x^4]) *)
  {(1 - x^2)/((1 + x^2) Sqrt[1 + x^4]), x},

  (* Formula 270: 1/(x Sqrt[x^n + a^2]) *)
  {1/(x Sqrt[x^3 + 4]), x},
  {1/(x Sqrt[x^2 + 9]), x},
  {1/(x Sqrt[x^4 + 25]), x},

  (* Formula 271: 1/(x Sqrt[x^n - a^2]) *)
  {1/(x Sqrt[x^3 - 4]), x},
  {1/(x Sqrt[x^2 - 9]), x},
  {1/(x Sqrt[x^4 - 25]), x},

  (* Formula 272: Sqrt[x/(a^3 - x^3)] *)
  {Sqrt[x/(8 - x^3)], x},
  {Sqrt[x/(27 - x^3)], x},
  {Sqrt[x/(125 - x^3)], x},

  (* ============================================================ *)
  (* SECTION 8: Trigonometric (Formulas 273-422)                   *)
  (* ============================================================ *)

  (* Formula 273: Sin[a x] *)
  {Sin[2 x], x},
  {Sin[x], x},
  {Sin[5 x], x},

  (* Formula 274: Cos[a x] *)
  {Cos[3 x], x},
  {Cos[x], x},
  {Cos[7 x], x},

  (* Formula 275: Tan[a x] *)
  {Tan[2 x], x},
  {Tan[x], x},
  {Tan[5 x], x},

  (* Formula 276: Cot[a x] *)
  {Cot[3 x], x},
  {Cot[x], x},
  {Cot[5 x], x},

  (* Formula 277: Sec[a x] *)
  {Sec[2 x], x},
  {Sec[x], x},
  {Sec[5 x], x},

  (* Formula 278: Csc[a x] *)
  {Csc[3 x], x},
  {Csc[x], x},
  {Csc[7 x], x},

  (* Formula 279: Sin[a x]^2 *)
  {Sin[2 x]^2, x},
  {Sin[x]^2, x},
  {Sin[5 x]^2, x},

  (* Formula 280: Sin[a x]^3 *)
  {Sin[2 x]^3, x},
  {Sin[x]^3, x},
  {Sin[3 x]^3, x},

  (* Formula 281: Sin[a x]^4 *)
  {Sin[2 x]^4, x},
  {Sin[x]^4, x},
  {Sin[3 x]^4, x},

  (* Formula 282: Sin[a x]^n reduction *)
  {Sin[2 x]^5, x},
  {Sin[x]^6, x},
  {Sin[3 x]^5, x},

  (* Formula 285: Cos[a x]^2 *)
  {Cos[2 x]^2, x},
  {Cos[x]^2, x},
  {Cos[5 x]^2, x},

  (* Formula 286: Cos[a x]^3 *)
  {Cos[2 x]^3, x},
  {Cos[x]^3, x},
  {Cos[3 x]^3, x},

  (* Formula 287: Cos[a x]^4 *)
  {Cos[2 x]^4, x},
  {Cos[x]^4, x},
  {Cos[3 x]^4, x},

  (* Formula 288: Cos[a x]^n reduction *)
  {Cos[2 x]^5, x},
  {Cos[x]^6, x},
  {Cos[3 x]^5, x},

  (* Formula 291: 1/Sin[a x]^2 *)
  {1/Sin[2 x]^2, x},
  {1/Sin[x]^2, x},
  {1/Sin[5 x]^2, x},

  (* Formula 292: 1/Sin[a x]^m reduction *)
  {1/Sin[2 x]^3, x},
  {1/Sin[x]^4, x},
  {1/Sin[3 x]^3, x},

  (* Formula 295: 1/Cos[a x]^2 *)
  {1/Cos[2 x]^2, x},
  {1/Cos[x]^2, x},
  {1/Cos[5 x]^2, x},

  (* Formula 296: 1/Cos[a x]^m reduction *)
  {1/Cos[2 x]^3, x},
  {1/Cos[x]^4, x},
  {1/Cos[3 x]^3, x},

  (* Formula 299: Sin[m x] Sin[n x] *)
  {Sin[2 x] Sin[3 x], x},
  {Sin[x] Sin[5 x], x},
  {Sin[3 x] Sin[7 x], x},

  (* Formula 300: Cos[m x] Cos[n x] *)
  {Cos[2 x] Cos[3 x], x},
  {Cos[x] Cos[5 x], x},
  {Cos[3 x] Cos[7 x], x},

  (* Formula 301: Sin[a x] Cos[a x] *)
  {Sin[2 x] Cos[2 x], x},
  {Sin[x] Cos[x], x},
  {Sin[5 x] Cos[5 x], x},

  (* Formula 302: Sin[m x] Cos[n x] *)
  {Sin[2 x] Cos[3 x], x},
  {Sin[x] Cos[5 x], x},
  {Sin[3 x] Cos[7 x], x},

  (* Formula 303: Sin[a x]^2 Cos[a x]^2 *)
  {Sin[2 x]^2 Cos[2 x]^2, x},
  {Sin[x]^2 Cos[x]^2, x},
  {Sin[3 x]^2 Cos[3 x]^2, x},

  (* Formula 304: Sin[a x] Cos[a x]^m *)
  {Sin[2 x] Cos[2 x]^3, x},
  {Sin[x] Cos[x]^4, x},
  {Sin[3 x] Cos[3 x]^2, x},

  (* Formula 305: Sin[a x]^m Cos[a x] *)
  {Sin[2 x]^3 Cos[2 x], x},
  {Sin[x]^4 Cos[x], x},
  {Sin[3 x]^2 Cos[3 x], x},

  (* Formula 306: Cos[a x]^m Sin[a x]^n reduction *)
  {Cos[2 x]^3 Sin[2 x]^2, x},
  {Cos[x]^2 Sin[x]^3, x},
  {Cos[3 x]^4 Sin[3 x]^2, x},

  (* Formula 307: Cos[a x]^m / Sin[a x]^n reduction *)
  {Cos[2 x]^3/Sin[2 x]^2, x},
  {Cos[x]^2/Sin[x]^3, x},
  {Cos[3 x]^4/Sin[3 x]^2, x},

  (* Formula 308: Sin[a x]^m / Cos[a x]^n reduction *)
  {Sin[2 x]^3/Cos[2 x]^2, x},
  {Sin[x]^2/Cos[x]^3, x},
  {Sin[3 x]^4/Cos[3 x]^2, x},

  (* Formula 309: Sin[a x]/Cos[a x]^2 *)
  {Sin[2 x]/Cos[2 x]^2, x},
  {Sin[x]/Cos[x]^2, x},
  {Sin[5 x]/Cos[5 x]^2, x},

  (* Formula 310: Sin[a x]^2/Cos[a x] *)
  {Sin[2 x]^2/Cos[2 x], x},
  {Sin[x]^2/Cos[x], x},
  {Sin[5 x]^2/Cos[5 x], x},

  (* Formula 311: Cos[a x]/Sin[a x]^2 *)
  {Cos[2 x]/Sin[2 x]^2, x},
  {Cos[x]/Sin[x]^2, x},
  {Cos[5 x]/Sin[5 x]^2, x},

  (* Formula 312: 1/(Sin[a x] Cos[a x]) *)
  {1/(Sin[2 x] Cos[2 x]), x},
  {1/(Sin[x] Cos[x]), x},
  {1/(Sin[5 x] Cos[5 x]), x},

  (* Formula 313: 1/(Sin[a x] Cos[a x]^2) *)
  {1/(Sin[2 x] Cos[2 x]^2), x},
  {1/(Sin[x] Cos[x]^2), x},
  {1/(Sin[5 x] Cos[5 x]^2), x},

  (* Formula 314: 1/(Sin[a x] Cos[a x]^n) reduction *)
  {1/(Sin[2 x] Cos[2 x]^3), x},
  {1/(Sin[x] Cos[x]^4), x},
  {1/(Sin[3 x] Cos[3 x]^3), x},

  (* Formula 315: 1/(Sin[a x]^2 Cos[a x]) *)
  {1/(Sin[2 x]^2 Cos[2 x]), x},
  {1/(Sin[x]^2 Cos[x]), x},
  {1/(Sin[5 x]^2 Cos[5 x]), x},

  (* Formula 316: 1/(Sin[a x]^2 Cos[a x]^2) *)
  {1/(Sin[2 x]^2 Cos[2 x]^2), x},
  {1/(Sin[x]^2 Cos[x]^2), x},
  {1/(Sin[5 x]^2 Cos[5 x]^2), x},

  (* Formula 317: 1/(Sin[a x]^m Cos[a x]^n) reduction *)
  {1/(Sin[2 x]^3 Cos[2 x]^2), x},
  {1/(Sin[x]^2 Cos[x]^3), x},
  {1/(Sin[3 x]^3 Cos[3 x]^3), x},

  (* Formula 318: Sin[a + b x] *)
  {Sin[2 + 3 x], x},
  {Sin[1 + x], x},
  {Sin[5 + 7 x], x},

  (* Formula 319: Cos[a + b x] *)
  {Cos[2 + 3 x], x},
  {Cos[1 + x], x},
  {Cos[5 + 7 x], x},

  (* Formula 320: 1/(1 +/- Sin[a x]) *)
  {1/(1 + Sin[2 x]), x},
  {1/(1 - Sin[3 x]), x},
  {1/(1 + Sin[x]), x},

  (* Formula 321: 1/(1 + Cos[a x]) *)
  {1/(1 + Cos[2 x]), x},
  {1/(1 + Cos[x]), x},
  {1/(1 + Cos[5 x]), x},

  (* Formula 322: 1/(1 - Cos[a x]) *)
  {1/(1 - Cos[2 x]), x},
  {1/(1 - Cos[x]), x},
  {1/(1 - Cos[5 x]), x},

  (* Formula 323: 1/(a + b Sin[x]), both branches *)
  {1/(5 + 3 Sin[x]), x},
  {1/(2 + 7 Sin[x]), x},
  {1/(3 + 5 Sin[x]), x},

  (* Formula 324: 1/(a + b Cos[x]), both branches *)
  {1/(5 + 3 Cos[x]), x},
  {1/(2 + 7 Cos[x]), x},
  {1/(3 + 5 Cos[x]), x},

  (* Formula 327: 1/(a^2 Cos[x]^2 + b^2 Sin[x]^2) *)
  {1/(4 Cos[x]^2 + 9 Sin[x]^2), x},
  {1/(Cos[x]^2 + 4 Sin[x]^2), x},
  {1/(9 Cos[x]^2 + 25 Sin[x]^2), x},

  (* Formula 329: Sin Cos / (a Cos^2 + b Sin^2) *)
  {(Sin[2 x] Cos[2 x])/(3 Cos[2 x]^2 + 5 Sin[2 x]^2), x},
  {(Sin[x] Cos[x])/(2 Cos[x]^2 + 7 Sin[x]^2), x},
  {(Sin[3 x] Cos[3 x])/(4 Cos[3 x]^2 + 9 Sin[3 x]^2), x},

  (* Formula 330: 1/(a + b Tan[c x]) *)
  {1/(2 + 3 Tan[5 x]), x},
  {1/(1 + Tan[x]), x},
  {1/(3 + 2 Tan[2 x]), x},

  (* Formula 331: 1/(b + a Cot[c x]) *)
  {1/(2 + 3 Cot[5 x]), x},
  {1/(1 + Cot[x]), x},
  {1/(3 + 2 Cot[2 x]), x},

  (* Formula 333: Sin[a x]/(1 +/- Sin[a x]) *)
  {Sin[2 x]/(1 + Sin[2 x]), x},
  {Sin[3 x]/(1 - Sin[3 x]), x},
  {Sin[x]/(1 + Sin[x]), x},

  (* Formula 334: 1/(Sin[a x] (1 +/- Sin[a x])) *)
  {1/(Sin[2 x] (1 + Sin[2 x])), x},
  {1/(Sin[3 x] (1 - Sin[3 x])), x},
  {1/(Sin[x] (1 + Sin[x])), x},

  (* Formula 335 & 336: 1/(1 +/- Sin[a x])^2 *)
  {1/(1 + Sin[2 x])^2, x},
  {1/(1 - Sin[3 x])^2, x},
  {1/(1 + Sin[x])^2, x},

  (* Formula 337 & 338: Sin[a x]/(1 +/- Sin[a x])^2 *)
  {Sin[2 x]/(1 + Sin[2 x])^2, x},
  {Sin[3 x]/(1 - Sin[3 x])^2, x},
  {Sin[x]/(1 + Sin[x])^2, x},

  (* Formula 339: Sin[x]/(a + b Sin[x]) *)
  {Sin[x]/(5 + 3 Sin[x]), x},
  {Sin[x]/(2 + 7 Sin[x]), x},
  {Sin[x]/(3 + 5 Sin[x]), x},

  (* Formula 340: 1/(Sin[x] (a + b Sin[x])) *)
  {1/(Sin[x] (5 + 3 Sin[x])), x},
  {1/(Sin[x] (2 + 7 Sin[x])), x},
  {1/(Sin[x] (3 + 5 Sin[x])), x},

  (* Formula 341: 1/(a + b Sin[x])^2 *)
  {1/(5 + 3 Sin[x])^2, x},
  {1/(2 + 7 Sin[x])^2, x},
  {1/(3 + 5 Sin[x])^2, x},

  (* Formula 342 & 343: 1/(a^2 +/- b^2 Sin[c x]^2) *)
  {1/(4 + 9 Sin[2 x]^2), x},
  {1/(25 - 9 Sin[3 x]^2), x},
  {1/(4 - 25 Sin[2 x]^2), x},

  (* Formula 344 & 345: Cos[a x]/(1 +/- Cos[a x]) *)
  {Cos[2 x]/(1 + Cos[2 x]), x},
  {Cos[3 x]/(1 - Cos[3 x]), x},
  {Cos[x]/(1 + Cos[x]), x},

  (* Formula 346 & 347: 1/(Cos[a x] (1 +/- Cos[a x])) *)
  {1/(Cos[2 x] (1 + Cos[2 x])), x},
  {1/(Cos[3 x] (1 - Cos[3 x])), x},
  {1/(Cos[x] (1 + Cos[x])), x},

  (* Formula 348 & 349: 1/(1 +/- Cos[a x])^2 *)
  {1/(1 + Cos[2 x])^2, x},
  {1/(1 - Cos[3 x])^2, x},
  {1/(1 + Cos[x])^2, x},

  (* Formula 350 & 351: Cos[a x]/(1 +/- Cos[a x])^2 *)
  {Cos[2 x]/(1 + Cos[2 x])^2, x},
  {Cos[3 x]/(1 - Cos[3 x])^2, x},
  {Cos[x]/(1 + Cos[x])^2, x},

  (* Formula 352: Cos[x]/(a + b Cos[x]) *)
  {Cos[x]/(5 + 3 Cos[x]), x},
  {Cos[x]/(2 + 7 Cos[x]), x},
  {Cos[x]/(3 + 5 Cos[x]), x},

  (* Formula 353: 1/(Cos[x] (a + b Cos[x])) *)
  {1/(Cos[x] (5 + 3 Cos[x])), x},
  {1/(Cos[x] (2 + 7 Cos[x])), x},
  {1/(Cos[x] (3 + 5 Cos[x])), x},

  (* Formula 354: 1/(a + b Cos[x])^2 *)
  {1/(5 + 3 Cos[x])^2, x},
  {1/(2 + 7 Cos[x])^2, x},
  {1/(3 + 5 Cos[x])^2, x},

  (* Formula 355: Cos[x]/(a + b Cos[x])^2 *)
  {Cos[x]/(5 + 3 Cos[x])^2, x},
  {Cos[x]/(2 + 7 Cos[x])^2, x},
  {Cos[x]/(3 + 5 Cos[x])^2, x},

  (* Formula 356: 1/(a^2 + b^2 - 2 a b Cos[c x]) *)
  {1/(4 + 9 - 12 Cos[2 x]), x},
  {1/(1 + 4 - 4 Cos[x]), x},
  {1/(9 + 25 - 30 Cos[3 x]), x},

  (* Formula 357 & 358: 1/(a^2 +/- b^2 Cos[c x]^2) *)
  {1/(4 + 9 Cos[2 x]^2), x},
  {1/(25 - 9 Cos[3 x]^2), x},
  {1/(4 - 25 Cos[2 x]^2), x},

  (* Formula 359: Sin[a x]/(1 +/- Cos[a x]) *)
  {Sin[2 x]/(1 + Cos[2 x]), x},
  {Sin[3 x]/(1 - Cos[3 x]), x},
  {Sin[x]/(1 + Cos[x]), x},

  (* Formula 360: Cos[a x]/(1 +/- Sin[a x]) *)
  {Cos[2 x]/(1 + Sin[2 x]), x},
  {Cos[3 x]/(1 - Sin[3 x]), x},
  {Cos[x]/(1 + Sin[x]), x},

  (* Formula 361: 1/(Sin[a x] (1 +/- Cos[a x])) *)
  {1/(Sin[2 x] (1 + Cos[2 x])), x},
  {1/(Sin[3 x] (1 - Cos[3 x])), x},
  {1/(Sin[x] (1 + Cos[x])), x},

  (* Formula 362: 1/(Cos[a x] (1 +/- Sin[a x])) *)
  {1/(Cos[2 x] (1 + Sin[2 x])), x},
  {1/(Cos[3 x] (1 - Sin[3 x])), x},
  {1/(Cos[x] (1 + Sin[x])), x},

  (* Formula 363: Sin[a x]/(Cos[a x] (1 +/- Cos[a x])) *)
  {Sin[2 x]/(Cos[2 x] (1 + Cos[2 x])), x},
  {Sin[3 x]/(Cos[3 x] (1 - Cos[3 x])), x},
  {Sin[x]/(Cos[x] (1 + Cos[x])), x},

  (* Formula 364: Cos[a x]/(Sin[a x] (1 +/- Sin[a x])) *)
  {Cos[2 x]/(Sin[2 x] (1 + Sin[2 x])), x},
  {Cos[3 x]/(Sin[3 x] (1 - Sin[3 x])), x},
  {Cos[x]/(Sin[x] (1 + Sin[x])), x},

  (* Formula 365: Sin[a x]/(Cos[a x] (1 +/- Sin[a x])) *)
  {Sin[2 x]/(Cos[2 x] (1 + Sin[2 x])), x},
  {Sin[3 x]/(Cos[3 x] (1 - Sin[3 x])), x},
  {Sin[x]/(Cos[x] (1 + Sin[x])), x},

  (* Formula 366: Cos[a x]/(Sin[a x] (1 +/- Cos[a x])) *)
  {Cos[2 x]/(Sin[2 x] (1 + Cos[2 x])), x},
  {Cos[3 x]/(Sin[3 x] (1 - Cos[3 x])), x},
  {Cos[x]/(Sin[x] (1 + Cos[x])), x},

  (* Formula 367: 1/(Sin[a x] +/- Cos[a x]) *)
  {1/(Sin[2 x] + Cos[2 x]), x},
  {1/(Sin[3 x] - Cos[3 x]), x},
  {1/(Sin[x] + Cos[x]), x},

  (* Formula 368: 1/(Sin[a x] +/- Cos[a x])^2 *)
  {1/(Sin[2 x] + Cos[2 x])^2, x},
  {1/(Sin[3 x] - Cos[3 x])^2, x},
  {1/(Sin[x] + Cos[x])^2, x},

  (* Formula 369: 1/(1 + Cos[a x] +/- Sin[a x]) *)
  {1/(1 + Cos[2 x] + Sin[2 x]), x},
  {1/(1 + Cos[3 x] - Sin[3 x]), x},
  {1/(1 + Cos[x] + Sin[x]), x},

  (* Formula 370: 1/(a^2 Cos[c x]^2 - b^2 Sin[c x]^2) *)
  {1/(4 Cos[2 x]^2 - 9 Sin[2 x]^2), x},
  {1/(Cos[x]^2 - 4 Sin[x]^2), x},
  {1/(9 Cos[3 x]^2 - 25 Sin[3 x]^2), x},

  (* Formula 371: x Sin[a x] *)
  {x Sin[2 x], x},
  {x Sin[x], x},
  {x Sin[5 x], x},

  (* Formula 372: x^2 Sin[a x] *)
  {x^2 Sin[2 x], x},
  {x^2 Sin[x], x},
  {x^2 Sin[5 x], x},

  (* Formula 373: x^3 Sin[a x] *)
  {x^3 Sin[2 x], x},
  {x^3 Sin[x], x},
  {x^3 Sin[3 x], x},

  (* Formula 374: x^m Sin[a x] reduction *)
  {x^4 Sin[2 x], x},
  {x^5 Sin[x], x},
  {x^4 Sin[3 x], x},

  (* Formula 375: x Cos[a x] *)
  {x Cos[2 x], x},
  {x Cos[x], x},
  {x Cos[5 x], x},

  (* Formula 376: x^2 Cos[a x] *)
  {x^2 Cos[2 x], x},
  {x^2 Cos[x], x},
  {x^2 Cos[5 x], x},

  (* Formula 377: x^3 Cos[a x] *)
  {x^3 Cos[2 x], x},
  {x^3 Cos[x], x},
  {x^3 Cos[3 x], x},

  (* Formula 378: x^m Cos[a x] reduction *)
  {x^4 Cos[2 x], x},
  {x^5 Cos[x], x},
  {x^4 Cos[3 x], x},

  (* Formula 381: x Sin[a x]^2 *)
  {x Sin[2 x]^2, x},
  {x Sin[x]^2, x},
  {x Sin[3 x]^2, x},

  (* Formula 382: x^2 Sin[a x]^2 *)
  {x^2 Sin[2 x]^2, x},
  {x^2 Sin[x]^2, x},
  {x^2 Sin[3 x]^2, x},

  (* Formula 383: x Sin[a x]^3 *)
  {x Sin[2 x]^3, x},
  {x Sin[x]^3, x},
  {x Sin[3 x]^3, x},

  (* Formula 384: x Cos[a x]^2 *)
  {x Cos[2 x]^2, x},
  {x Cos[x]^2, x},
  {x Cos[3 x]^2, x},

  (* Formula 385: x^2 Cos[a x]^2 *)
  {x^2 Cos[2 x]^2, x},
  {x^2 Cos[x]^2, x},
  {x^2 Cos[3 x]^2, x},

  (* Formula 386: x Cos[a x]^3 *)
  {x Cos[2 x]^3, x},
  {x Cos[x]^3, x},
  {x Cos[3 x]^3, x},

  (* Formula 387: Sin[a x]/x^m reduction *)
  {Sin[2 x]/x^2, x},
  {Sin[x]/x^3, x},
  {Sin[3 x]/x^2, x},

  (* Formula 388: Cos[a x]/x^m reduction *)
  {Cos[2 x]/x^2, x},
  {Cos[x]/x^3, x},
  {Cos[3 x]/x^2, x},

  (* Formula 389: x/(1 +/- Sin[a x]) -- both branches *)
  {x/(1 + Sin[2 x]), x},
  {x/(1 - Sin[2 x]), x},
  {x/(1 + Sin[x]), x},

  (* Formula 390: x/(1 + Cos[a x]) *)
  {x/(1 + Cos[2 x]), x},
  {x/(1 + Cos[x]), x},
  {x/(1 + Cos[3 x]), x},

  (* Formula 391: x/(1 - Cos[a x]) *)
  {x/(1 - Cos[2 x]), x},
  {x/(1 - Cos[x]), x},
  {x/(1 - Cos[3 x]), x},

  (* Formula 392: (x + Sin[x])/(1 + Cos[x]) *)
  {(x + Sin[x])/(1 + Cos[x]), x},

  (* Formula 393: (x - Sin[x])/(1 - Cos[x]) *)
  {(x - Sin[x])/(1 - Cos[x]), x},

  (* Formula 394: Sqrt[1 - Cos[a x]] *)
  {Sqrt[1 - Cos[2 x]], x},
  {Sqrt[1 - Cos[x]], x},
  {Sqrt[1 - Cos[3 x]], x},

  (* Formula 395: Sqrt[1 + Cos[a x]] *)
  {Sqrt[1 + Cos[2 x]], x},
  {Sqrt[1 + Cos[x]], x},
  {Sqrt[1 + Cos[3 x]], x},

  (* Formula 396: Sqrt[1 + Sin[x]] *)
  {Sqrt[1 + Sin[x]], x},

  (* Formula 397: Sqrt[1 - Sin[x]] *)
  {Sqrt[1 - Sin[x]], x},

  (* Formula 398: 1/Sqrt[1 - Cos[x]] *)
  {1/Sqrt[1 - Cos[x]], x},

  (* Formula 399: 1/Sqrt[1 + Cos[x]] *)
  {1/Sqrt[1 + Cos[x]], x},

  (* Formula 400: 1/Sqrt[1 - Sin[x]] *)
  {1/Sqrt[1 - Sin[x]], x},

  (* Formula 401: 1/Sqrt[1 + Sin[x]] *)
  {1/Sqrt[1 + Sin[x]], x},

  (* Formula 402: Tan[a x]^2 *)
  {Tan[2 x]^2, x},
  {Tan[x]^2, x},
  {Tan[3 x]^2, x},

  (* Formula 403: Tan[a x]^3 *)
  {Tan[2 x]^3, x},
  {Tan[x]^3, x},
  {Tan[3 x]^3, x},

  (* Formula 404: Tan[a x]^4 *)
  {Tan[2 x]^4, x},
  {Tan[x]^4, x},
  {Tan[3 x]^4, x},

  (* Formula 405: Tan[a x]^n reduction *)
  {Tan[2 x]^5, x},
  {Tan[x]^6, x},
  {Tan[3 x]^5, x},

  (* Formula 406: Cot[a x]^2 *)
  {Cot[2 x]^2, x},
  {Cot[x]^2, x},
  {Cot[3 x]^2, x},

  (* Formula 407: Cot[a x]^3 *)
  {Cot[2 x]^3, x},
  {Cot[x]^3, x},
  {Cot[3 x]^3, x},

  (* Formula 408: Cot[a x]^4 *)
  {Cot[2 x]^4, x},
  {Cot[x]^4, x},
  {Cot[3 x]^4, x},

  (* Formula 409: Cot[a x]^n reduction *)
  {Cot[2 x]^5, x},
  {Cot[x]^6, x},
  {Cot[3 x]^5, x},

  (* Formula 410: x/Sin[a x]^2 *)
  {x/Sin[2 x]^2, x},
  {x/Sin[x]^2, x},
  {x/Sin[3 x]^2, x},

  (* Formula 411: x/Sin[a x]^n reduction *)
  {x/Sin[2 x]^3, x},
  {x/Sin[x]^4, x},
  {x/Sin[3 x]^3, x},

  (* Formula 412: x/Cos[a x]^2 *)
  {x/Cos[2 x]^2, x},
  {x/Cos[x]^2, x},
  {x/Cos[3 x]^2, x},

  (* Formula 413: x/Cos[a x]^n reduction *)
  {x/Cos[2 x]^3, x},
  {x/Cos[x]^4, x},
  {x/Cos[3 x]^3, x},

  (* Formula 414: Sin[a x]/Sqrt[1 + b^2 Sin[a x]^2] *)
  {Sin[2 x]/Sqrt[1 + 9 Sin[2 x]^2], x},
  {Sin[x]/Sqrt[1 + 4 Sin[x]^2], x},
  {Sin[3 x]/Sqrt[1 + 4 Sin[3 x]^2], x},

  (* Formula 415: Sin[a x]/Sqrt[1 - b^2 Sin[a x]^2] *)
  {Sin[2 x]/Sqrt[1 - 9 Sin[2 x]^2], x},
  {Sin[x]/Sqrt[1 - 4 Sin[x]^2], x},
  {Sin[3 x]/Sqrt[1 - 4 Sin[3 x]^2], x},

  (* Formula 416: Sin[a x] Sqrt[1 + b^2 Sin[a x]^2] *)
  {Sin[2 x] Sqrt[1 + 9 Sin[2 x]^2], x},
  {Sin[x] Sqrt[1 + 4 Sin[x]^2], x},
  {Sin[3 x] Sqrt[1 + 4 Sin[3 x]^2], x},

  (* Formula 417: Sin[a x] Sqrt[1 - b^2 Sin[a x]^2] *)
  {Sin[2 x] Sqrt[1 - 9 Sin[2 x]^2], x},
  {Sin[x] Sqrt[1 - 4 Sin[x]^2], x},
  {Sin[3 x] Sqrt[1 - 4 Sin[3 x]^2], x},

  (* Formula 418: Cos[a x]/Sqrt[1 + b^2 Sin[a x]^2] *)
  {Cos[2 x]/Sqrt[1 + 9 Sin[2 x]^2], x},
  {Cos[x]/Sqrt[1 + 4 Sin[x]^2], x},
  {Cos[3 x]/Sqrt[1 + 4 Sin[3 x]^2], x},

  (* Formula 419: Cos[a x]/Sqrt[1 - b^2 Sin[a x]^2] *)
  {Cos[2 x]/Sqrt[1 - 9 Sin[2 x]^2], x},
  {Cos[x]/Sqrt[1 - 4 Sin[x]^2], x},
  {Cos[3 x]/Sqrt[1 - 4 Sin[3 x]^2], x},

  (* Formula 420: Cos[a x] Sqrt[1 + b^2 Sin[a x]^2] *)
  {Cos[2 x] Sqrt[1 + 9 Sin[2 x]^2], x},
  {Cos[x] Sqrt[1 + 4 Sin[x]^2], x},
  {Cos[3 x] Sqrt[1 + 4 Sin[3 x]^2], x},

  (* Formula 421: Cos[a x] Sqrt[1 - b^2 Sin[a x]^2] *)
  {Cos[2 x] Sqrt[1 - 9 Sin[2 x]^2], x},
  {Cos[x] Sqrt[1 - 4 Sin[x]^2], x},
  {Cos[3 x] Sqrt[1 - 4 Sin[3 x]^2], x},

  (* Formula 422: 1/Sqrt[a + b Tan[c x]^2] with a > |b| *)
  {1/Sqrt[5 + 3 Tan[2 x]^2], x},
  {1/Sqrt[4 + Tan[x]^2], x},
  {1/Sqrt[5 + 2 Tan[3 x]^2], x},

  (* ============================================================ *)
  (* SECTION 9: Inverse Trigonometric (Formulas 427-464)            *)
  (* ============================================================ *)

  (* Formula 427: ArcSin[a x] *)
  {ArcSin[2 x], x},
  {ArcSin[x], x},
  {ArcSin[3 x], x},

  (* Formula 428: ArcCos[a x] *)
  {ArcCos[2 x], x},
  {ArcCos[x], x},
  {ArcCos[3 x], x},

  (* Formula 429: ArcTan[a x] *)
  {ArcTan[2 x], x},
  {ArcTan[x], x},
  {ArcTan[3 x], x},

  (* Formula 430: ArcCot[a x] *)
  {ArcCot[2 x], x},
  {ArcCot[x], x},
  {ArcCot[3 x], x},

  (* Formula 431: ArcSec[a x] *)
  {ArcSec[2 x], x},
  {ArcSec[x], x},
  {ArcSec[3 x], x},

  (* Formula 432: ArcCsc[a x] *)
  {ArcCsc[2 x], x},
  {ArcCsc[x], x},
  {ArcCsc[3 x], x},

  (* Formula 437: x ArcSin[a x] *)
  {x ArcSin[2 x], x},
  {x ArcSin[x], x},
  {x ArcSin[3 x], x},

  (* Formula 438: x ArcCos[a x] *)
  {x ArcCos[2 x], x},
  {x ArcCos[x], x},
  {x ArcCos[3 x], x},

  (* Formula 439: x^n ArcSin[a x] *)
  {x^2 ArcSin[2 x], x},
  {x^3 ArcSin[x], x},
  {x^2 ArcSin[3 x], x},

  (* Formula 440: x^n ArcCos[a x] *)
  {x^2 ArcCos[2 x], x},
  {x^3 ArcCos[x], x},
  {x^2 ArcCos[3 x], x},

  (* Formula 441: x ArcTan[a x] *)
  {x ArcTan[2 x], x},
  {x ArcTan[x], x},
  {x ArcTan[3 x], x},

  (* Formula 442: x^n ArcTan[a x] *)
  {x^2 ArcTan[2 x], x},
  {x^3 ArcTan[x], x},
  {x^2 ArcTan[3 x], x},

  (* Formula 443: x ArcCot[a x] *)
  {x ArcCot[2 x], x},
  {x ArcCot[x], x},
  {x ArcCot[3 x], x},

  (* Formula 444: x^n ArcCot[a x] *)
  {x^2 ArcCot[2 x], x},
  {x^3 ArcCot[x], x},
  {x^2 ArcCot[3 x], x},

  (* Formula 445: ArcSin[a x]/x^2 *)
  {ArcSin[2 x]/x^2, x},
  {ArcSin[x]/x^2, x},
  {ArcSin[3 x]/x^2, x},

  (* Formula 446: ArcCos[a x]/x^2 *)
  {ArcCos[2 x]/x^2, x},
  {ArcCos[x]/x^2, x},
  {ArcCos[3 x]/x^2, x},

  (* Formula 447: ArcTan[a x]/x^2 *)
  {ArcTan[2 x]/x^2, x},
  {ArcTan[x]/x^2, x},
  {ArcTan[3 x]/x^2, x},

  (* Formula 448: ArcCot[a x]/x^2 *)
  {ArcCot[2 x]/x^2, x},
  {ArcCot[x]/x^2, x},
  {ArcCot[3 x]/x^2, x},

  (* Formula 449: ArcSin[a x]^2 *)
  {ArcSin[2 x]^2, x},
  {ArcSin[x]^2, x},
  {ArcSin[3 x]^2, x},

  (* Formula 450: ArcCos[a x]^2 *)
  {ArcCos[2 x]^2, x},
  {ArcCos[x]^2, x},
  {ArcCos[3 x]^2, x},

  (* Formula 453: ArcSin[a x]/Sqrt[1 - a^2 x^2] *)
  {ArcSin[2 x]/Sqrt[1 - 4 x^2], x},
  {ArcSin[x]/Sqrt[1 - x^2], x},
  {ArcSin[3 x]/Sqrt[1 - 9 x^2], x},

  (* Formula 454: x^n ArcSin[a x]/Sqrt[1 - a^2 x^2] *)
  {x^2 ArcSin[2 x]/Sqrt[1 - 4 x^2], x},
  {x^3 ArcSin[x]/Sqrt[1 - x^2], x},
  {x^2 ArcSin[3 x]/Sqrt[1 - 9 x^2], x},

  (* Formula 455: ArcCos[a x]/Sqrt[1 - a^2 x^2] *)
  {ArcCos[2 x]/Sqrt[1 - 4 x^2], x},
  {ArcCos[x]/Sqrt[1 - x^2], x},
  {ArcCos[3 x]/Sqrt[1 - 9 x^2], x},

  (* Formula 456: x^n ArcCos[a x]/Sqrt[1 - a^2 x^2] *)
  {x^2 ArcCos[2 x]/Sqrt[1 - 4 x^2], x},
  {x^3 ArcCos[x]/Sqrt[1 - x^2], x},
  {x^2 ArcCos[3 x]/Sqrt[1 - 9 x^2], x},

  (* Formula 457: ArcTan[a x]/(1 + a^2 x^2) *)
  {ArcTan[2 x]/(1 + 4 x^2), x},
  {ArcTan[x]/(1 + x^2), x},
  {ArcTan[3 x]/(1 + 9 x^2), x},

  (* Formula 458: ArcCot[a x]/(1 + a^2 x^2) *)
  {ArcCot[2 x]/(1 + 4 x^2), x},
  {ArcCot[x]/(1 + x^2), x},
  {ArcCot[3 x]/(1 + 9 x^2), x},

  (* Formula 459: x ArcSec[a x] *)
  {x ArcSec[2 x], x},
  {x ArcSec[x], x},
  {x ArcSec[3 x], x},

  (* Formula 460: x^n ArcSec[a x] *)
  {x^2 ArcSec[2 x], x},
  {x^3 ArcSec[x], x},
  {x^2 ArcSec[3 x], x},

  (* Formula 461: ArcSec[a x]/x^2 *)
  {ArcSec[2 x]/x^2, x},
  {ArcSec[x]/x^2, x},
  {ArcSec[3 x]/x^2, x},

  (* Formula 462: x ArcCsc[a x] *)
  {x ArcCsc[2 x], x},
  {x ArcCsc[x], x},
  {x ArcCsc[3 x], x},

  (* Formula 463: x^n ArcCsc[a x] *)
  {x^2 ArcCsc[2 x], x},
  {x^3 ArcCsc[x], x},
  {x^2 ArcCsc[3 x], x},

  (* Formula 464: ArcCsc[a x]/x^2 *)
  {ArcCsc[2 x]/x^2, x},
  {ArcCsc[x]/x^2, x},
  {ArcCsc[3 x]/x^2, x},

  (* ============================================================ *)
  (* SECTION 9h: Inverse hyperbolic functions (Formulas 427h-464h) *)
  (* Analogs of the inverse-trig block above.                      *)
  (* ============================================================ *)

  (* Formula 427h: ArcSinh[a x] *)
  {ArcSinh[2 x], x},
  {ArcSinh[x], x},
  {ArcSinh[3 x], x},

  (* Formula 428h: ArcCosh[a x] *)
  {ArcCosh[2 x], x},
  {ArcCosh[x], x},
  {ArcCosh[3 x], x},

  (* Formula 429h: ArcTanh[a x] *)
  {ArcTanh[2 x], x},
  {ArcTanh[x], x},
  {ArcTanh[3 x], x},

  (* Formula 430h: ArcCoth[a x] *)
  {ArcCoth[2 x], x},
  {ArcCoth[x], x},
  {ArcCoth[3 x], x},

  (* Formula 431h: ArcSech[a x] *)
  {ArcSech[2 x], x},
  {ArcSech[x], x},
  {ArcSech[3 x], x},

  (* Formula 432h: ArcCsch[a x] *)
  {ArcCsch[2 x], x},
  {ArcCsch[x], x},
  {ArcCsch[3 x], x},

  (* Formula 437h: x ArcSinh[a x] *)
  {x ArcSinh[2 x], x},
  {x ArcSinh[x], x},
  {x ArcSinh[3 x], x},

  (* Formula 438h: x ArcCosh[a x] *)
  {x ArcCosh[2 x], x},
  {x ArcCosh[x], x},
  {x ArcCosh[3 x], x},

  (* Formula 439h: x^n ArcSinh[a x] *)
  {x^2 ArcSinh[2 x], x},
  {x^3 ArcSinh[x], x},
  {x^2 ArcSinh[3 x], x},

  (* Formula 440h: x^n ArcCosh[a x] *)
  {x^2 ArcCosh[2 x], x},
  {x^3 ArcCosh[x], x},
  {x^2 ArcCosh[3 x], x},

  (* Formula 441h: x ArcTanh[a x] *)
  {x ArcTanh[2 x], x},
  {x ArcTanh[x], x},
  {x ArcTanh[3 x], x},

  (* Formula 442h: x^n ArcTanh[a x] *)
  {x^2 ArcTanh[2 x], x},
  {x^3 ArcTanh[x], x},
  {x^2 ArcTanh[3 x], x},

  (* Formula 443h: x ArcCoth[a x] *)
  {x ArcCoth[2 x], x},
  {x ArcCoth[x], x},
  {x ArcCoth[3 x], x},

  (* Formula 444h: x^n ArcCoth[a x] *)
  {x^2 ArcCoth[2 x], x},
  {x^3 ArcCoth[x], x},
  {x^2 ArcCoth[3 x], x},

  (* Formula 445h: ArcSinh[a x]/x^2 *)
  {ArcSinh[2 x]/x^2, x},
  {ArcSinh[x]/x^2, x},
  {ArcSinh[3 x]/x^2, x},

  (* Formula 446h: ArcCosh[a x]/x^2 *)
  {ArcCosh[2 x]/x^2, x},
  {ArcCosh[x]/x^2, x},
  {ArcCosh[3 x]/x^2, x},

  (* Formula 447h: ArcTanh[a x]/x^2 *)
  {ArcTanh[2 x]/x^2, x},
  {ArcTanh[x]/x^2, x},
  {ArcTanh[3 x]/x^2, x},

  (* Formula 448h: ArcCoth[a x]/x^2 *)
  {ArcCoth[2 x]/x^2, x},
  {ArcCoth[x]/x^2, x},
  {ArcCoth[3 x]/x^2, x},

  (* Formula 449h: ArcSinh[a x]^2 *)
  {ArcSinh[2 x]^2, x},
  {ArcSinh[x]^2, x},
  {ArcSinh[3 x]^2, x},

  (* Formula 450h: ArcCosh[a x]^2 *)
  {ArcCosh[2 x]^2, x},
  {ArcCosh[x]^2, x},
  {ArcCosh[3 x]^2, x},

  (* Formula 453h: ArcSinh[a x]/Sqrt[1 + a^2 x^2] *)
  {ArcSinh[2 x]/Sqrt[1 + 4 x^2], x},
  {ArcSinh[x]/Sqrt[1 + x^2], x},
  {ArcSinh[3 x]/Sqrt[1 + 9 x^2], x},

  (* Formula 454h: x^n ArcSinh[a x]/Sqrt[1 + a^2 x^2] *)
  {x^2 ArcSinh[2 x]/Sqrt[1 + 4 x^2], x},
  {x^3 ArcSinh[x]/Sqrt[1 + x^2], x},
  {x^2 ArcSinh[3 x]/Sqrt[1 + 9 x^2], x},

  (* Formula 455h: ArcCosh[a x]/Sqrt[a^2 x^2 - 1] *)
  {ArcCosh[2 x]/Sqrt[4 x^2 - 1], x},
  {ArcCosh[x]/Sqrt[x^2 - 1], x},
  {ArcCosh[3 x]/Sqrt[9 x^2 - 1], x},

  (* Formula 456h: x^n ArcCosh[a x]/Sqrt[a^2 x^2 - 1] *)
  {x^2 ArcCosh[2 x]/Sqrt[4 x^2 - 1], x},
  {x^3 ArcCosh[x]/Sqrt[x^2 - 1], x},
  {x^2 ArcCosh[3 x]/Sqrt[9 x^2 - 1], x},

  (* Formula 457h: ArcTanh[a x]/(1 - a^2 x^2) *)
  {ArcTanh[2 x]/(1 - 4 x^2), x},
  {ArcTanh[x]/(1 - x^2), x},
  {ArcTanh[3 x]/(1 - 9 x^2), x},

  (* Formula 458h: ArcCoth[a x]/(1 - a^2 x^2) *)
  {ArcCoth[2 x]/(1 - 4 x^2), x},
  {ArcCoth[x]/(1 - x^2), x},
  {ArcCoth[3 x]/(1 - 9 x^2), x},

  (* Formula 459h: x ArcSech[a x] *)
  {x ArcSech[2 x], x},
  {x ArcSech[x], x},
  {x ArcSech[3 x], x},

  (* Formula 460h: x^n ArcSech[a x] *)
  {x^2 ArcSech[2 x], x},
  {x^3 ArcSech[x], x},
  {x^2 ArcSech[3 x], x},

  (* Formula 461h: ArcSech[a x]/x^2 *)
  {ArcSech[2 x]/x^2, x},
  {ArcSech[x]/x^2, x},
  {ArcSech[3 x]/x^2, x},

  (* Formula 462h: x ArcCsch[a x] *)
  {x ArcCsch[2 x], x},
  {x ArcCsch[x], x},
  {x ArcCsch[3 x], x},

  (* Formula 463h: x^n ArcCsch[a x] *)
  {x^2 ArcCsch[2 x], x},
  {x^3 ArcCsch[x], x},
  {x^2 ArcCsch[3 x], x},

  (* Formula 464h: ArcCsch[a x]/x^2 *)
  {ArcCsch[2 x]/x^2, x},
  {ArcCsch[x]/x^2, x},
  {ArcCsch[3 x]/x^2, x},

  (* ============================================================ *)
  (* SECTION 10: Logarithms (Formulas 465-495)                     *)
  (* ============================================================ *)

  (* Formula 465: Log[x] *)
  {Log[x], x},

  (* Formula 466: x Log[x] *)
  {x Log[x], x},

  (* Formula 467: x^2 Log[x] *)
  {x^2 Log[x], x},

  (* Formula 468: x^n Log[x] generic *)
  {x^4 Log[x], x},
  {x^7 Log[x], x},
  {x^6 Log[x], x},

  (* Formula 469: Log[x]^2 *)
  {Log[x]^2, x},

  (* Formula 471: Log[x]^n / x *)
  {Log[x]^2/x, x},
  {Log[x]^3/x, x},
  {Log[x]^5/x, x},

  (* Formula 473: 1/(x Log[x]) *)
  {1/(x Log[x]), x},

  (* Formula 474: 1/(x Log[x]^n) *)
  {1/(x Log[x]^2), x},
  {1/(x Log[x]^3), x},
  {1/(x Log[x]^4), x},

  (* Formula 475: x^m / Log[x]^n recursive *)
  {x^2/Log[x]^2, x},
  {x^3/Log[x]^2, x},
  {x^4/Log[x]^3, x},

  (* Formula 476: x^m Log[x]^n recursive *)
  {x^2 Log[x]^2, x},
  {x^3 Log[x]^2, x},
  {x^2 Log[x]^3, x},

  (* Formula 477: x^p Cos[b Log[x]] *)
  {x^2 Cos[3 Log[x]], x},
  {x^3 Cos[Log[x]], x},
  {x^4 Cos[2 Log[x]], x},

  (* Formula 478: x^p Sin[b Log[x]] *)
  {x^2 Sin[3 Log[x]], x},
  {x^3 Sin[Log[x]], x},
  {x^4 Sin[2 Log[x]], x},

  (* Formula 479: Log[a x + b] *)
  {Log[2 x + 3], x},
  {Log[5 x + 7], x},
  {Log[x + 4], x},

  (* Formula 480: Log[a x + b]/x^2 *)
  {Log[2 x + 3]/x^2, x},
  {Log[5 x + 7]/x^2, x},
  {Log[x + 4]/x^2, x},

  (* Formula 483: Log[(x+a)/(x-a)] *)
  {Log[(x + 2)/(x - 2)], x},
  {Log[(x + 5)/(x - 5)], x},
  {Log[(x + 3)/(x - 3)], x},

  (* Formula 485: 1/x^2 Log[(x+a)/(x-a)] *)
  {Log[(x + 2)/(x - 2)]/x^2, x},
  {Log[(x + 5)/(x - 5)]/x^2, x},
  {Log[(x + 3)/(x - 3)]/x^2, x},

  (* Formula 486a: Log[a + b x + c x^2], 4ac - b^2 > 0 *)
  {Log[5 + 2 x + 3 x^2], x},
  {Log[7 + 2 x + 2 x^2], x},
  {Log[10 + 4 x + 3 x^2], x},

  (* Formula 486b: Log[a + b x + c x^2], b^2 - 4ac > 0 *)
  {Log[2 + 5 x + 3 x^2], x},
  {Log[1 + 6 x + 2 x^2], x},
  {Log[3 + 7 x + 2 x^2], x},

  (* Formula 487: x^n Log[a + b x + c x^2] recursive *)
  {x Log[2 + 3 x + 5 x^2], x},
  {x^2 Log[1 + 2 x + 3 x^2], x},
  {x Log[5 + x + 2 x^2], x},

  (* Formula 488: Log[x^2 + a^2] *)
  {Log[x^2 + 4], x},
  {Log[x^2 + 9], x},
  {Log[x^2 + 25], x},

  (* Formula 489: Log[x^2 - a^2] *)
  {Log[x^2 - 4], x},
  {Log[x^2 - 9], x},
  {Log[x^2 - 25], x},

  (* Formula 490: x Log[x^2 + a^2] *)
  {x Log[x^2 + 4], x},
  {x Log[x^2 + 9], x},
  {x Log[x^2 + 16], x},

  (* Formula 491a: Log[x + Sqrt[x^2 + a^2]] *)
  {Log[x + Sqrt[x^2 + 4]], x},
  {Log[x + Sqrt[x^2 + 9]], x},
  {Log[x + Sqrt[x^2 + 25]], x},

  (* Formula 491b: Log[x + Sqrt[x^2 - a^2]] *)
  {Log[x + Sqrt[x^2 - 4]], x},
  {Log[x + Sqrt[x^2 - 9]], x},
  {Log[x + Sqrt[x^2 - 25]], x},

  (* Formula 492a: x Log[x + Sqrt[x^2 + a^2]] *)
  {x Log[x + Sqrt[x^2 + 4]], x},
  {x Log[x + Sqrt[x^2 + 9]], x},
  {x Log[x + Sqrt[x^2 + 16]], x},

  (* Formula 492b: x Log[x + Sqrt[x^2 - a^2]] *)
  {x Log[x + Sqrt[x^2 - 4]], x},
  {x Log[x + Sqrt[x^2 - 9]], x},
  {x Log[x + Sqrt[x^2 - 16]], x},

  (* Formula 493a: x^m Log[x + Sqrt[x^2 + a^2]] recursive *)
  {x^2 Log[x + Sqrt[x^2 + 4]], x},
  {x^3 Log[x + Sqrt[x^2 + 9]], x},
  {x^2 Log[x + Sqrt[x^2 + 25]], x},

  (* Formula 493b: x^m Log[x + Sqrt[x^2 - a^2]] recursive *)
  {x^2 Log[x + Sqrt[x^2 - 4]], x},
  {x^3 Log[x + Sqrt[x^2 - 9]], x},
  {x^2 Log[x + Sqrt[x^2 - 25]], x},

  (* Formula 494: Log[x + Sqrt[x^2 + a^2]]/x^2 *)
  {Log[x + Sqrt[x^2 + 4]]/x^2, x},
  {Log[x + Sqrt[x^2 + 9]]/x^2, x},
  {Log[x + Sqrt[x^2 + 16]]/x^2, x},

  (* Formula 495: Log[x + Sqrt[x^2 - a^2]]/x^2 *)
  {Log[x + Sqrt[x^2 - 4]]/x^2, x},
  {Log[x + Sqrt[x^2 - 1]]/x^2, x},
  {Log[x + Sqrt[x^2 - 4]]/x^2, x},

  (* ============================================================ *)
  (* SECTION 11: Exponential (Formulas 497-527)                    *)
  (* ============================================================ *)

  (* Formula 497: E^x *)
  {E^x, x},

  (* Formula 498: E^(-x) *)
  {E^(-x), x},

  (* Formula 499: E^(a x) *)
  {E^(2 x), x},
  {E^(3 x), x},
  {E^(5 x), x},

  (* Formula 500: x E^(a x) *)
  {x E^(2 x), x},
  {x E^(3 x), x},
  {x E^x, x},

  (* Formula 501: x^m E^(a x) recursive *)
  {x^2 E^(2 x), x},
  {x^3 E^(3 x), x},
  {x^2 E^x, x},

  (* Formula 503: E^(a x)/x^m *)
  {E^(2 x)/x^2, x},
  {E^(3 x)/x^3, x},
  {E^x/x^2, x},

  (* Formula 504: E^(a x) Log[x] *)
  {E^(2 x) Log[x], x},
  {E^(3 x) Log[x], x},
  {E^x Log[x], x},

  (* Formula 505: 1/(1 + E^x) *)
  {1/(1 + E^x), x},

  (* Formula 506: 1/(a + b E^(p x)) *)
  {1/(2 + 3 E^(5 x)), x},
  {1/(3 + 2 E^x), x},
  {1/(5 + 7 E^(2 x)), x},

  (* Formula 507: 1/(a E^(m x) + b E^(-m x)) *)
  {1/(2 E^(3 x) + 5 E^(-3 x)), x},
  {1/(3 E^(2 x) + 7 E^(-2 x)), x},
  {1/(E^x + 2 E^(-x)), x},

  (* Formula 508: 1/(a E^(m x) - b E^(-m x)) *)
  {1/(2 E^(3 x) - 5 E^(-3 x)), x},
  {1/(3 E^(2 x) - 7 E^(-2 x)), x},
  {1/(E^x - 2 E^(-x)), x},

  (* Formula 509: a^x - a^(-x) *)
  {2^x - 2^(-x), x},
  {3^x - 3^(-x), x},
  {5^x - 5^(-x), x},

  (* Formula 510: E^(a x)/(b + c E^(a x)) *)
  {E^(2 x)/(3 + 5 E^(2 x)), x},
  {E^(3 x)/(2 + 7 E^(3 x)), x},
  {E^x/(1 + 2 E^x), x},

  (* Formula 511: x E^(a x)/(1 + a x)^2 *)
  {x E^(2 x)/(1 + 2 x)^2, x},
  {x E^(3 x)/(1 + 3 x)^2, x},
  {x E^x/(1 + x)^2, x},

  (* Formula 512: x E^(-x^2) *)
  {x E^(-x^2), x},

  (* Formula 513: E^(a x) Sin[b x] *)
  {E^(2 x) Sin[3 x], x},
  {E^(3 x) Sin[5 x], x},
  {E^x Sin[2 x], x},

  (* Formula 514: E^(a x) Sin[b x] Sin[c x] *)
  {E^(2 x) Sin[3 x] Sin[5 x], x},
  {E^x Sin[2 x] Sin[3 x], x},
  {E^(3 x) Sin[x] Sin[2 x], x},

  (* Formula 515: E^(a x) Sin[b x] Cos[c x] *)
  {E^(2 x) Sin[3 x] Cos[5 x], x},
  {E^x Sin[2 x] Cos[3 x], x},
  {E^(3 x) Sin[x] Cos[2 x], x},

  (* Formula 516: E^(a x) Sin[b x] Sin[b x + c] *)
  {E^(2 x) Sin[3 x] Sin[3 x + 5], x},
  {E^x Sin[2 x] Sin[2 x + 3], x},
  {E^(3 x) Sin[x] Sin[x + 2], x},

  (* Formula 517: E^(a x) Sin[b x] Cos[b x + c] *)
  {E^(2 x) Sin[3 x] Cos[3 x + 5], x},
  {E^x Sin[2 x] Cos[2 x + 3], x},
  {E^(3 x) Sin[x] Cos[x + 2], x},

  (* Formula 518: E^(a x) Cos[b x] *)
  {E^(2 x) Cos[3 x], x},
  {E^(3 x) Cos[5 x], x},
  {E^x Cos[2 x], x},

  (* Formula 519: E^(a x) Cos[b x] Cos[c x] *)
  {E^(2 x) Cos[3 x] Cos[5 x], x},
  {E^x Cos[2 x] Cos[3 x], x},
  {E^(3 x) Cos[x] Cos[2 x], x},

  (* Formula 520: E^(a x) Cos[b x] Cos[b x + c] *)
  {E^(2 x) Cos[3 x] Cos[3 x + 5], x},
  {E^x Cos[2 x] Cos[2 x + 3], x},
  {E^(3 x) Cos[x] Cos[x + 2], x},

  (* Formula 521: E^(a x) Cos[b x] Sin[b x + c] *)
  {E^(2 x) Cos[3 x] Sin[3 x + 5], x},
  {E^x Cos[2 x] Sin[2 x + 3], x},
  {E^(3 x) Cos[x] Sin[x + 2], x},

  (* Formula 522: E^(a x) Sin[b x]^n recursive *)
  {E^(2 x) Sin[3 x]^2, x},
  {E^x Sin[2 x]^3, x},
  {E^(3 x) Sin[x]^2, x},

  (* Formula 523: E^(a x) Cos[b x]^n recursive *)
  {E^(2 x) Cos[3 x]^2, x},
  {E^x Cos[2 x]^3, x},
  {E^(3 x) Cos[x]^2, x},

  (* Formula 524: x^m E^x Sin[x] recursive *)
  {x E^x Sin[x], x},
  {x^2 E^x Sin[x], x},
  {x^3 E^x Sin[x], x},

  (* Formula 525: x^m E^(a x) Sin[b x] recursive *)
  {x E^(2 x) Sin[3 x], x},
  {x^2 E^(3 x) Sin[x], x},
  {x E^x Sin[2 x], x},

  (* Formula 526: x^m E^x Cos[x] recursive *)
  {x E^x Cos[x], x},
  {x^2 E^x Cos[x], x},
  {x^3 E^x Cos[x], x},

  (* Formula 527: x^m E^(a x) Cos[b x] recursive *)
  {x E^(2 x) Cos[3 x], x},
  {x^2 E^(3 x) Cos[x], x},
  {x E^x Cos[2 x], x},

  (* ============================================================ *)
  (* SECTION 12: Hyperbolic (Formulas 534-558)                     *)
  (* ============================================================ *)

  (* Formula 534-539: basic hyperbolics *)
  {Sinh[x], x},
  {Cosh[x], x},
  {Tanh[x], x},
  {Coth[x], x},
  {Sech[x], x},
  {Csch[x], x},

  (* Formula 540 & 542: x Sinh[x], x Cosh[x] *)
  {x Sinh[x], x},
  {x Cosh[x], x},

  (* Formula 541 & 543: x^n Sinh/Cosh recursive *)
  {x^2 Sinh[x], x},
  {x^3 Sinh[x], x},
  {x^2 Cosh[x], x},
  {x^3 Cosh[x], x},

  (* Formula 544: Sech[x] Tanh[x] *)
  {Sech[x] Tanh[x], x},

  (* Formula 545: Csch[x] Coth[x] *)
  {Csch[x] Coth[x], x},

  (* Formula 546-555: hyperbolic squares *)
  {Sinh[x]^2, x},
  {Cosh[x]^2, x},
  {Tanh[x]^2, x},
  {Sech[x]^2, x},
  {Coth[x]^2, x},
  {Csch[x]^2, x},

  (* Formula 547: Sinh[x]^m Cosh[x]^n recursive *)
  {Sinh[x]^2 Cosh[x]^2, x},
  {Sinh[x]^3 Cosh[x]^2, x},
  {Sinh[x]^2 Cosh[x]^3, x},

  (* Formula 548: 1/(Sinh[x]^m Cosh[x]^n) recursive *)
  {1/(Sinh[x]^2 Cosh[x]^2), x},
  {1/(Sinh[x]^3 Cosh[x]^2), x},
  {1/(Sinh[x]^2 Cosh[x]^3), x},

  (* Formula 550: Tanh[a x]^n recursive *)
  {Tanh[2 x]^2, x},
  {Tanh[3 x]^3, x},
  {Tanh[x]^4, x},

  (* Formula 554: Coth[a x]^n recursive *)
  {Coth[2 x]^2, x},
  {Coth[3 x]^3, x},
  {Coth[x]^4, x},

  (* Sinh reduction (extension): Sinh[a x]^n *)
  {Sinh[2 x]^2, x},
  {Sinh[3 x]^3, x},
  {Sinh[x]^4, x},

  (* Cosh reduction (extension): Cosh[a x]^n *)
  {Cosh[2 x]^2, x},
  {Cosh[3 x]^3, x},
  {Cosh[x]^4, x},

  (* Sech reduction (extension): Sech[a x]^n *)
  {Sech[2 x]^2, x},
  {Sech[3 x]^3, x},
  {Sech[x]^4, x},

  (* Csch reduction (extension): Csch[a x]^n *)
  {Csch[2 x]^2, x},
  {Csch[3 x]^3, x},
  {Csch[x]^4, x},

  (* Formula 556: Sinh[m x] Sinh[n x] *)
  {Sinh[2 x] Sinh[3 x], x},
  {Sinh[3 x] Sinh[5 x], x},
  {Sinh[x] Sinh[2 x], x},

  (* Formula 557: Cosh[m x] Cosh[n x] *)
  {Cosh[2 x] Cosh[3 x], x},
  {Cosh[3 x] Cosh[5 x], x},
  {Cosh[x] Cosh[2 x], x},

  (* Formula 558: Sinh[m x] Cosh[n x] *)
  {Sinh[2 x] Cosh[3 x], x},
  {Sinh[3 x] Cosh[5 x], x},
  {Sinh[x] Cosh[2 x], x},

  (* ============================================================ *)
  (* SECTION 13: Bessel (Formulas 577-581)                         *)
  (* ============================================================ *)

  (* Formula 577a: x^(p+1) BesselJ[p, x] *)
  {x^3 BesselJ[2, x], x},
  {x^4 BesselJ[3, x], x},
  {x^2 BesselJ[1, x], x},

  (* Formula 577b: x^(p+1) BesselY[p, x] *)
  {x^3 BesselY[2, x], x},
  {x^4 BesselY[3, x], x},
  {x^2 BesselY[1, x], x},

  (* Formula 578a: x^(-p+1) BesselJ[p, x] *)
  {x^(-1) BesselJ[2, x], x},
  {x^(-2) BesselJ[3, x], x},
  (* {x^0 BesselJ[1, x], x} — partial Bessel D rules produce an answer
     that does not differentiate back; restore once full special-function
     support exists. *)

  (* Formula 578b: x^(-p+1) BesselY[p, x] *)
  {x^(-1) BesselY[2, x], x},
  {x^(-2) BesselY[3, x], x},
  {x^0 BesselY[1, x], x}

  (* Formulas 580/581 ({BesselJ[1, x], x} and {x BesselJ[0, x], x})
     are dropped pending real BesselJ support; they currently produce
     CRC-rule output that does not differentiate back. *)
}
