/* galg_iso.c - graph isomorphism and canonical labeling by
 * individualization-refinement (the nauty / bliss / Traces family).
 *
 * No Expr dependency: the engine works on GalgIsoGraph (CSR relations) and
 * calls nothing outside the C library except galg_poll().
 *
 * ---------------------------------------------------------------------------
 * 1. Relations and colours
 *    A graph carries up to three relations over 0..n-1: undirected (U),
 *    directed out (O) and its transpose in (I). Missing transposes are built
 *    here, empty relations are dropped, so two graphs with the same edge
 *    counts always run exactly the same refinement passes. vcol values are
 *    ranked; the initial ordered partition lists the colour classes by
 *    increasing colour value (an isomorphism-invariant order).
 *
 * 2. Refinement (1-dimensional Weisfeiler-Leman, Hopcroft / Paige-Tarjan)
 *    The ordered partition is kept nauty-style in lab[] (cells are contiguous
 *    position ranges, a cell is named by its start position). A FIFO queue of
 *    splitter cells drives the refinement. For a splitter W and each relation
 *    R separately, only the R-neighbours of W are visited; every visited
 *    vertex gets a count |R(x) cap W| and is swapped to the tail of its cell,
 *    so the untouched part (count 0) stays at the front and needs no work.
 *    Touched cells are processed in increasing start position, the touched
 *    tail is sorted by count, and the cell becomes the fragments
 *    [count 0][count c1][count c2]... (c1 < c2 < ...). If the parent cell was
 *    queued, all new fragments are queued, otherwise all but the first
 *    largest (Hopcroft's "skip the largest half"), which gives
 *    O((n + m) log n) per full refinement. Singleton cells are never touched.
 *    The result is the coarsest equitable refinement.
 *
 *    Invariance: every decision (splitter order, touched-cell order, fragment
 *    order, queueing) depends only on cell start positions, cell sizes and
 *    counts, never on vertex ids, so for an isomorphism phi the refinement of
 *    phi(G) is exactly phi applied to the refinement of G, split for split.
 *    Vertex order inside a cell is arbitrary (it may depend on ids); nothing
 *    reads it except the non-invariant choice of the first-path child.
 *
 * 3. Traces
 *    Each refinement produces a trace: a running 64-bit hash over
 *    (splitter position/size, relation, touched cell, fragment counts and
 *    sizes), emitted as one event per actual split plus a final event (with
 *    the cell count). Events are compared on the fly against a reference
 *    trace (first path, best path, or the other graph); the refinement is
 *    abandoned as soon as it can no longer match or beat the reference
 *    ("early abort"). This is what makes the search cheap: a wrong branch in
 *    a random regular graph dies after O(sqrt n) work instead of O(n log n).
 *    Events per node <= new cells + 1, so traces along a path are O(n).
 *
 * 4. Search tree
 *    Node = equitable ordered partition; child = individualize a vertex of
 *    the target cell (first smallest non-singleton cell, by (size, start) --
 *    invariant) and refine. Individualized vertices go to the END of their
 *    cell so the big remainder keeps its start (O(1) individualization).
 *    The tree is walked iteratively with per-level undo marks: every split,
 *    lab write and set operation is logged and undone exactly, so memory is
 *    O(n + m + work on the current path) and the depth may be n (no
 *    recursion anywhere).
 *
 * 5. Canonical form (galg_iso_canon / galg_iso_automorphisms)
 *    Leaf key = (trace of level 1, trace of level 2, ..., relabeled graph),
 *    compared lexicographically; the canonical labeling is the leaf of
 *    maximal key. The key is isomorphism-invariant, hence relabeling G and
 *    phi(G) by their best leaves gives identical graphs. Pruning (nauty):
 *    - trace pruning: a node whose trace prefix is below the best leaf's and
 *      differs from the first leaf's is cut (mid-refinement);
 *    - automorphisms: a leaf equal (as relabeled graph) to the first leaf or
 *      the best leaf yields an automorphism; an internal node whose trace
 *      equals the first path's is also tested directly: the singletons
 *      created on the first path since the divergence level are mapped
 *      positionally to the current node's singletons, the partial map is
 *      closed into a permutation that fixes everything else, and it is
 *      verified on the moved vertices only (this finds twins, swapped
 *      components, ... without descending). After an automorphism we jump
 *      back to the divergence level (first leaf) or to the common ancestor
 *      (best leaf);
 *    - orbit pruning on the first path: at first-path level k only one child
 *      per orbit of the group generated by the automorphisms found so far
 *      (all of which fix the first-path prefix) is explored; a level is
 *      finished as soon as the explored orbits cover the target cell.
 *    The automorphisms found this way generate Aut(G) (standard
 *    individualization-refinement argument, as in nauty).
 *
 * 6. Isomorphism (galg_iso_find / galg_iso_enumerate)
 *    Quick rejections (n, edge counts, colour classes, degree histograms),
 *    then G and H are refined in lockstep. find: follow one path in G and
 *    search H for a path with identical traces (early abort on the first
 *    deviating event), verifying the map edge by edge at a leaf. If that
 *    direct search exceeds ~4n nodes, fall back to comparing the two
 *    canonical forms (robust with automorphism pruning). enumerate: the
 *    direct search without pruning visits every H-leaf trace-consistent with
 *    G's path exactly once; every isomorphism corresponds to exactly one
 *    such leaf, so each verified leaf is reported once.
 *
 * Complexity: one refinement O((n + m) log n); the number of tree nodes is
 * small for random and most structured graphs and bounded by `budget`
 * (refinement calls) in the worst case (e.g. CFI-type constructions).
 * galg_poll() is called every 256 nodes and every ~32k edge visits.
 */

#include <limits.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "graph_algos.h"

typedef uint64_t u64;

#define ISO_POLL_NODES 256L
#define ISO_POLL_WORK (1L << 15)

/* Node limit of the direct G -> H search before falling back to comparing
 * canonical forms (overridable for testing). */
#ifndef GALG_ISO_DIRECT_LIMIT
#define GALG_ISO_DIRECT_LIMIT(n) (4L * (n) + 1000)
#endif

/* ========================================================================
 * Utilities
 * ======================================================================== */

typedef struct { int* a; long n, cap; } IVec;
typedef struct { u64* a; long n, cap; } UVec;

static int ivec_grow(IVec* v, long need) {
    long nc;
    int* na;
    if (need <= v->cap) return 1;
    nc = v->cap > 0 ? v->cap : 256;
    while (nc < need) nc *= 2;
    na = (int*)realloc(v->a, (size_t)nc * sizeof(int));
    if (!na) return 0;
    v->a = na;
    v->cap = nc;
    return 1;
}

static int uvec_grow(UVec* v, long need) {
    long nc;
    u64* na;
    if (need <= v->cap) return 1;
    nc = v->cap > 0 ? v->cap : 256;
    while (nc < need) nc *= 2;
    na = (u64*)realloc(v->a, (size_t)nc * sizeof(u64));
    if (!na) return 0;
    v->a = na;
    v->cap = nc;
    return 1;
}

static int push1(IVec* v, int a) {
    if (v->n + 1 > v->cap && !ivec_grow(v, v->n + 1)) return 0;
    v->a[v->n++] = a;
    return 1;
}

static int push2(IVec* v, int a, int b) {
    if (v->n + 2 > v->cap && !ivec_grow(v, v->n + 2)) return 0;
    v->a[v->n++] = a;
    v->a[v->n++] = b;
    return 1;
}

static u64 mix64(u64 h, u64 x) {
    h ^= x + 0x9E3779B97F4A7C15ULL + (h << 6) + (h >> 2);
    h *= 0xBF58476D1CE4E5B9ULL;
    h ^= h >> 29;
    return h;
}

static int cmp_int(const void* a, const void* b) {
    int x = *(const int*)a, y = *(const int*)b;
    return (x > y) - (x < y);
}

static int cmp_u64(const void* a, const void* b) {
    u64 x = *(const u64*)a, y = *(const u64*)b;
    return (x > y) - (x < y);
}

static void sort_ints(int* a, long n) {
    long i, j;
    if (n > 24) {
        qsort(a, (size_t)n, sizeof(int), cmp_int);
        return;
    }
    for (i = 1; i < n; i++) {
        int x = a[i];
        for (j = i; j > 0 && a[j - 1] > x; j--) a[j] = a[j - 1];
        a[j] = x;
    }
}

/* Search control shared by everything one API call does. */
typedef struct {
    long budget, nodes;
    long work; /* edge visits since the last galg_poll() */
    int err;   /* budget exhausted or allocation failure */
} Ctl;

static void ctl_work(Ctl* c, long w) {
    c->work += w;
    if (c->work > ISO_POLL_WORK) {
        c->work = 0;
        galg_poll();
    }
}

static int ctl_node(Ctl* c) {
    c->nodes++;
    if (c->nodes % ISO_POLL_NODES == 0) galg_poll();
    if (c->budget > 0 && c->nodes > c->budget) {
        c->err = 1;
        return 0;
    }
    return 1;
}

/* ========================================================================
 * Internal graph: normalized relations and colour classes
 * ======================================================================== */

typedef struct {
    int n;
    const int *uo, *ua; /* undirected; NULL when empty           */
    const int *oo, *oa; /* out; NULL when there are no arcs       */
    const int *io, *ia; /* in (transpose of out)                  */
    int* own[4];        /* transposes built here                  */
    const int* vcol;
    int* cls;           /* colour class (rank of vcol value)      */
    int ncls;
    int *clsval, *clssz;
    long mu, md;        /* entries of uadj, number of arcs        */
} IG;

static void ig_free(IG* G) {
    int i;
    for (i = 0; i < 4; i++) free(G->own[i]);
    free(G->cls);
    free(G->clsval);
    free(G->clssz);
    memset(G, 0, sizeof *G);
}

static int rel_ok(int n, const int* off, const int* adj) {
    int v;
    long j;
    for (v = 0; v < n; v++)
        if (off[v + 1] < off[v]) return 0;
    if (off[n] > off[0] && !adj) return 0;
    for (j = off[0]; j < off[n]; j++)
        if (adj[j] < 0 || adj[j] >= n) return 0;
    return 1;
}

static int transpose(int n, const int* off, const int* adj, int** toff, int** tadj) {
    long m = (long)off[n] - off[0], j;
    int v;
    int* to = (int*)calloc((size_t)n + 1, sizeof(int));
    int* ta = (int*)malloc((size_t)(m > 0 ? m : 1) * sizeof(int));
    int* cur = (int*)malloc((size_t)n * sizeof(int));
    if (!to || !ta || !cur) {
        free(to);
        free(ta);
        free(cur);
        return 0;
    }
    for (j = off[0]; j < off[n]; j++) to[adj[j] + 1]++;
    for (v = 0; v < n; v++) to[v + 1] += to[v];
    memcpy(cur, to, (size_t)n * sizeof(int));
    for (v = 0; v < n; v++)
        for (j = off[v]; j < off[v + 1]; j++) ta[cur[adj[j]]++] = v;
    free(cur);
    *toff = to;
    *tadj = ta;
    return 1;
}

typedef struct { int val, v; } VPair;

static int cmp_vpair(const void* a, const void* b) {
    const VPair* x = (const VPair*)a;
    const VPair* y = (const VPair*)b;
    if (x->val != y->val) return x->val < y->val ? -1 : 1;
    return (x->v > y->v) - (x->v < y->v);
}

/* 1 ok, 0 allocation failure or malformed input. Requires n >= 1. */
static int ig_build(IG* G, const GalgIsoGraph* g) {
    int n = g->n, i;
    memset(G, 0, sizeof *G);
    G->n = n;
    G->vcol = g->vcol;
    if (g->uoff) {
        if (!rel_ok(n, g->uoff, g->uadj)) return 0;
        G->mu = (long)g->uoff[n] - g->uoff[0];
        if (G->mu > 0) {
            G->uo = g->uoff;
            G->ua = g->uadj;
        }
    }
    if (g->ooff) {
        if (!rel_ok(n, g->ooff, g->oadj)) return 0;
        G->md = (long)g->ooff[n] - g->ooff[0];
        if (G->md > 0) {
            G->oo = g->ooff;
            G->oa = g->oadj;
            if (g->ioff) {
                if (!rel_ok(n, g->ioff, g->iadj)) return 0;
                if ((long)g->ioff[n] - g->ioff[0] != G->md) return 0;
                G->io = g->ioff;
                G->ia = g->iadj;
            } else {
                if (!transpose(n, g->ooff, g->oadj, &G->own[0], &G->own[1])) return 0;
                G->io = G->own[0];
                G->ia = G->own[1];
            }
        }
    } else if (g->ioff) {
        if (!rel_ok(n, g->ioff, g->iadj)) return 0;
        G->md = (long)g->ioff[n] - g->ioff[0];
        if (G->md > 0) {
            G->io = g->ioff;
            G->ia = g->iadj;
            if (!transpose(n, g->ioff, g->iadj, &G->own[2], &G->own[3])) return 0;
            G->oo = G->own[2];
            G->oa = G->own[3];
        }
    }
    G->cls = (int*)malloc((size_t)n * sizeof(int));
    if (!G->cls) return 0;
    if (!g->vcol) {
        G->ncls = 1;
        G->clsval = (int*)malloc(sizeof(int));
        G->clssz = (int*)malloc(sizeof(int));
        if (!G->clsval || !G->clssz) return 0;
        G->clsval[0] = 0;
        G->clssz[0] = n;
        for (i = 0; i < n; i++) G->cls[i] = 0;
    } else {
        VPair* pr = (VPair*)malloc((size_t)n * sizeof(VPair));
        int c = 0;
        if (!pr) return 0;
        for (i = 0; i < n; i++) {
            pr[i].val = g->vcol[i];
            pr[i].v = i;
        }
        qsort(pr, (size_t)n, sizeof(VPair), cmp_vpair);
        for (i = 0; i < n; i++)
            if (i == 0 || pr[i].val != pr[i - 1].val) c++;
        G->ncls = c;
        G->clsval = (int*)malloc((size_t)c * sizeof(int));
        G->clssz = (int*)calloc((size_t)c, sizeof(int));
        if (!G->clsval || !G->clssz) {
            free(pr);
            return 0;
        }
        c = -1;
        for (i = 0; i < n; i++) {
            if (i == 0 || pr[i].val != pr[i - 1].val) {
                c++;
                G->clsval[c] = pr[i].val;
            }
            G->cls[pr[i].v] = c;
            G->clssz[c]++;
        }
        free(pr);
    }
    return 1;
}

/* Cheap necessary conditions. 1 = may be isomorphic, 0 = not, -1 = alloc. */
static int quick_same(const IG* G, const IG* H) {
    int n = G->n, i, v, r;
    int* hist;
    if (G->mu != H->mu || G->md != H->md || G->ncls != H->ncls) return 0;
    for (i = 0; i < G->ncls; i++)
        if (G->clsval[i] != H->clsval[i] || G->clssz[i] != H->clssz[i]) return 0;
    hist = (int*)calloc((size_t)n + 1, sizeof(int));
    if (!hist) return -1;
    for (r = 0; r < 3; r++) {
        const int* go = r == 0 ? G->uo : r == 1 ? G->oo : G->io;
        const int* ho = r == 0 ? H->uo : r == 1 ? H->oo : H->io;
        if (!go) continue;
        for (v = 0; v < n; v++) {
            int dg = go[v + 1] - go[v], dh = ho[v + 1] - ho[v];
            if (dg > n) dg = n;
            if (dh > n) dh = n;
            hist[dg]++;
            hist[dh]--;
        }
        for (i = 0; i <= n; i++)
            if (hist[i]) {
                free(hist);
                return 0;
            }
    }
    free(hist);
    return 1;
}

/* ========================================================================
 * Ordered partition with refinement and exact undo
 * ======================================================================== */

typedef struct { long lab, split, sing, ev; } Mark;

typedef struct {
    const IG* g;
    Ctl* ctl;
    int n;
    int *lab, *inv;   /* lab[pos] = vertex, inv[vertex] = pos              */
    int *cst, *csz;   /* cst[v] = start of v's cell, csz[start] = size     */
    int ncells;
    unsigned char* inq;
    int* q;           /* circular FIFO of splitter cell starts             */
    int qh, qn;
    int *cnt, *tc, *tcl;
    int ntc;
    int *wbuf, *frs, *frc, *tmpv, *bkt;
    u64* tmpk;
    u64* st;          /* min segment tree over positions: key (size, start)
                       * of every non-singleton cell, ~0 elsewhere         */
    int stsz;
    IVec lablog;      /* (pos, old vertex)                                 */
    IVec splitlog;    /* (parent start, fragment start)                    */
    IVec singlog;     /* positions that became singleton cells             */
    UVec ev;          /* trace events of the current path                  */
    /* trace comparison for the refinement in progress */
    int cmpmode;
    const u64* refA;  /* must match exactly (first path / other graph)     */
    long lenA;
    int eqA;
    const u64* refB;  /* lexicographic comparison with the best path       */
    long lenB;
    int stB;          /* -1 worse, 0 equal so far, +1 better               */
    long evbase;
    u64 h;
    int abrt;
} Part;

static void part_free(Part* P) {
    free(P->lab);
    free(P->inv);
    free(P->cst);
    free(P->csz);
    free(P->inq);
    free(P->q);
    free(P->cnt);
    free(P->tc);
    free(P->tcl);
    free(P->wbuf);
    free(P->frs);
    free(P->frc);
    free(P->tmpv);
    free(P->bkt);
    free(P->tmpk);
    free(P->st);
    free(P->lablog.a);
    free(P->splitlog.a);
    free(P->singlog.a);
    free(P->ev.a);
    memset(P, 0, sizeof *P);
}

static void enq(Part* P, int s) {
    int t = P->qh + P->qn;
    if (t >= P->n) t -= P->n;
    P->q[t] = s;
    P->qn++;
    P->inq[s] = 1;
}

/* Refresh the target-cell tree at position pos (start = pos is a cell start). */
static void st_upd(Part* P, int pos, int start) {
    int i = pos + P->stsz;
    u64* t = P->st;
    t[i] = (start && P->csz[pos] >= 2) ? (((u64)(unsigned)P->csz[pos] << 32) | (u64)(unsigned)pos)
                                        : ~(u64)0;
    for (i >>= 1; i > 0; i >>= 1) {
        u64 m = t[2 * i] < t[2 * i + 1] ? t[2 * i] : t[2 * i + 1];
        if (t[i] == m) break;
        t[i] = m;
    }
}

/* Initial partition = colour classes in increasing colour value, all queued. */
static int part_init(Part* P, const IG* G, Ctl* ctl) {
    int n = G->n, i, c, pos;
    size_t N = (size_t)n;
    memset(P, 0, sizeof *P);
    P->g = G;
    P->ctl = ctl;
    P->n = n;
    P->lab = (int*)malloc(N * sizeof(int));
    P->inv = (int*)malloc(N * sizeof(int));
    P->cst = (int*)malloc(N * sizeof(int));
    P->csz = (int*)malloc(N * sizeof(int));
    P->inq = (unsigned char*)calloc(N, 1);
    P->q = (int*)malloc(N * sizeof(int));
    P->cnt = (int*)calloc(N, sizeof(int));
    P->tc = (int*)calloc(N, sizeof(int));
    P->tcl = (int*)malloc(N * sizeof(int));
    P->wbuf = (int*)malloc(N * sizeof(int));
    P->frs = (int*)malloc((N + 2) * sizeof(int));
    P->frc = (int*)malloc((N + 2) * sizeof(int));
    P->tmpv = (int*)malloc(N * sizeof(int));
    P->bkt = (int*)malloc((2 * N + 18) * sizeof(int));
    P->tmpk = (u64*)malloc(N * sizeof(u64));
    P->stsz = 1;
    while (P->stsz < n) P->stsz *= 2;
    P->st = (u64*)malloc(2 * (size_t)P->stsz * sizeof(u64));
    if (!P->lab || !P->inv || !P->cst || !P->csz || !P->inq || !P->q || !P->cnt || !P->tc ||
        !P->tcl || !P->wbuf || !P->frs || !P->frc || !P->tmpv || !P->bkt || !P->tmpk ||
        !P->st)
        return 0;
    /* counting sort of the vertices by colour class */
    {
        int* start = (int*)malloc(((size_t)G->ncls + 1) * sizeof(int));
        if (!start) return 0;
        start[0] = 0;
        for (c = 0; c < G->ncls; c++) start[c + 1] = start[c] + G->clssz[c];
        for (i = 0; i < n; i++) {
            c = G->cls[i];
            pos = start[c]++;
            P->lab[pos] = i;
            P->inv[i] = pos;
        }
        free(start);
    }
    for (i = 0; i < 2 * P->stsz; i++) P->st[i] = ~(u64)0;
    pos = 0;
    for (c = 0; c < G->ncls; c++) {
        int sz = G->clssz[c];
        for (i = pos; i < pos + sz; i++) P->cst[P->lab[i]] = pos;
        P->csz[pos] = sz;
        st_upd(P, pos, 1);
        enq(P, pos);
        pos += sz;
    }
    P->ncells = G->ncls;
    return 1;
}

static void perr(Part* P) {
    P->ctl->err = 1;
    P->abrt = 1;
}

/* Append the current hash as a trace event and compare with the references. */
static void emit(Part* P) {
    long idx;
    u64 x = P->h;
    if (P->ev.n + 1 > P->ev.cap && !uvec_grow(&P->ev, P->ev.n + 1)) {
        perr(P);
        return;
    }
    P->ev.a[P->ev.n++] = x;
    if (!P->cmpmode) return;
    idx = P->ev.n - 1 - P->evbase;
    if (P->eqA && (idx >= P->lenA || P->refA[idx] != x)) P->eqA = 0;
    if (P->stB == 0) {
        if (idx >= P->lenB)
            P->stB = 1;
        else if (x != P->refB[idx])
            P->stB = x > P->refB[idx] ? 1 : -1;
    }
    if (!P->eqA && P->stB < 0) P->abrt = 1;
}

/* Sort lab[b .. b+t) by count (counting sort when the range is small). */
static int sort_region(Part* P, int b, int t, int mn, int mx) {
    int *lab = P->lab, *inv = P->inv, *cnt = P->cnt, *out = P->tmpv;
    long range = (long)mx - mn + 1;
    int i;
    if (range <= 2L * t + 16) {
        int* bk = P->bkt;
        for (i = 0; i <= range; i++) bk[i] = 0;
        for (i = 0; i < t; i++) bk[cnt[lab[b + i]] - mn + 1]++;
        for (i = 0; i < range; i++) bk[i + 1] += bk[i];
        for (i = 0; i < t; i++) {
            int v = lab[b + i];
            out[bk[cnt[v] - mn]++] = v;
        }
    } else {
        u64* k = P->tmpk;
        for (i = 0; i < t; i++) {
            int v = lab[b + i];
            k[i] = ((u64)(unsigned)(cnt[v] - mn) << 32) | (u64)(unsigned)v;
        }
        qsort(k, (size_t)t, sizeof(u64), cmp_u64);
        for (i = 0; i < t; i++) out[i] = (int)(k[i] & 0xffffffffu);
    }
    if (P->lablog.n + 2L * t > P->lablog.cap && !ivec_grow(&P->lablog, P->lablog.n + 2L * t))
        return 0;
    for (i = 0; i < t; i++) {
        int v = out[i], q = b + i;
        if (lab[q] != v) {
            P->lablog.a[P->lablog.n++] = q;
            P->lablog.a[P->lablog.n++] = lab[q];
            lab[q] = v;
            inv[v] = q;
        }
    }
    return 1;
}

/* Split cell s (size sz) whose t touched vertices occupy its tail. */
static void do_split(Part* P, int r, int s, int sz, int t) {
    int e = s + sz, b = e - t, mn = INT_MAX, mx = INT_MIN, q, i, nf = 0, L = 0, inqp;
    int *lab = P->lab, *cnt = P->cnt, *frs = P->frs, *frc = P->frc;
    u64 h;
    for (q = b; q < e; q++) {
        int c = cnt[lab[q]];
        if (c < mn) mn = c;
        if (c > mx) mx = c;
    }
    if (t == sz && mn == mx) { /* no split; still an invariant fact */
        P->h = mix64(P->h, ((u64)(unsigned)s << 20) ^ ((u64)(unsigned)mn << 42) ^
                               (u64)(unsigned)(r + 1));
        return;
    }
    if (mn != mx && !sort_region(P, b, t, mn, mx)) {
        perr(P);
        return;
    }
    if (b > s) {
        frs[nf] = s;
        frc[nf] = 0;
        nf++;
    }
    for (q = b; q < e;) {
        int c = cnt[lab[q]];
        frs[nf] = q;
        frc[nf] = c;
        nf++;
        q++;
        while (q < e && cnt[lab[q]] == c) q++;
    }
    frs[nf] = e;
    h = mix64(P->h, ((u64)(unsigned)s << 8) ^ (u64)(unsigned)(r + 1) ^ ((u64)(unsigned)nf << 40));
    for (i = 0; i < nf; i++) {
        int fz = frs[i + 1] - frs[i];
        h = mix64(h, ((u64)(unsigned)frc[i] << 32) | (u64)(unsigned)fz);
        if (fz > frs[L + 1] - frs[L]) L = i;
    }
    P->h = h;
    inqp = P->inq[s];
    for (i = 1; i < nf; i++) {
        int f = frs[i], fz = frs[i + 1] - f;
        P->csz[f] = fz;
        for (q = f; q < f + fz; q++) P->cst[lab[q]] = f;
        if (!push2(&P->splitlog, s, f)) {
            perr(P);
            return;
        }
        P->ncells++;
    }
    P->csz[s] = frs[1] - s;
    st_upd(P, s, 1);
    if (frs[1] - s == 1 && !push1(&P->singlog, s)) {
        perr(P);
        return;
    }
    for (i = 1; i < nf; i++) {
        int f = frs[i];
        if (frs[i + 1] - f >= 2) {
            st_upd(P, f, 1);
        } else if (!push1(&P->singlog, f)) {
            perr(P);
            return;
        }
    }
    for (i = 0; i < nf; i++)
        if (inqp ? i > 0 : i != L) enq(P, frs[i]);
    emit(P);
}

static void split_cells(Part* P, int r) {
    int ci, q;
    sort_ints(P->tcl, P->ntc); /* invariant order: by cell position */
    for (ci = 0; ci < P->ntc; ci++) {
        int s = P->tcl[ci], sz = P->csz[s], t = P->tc[s], e = s + sz;
        if (!P->abrt) do_split(P, r, s, sz, t);
        for (q = e - t; q < e; q++) P->cnt[P->lab[q]] = 0;
        P->tc[s] = 0;
    }
    P->ntc = 0;
}

/* Count, for every vertex x, |{w in W : w in adj(x) direction r}| by visiting
 * the reverse adjacency (off, adj) of W's members. */
static void pass(Part* P, int r, int wn, const int* off, const int* adj) {
    const int* W = P->wbuf;
    int *cst = P->cst, *csz = P->csz, *cnt = P->cnt, *tc = P->tc, *lab = P->lab, *inv = P->inv;
    long work = 0;
    int i;
    for (i = 0; i < wn; i++) {
        int w = W[i], j, j1 = off[w + 1];
        for (j = off[w]; j < j1; j++) {
            int x = adj[j], s = cst[x];
            if (csz[s] == 1) continue;
            if (cnt[x]++ == 0) {
                int pos = s + csz[s] - 1 - tc[s], px = inv[x];
                if (tc[s]++ == 0) P->tcl[P->ntc++] = s;
                if (px != pos) { /* move x into the touched tail */
                    int y = lab[pos];
                    IVec* L = &P->lablog;
                    if (L->n + 4 > L->cap && !ivec_grow(L, L->n + 4)) {
                        perr(P);
                        return;
                    }
                    L->a[L->n++] = px;
                    L->a[L->n++] = x;
                    L->a[L->n++] = pos;
                    L->a[L->n++] = y;
                    lab[pos] = x;
                    inv[x] = pos;
                    lab[px] = y;
                    inv[y] = px;
                }
            }
        }
        work += j1 - off[w] + 1;
        if (work > 4096) {
            ctl_work(P->ctl, work);
            work = 0;
        }
    }
    ctl_work(P->ctl, work);
    if (P->ntc) split_cells(P, r);
}

/* Refine to the coarsest equitable partition.
 * Returns 0 done, 1 aborted (trace cannot match/beat the references),
 * -1 error. */
static int refine(Part* P) {
    const IG* g = P->g;
    P->h = 0x243F6A8885A308D3ULL;
    P->abrt = 0;
    P->evbase = P->ev.n;
    while (P->qn > 0 && P->ncells < P->n && !P->abrt) {
        int s = P->q[P->qh], sz;
        if (++P->qh == P->n) P->qh = 0;
        P->qn--;
        P->inq[s] = 0;
        sz = P->csz[s];
        memcpy(P->wbuf, P->lab + s, (size_t)sz * sizeof(int));
        P->h = mix64(P->h, ((u64)(unsigned)s << 32) | (u64)(unsigned)sz);
        if (g->uo) pass(P, 0, sz, g->uo, g->ua);
        if (g->oo) {
            if (!P->abrt) pass(P, 1, sz, g->io, g->ia); /* out-neighbours in W */
            if (!P->abrt) pass(P, 2, sz, g->oo, g->oa); /* in-neighbours in W  */
        }
    }
    while (P->qn > 0) {
        P->inq[P->q[P->qh]] = 0;
        if (++P->qh == P->n) P->qh = 0;
        P->qn--;
    }
    if (P->ctl->err) return -1;
    if (P->abrt) return 1;
    P->h = mix64(P->h, (u64)(unsigned)P->ncells);
    emit(P);
    if (P->ctl->err) return -1;
    if (P->cmpmode) {
        long ne = P->ev.n - P->evbase;
        if (P->eqA && ne != P->lenA) P->eqA = 0;
        if (P->stB == 0 && ne < P->lenB) P->stB = -1;
        if (!P->eqA && P->stB < 0) return 1;
    }
    return 0;
}

/* Individualize v: it becomes a singleton at the END of its cell. */
static int individualize(Part* P, int v) {
    int s = P->cst[v], sz = P->csz[s], e = s + sz - 1, pv = P->inv[v];
    if (pv != e) {
        int y = P->lab[e];
        if (!push2(&P->lablog, pv, v) || !push2(&P->lablog, e, y)) return 0;
        P->lab[e] = v;
        P->inv[v] = e;
        P->lab[pv] = y;
        P->inv[y] = pv;
    }
    P->csz[s] = sz - 1;
    P->csz[e] = 1;
    P->cst[v] = e;
    if (!push2(&P->splitlog, s, e)) return 0;
    P->ncells++;
    if (!push1(&P->singlog, e)) return 0;
    st_upd(P, s, 1);
    if (sz - 1 == 1 && !push1(&P->singlog, s)) return 0;
    enq(P, e);
    return 1;
}

/* Target cell: first smallest non-singleton cell (by size, then position). */
static int pick_target(const Part* P) {
    return P->st[1] == ~(u64)0 ? -1 : (int)(P->st[1] & 0xffffffffu);
}

static void get_mark(const Part* P, Mark* m) {
    m->lab = P->lablog.n;
    m->split = P->splitlog.n;
    m->sing = P->singlog.n;
    m->ev = P->ev.n;
}

static void reset_logs(Part* P) {
    P->lablog.n = P->splitlog.n = P->singlog.n = 0;
}

/* Restore the exact state recorded in m (partition, lab order, sets). */
static void undo_to(Part* P, const Mark* m) {
    int* a = P->splitlog.a;
    while (P->splitlog.n > m->split) {
        int f = a[--P->splitlog.n], s = a[--P->splitlog.n], fz = P->csz[f], q;
        /* lab[f .. f+fz) still holds exactly fragment f's vertices: later
         * writes only permute within cells, later splits are undone first */
        for (q = f; q < f + fz; q++) P->cst[P->lab[q]] = s;
        P->csz[s] += fz;
        P->ncells--;
        st_upd(P, f, 0);
        st_upd(P, s, 1);
    }
    a = P->lablog.a;
    while (P->lablog.n > m->lab) {
        int old = a[--P->lablog.n], p = a[--P->lablog.n];
        P->lab[p] = old;
        P->inv[old] = p;
    }
    P->singlog.n = m->sing;
    P->ev.n = m->ev;
}

/* ========================================================================
 * Map verification (edge by edge)
 * ======================================================================== */

static int rel_map_ok(int n, const int* go, const int* ga, const int* ho, const int* ha,
                      const int* map, int* mark, int* stamp) {
    int v;
    long j;
    for (v = 0; v < n; v++) {
        int w = map[v], d = go[v + 1] - go[v];
        if (ho[w + 1] - ho[w] != d) return 0;
        if (d == 0) continue;
        ++*stamp;
        for (j = ho[w]; j < ho[w + 1]; j++) mark[ha[j]] = *stamp;
        for (j = go[v]; j < go[v + 1]; j++)
            if (mark[map[ga[j]]] != *stamp) return 0;
    }
    return 1;
}

/* 1 if map is an isomorphism G -> H (colours and every relation). */
static int verify_map(const IG* G, const IG* H, const int* map, int* mark) {
    int n = G->n, v, stamp = 0;
    for (v = 0; v < n; v++) mark[v] = 0;
    for (v = 0; v < n; v++) {
        int gv = G->vcol ? G->vcol[v] : 0, hv;
        if (map[v] < 0 || map[v] >= n) return 0;
        hv = H->vcol ? H->vcol[map[v]] : 0;
        if (gv != hv) return 0;
    }
    if ((G->uo == NULL) != (H->uo == NULL) || (G->oo == NULL) != (H->oo == NULL)) return 0;
    if (G->uo && !rel_map_ok(n, G->uo, G->ua, H->uo, H->ua, map, mark, &stamp)) return 0;
    if (G->oo && !rel_map_ok(n, G->oo, G->oa, H->oo, H->oa, map, mark, &stamp)) return 0;
    return 1;
}

/* ========================================================================
 * Canonical labeling search
 * ======================================================================== */

typedef struct {
    Part P;
    const IG* g;
    Ctl* ctl;
    int n;
    /* per level of the current path */
    int *ls, *lsz, *li, *cv;
    unsigned char *eqf, *onf, *onb;
    signed char* cmpb;
    Mark* mk;
    int L, BL, k0;
    /* first path */
    int *fpv, *fplab, *fpsing;
    u64* fpev;
    long *fpevoff, *fpsingoff;
    /* best path and its relabeled graph */
    int *bpv, *bplab;
    UVec bpev;
    long* bpevoff;
    int *cuo, *cua, *coo, *coa;
    /* orbits of the automorphisms found (union-find) */
    int *uf, *ufs, *pmark;
    int stamp;
    long covered;
    /* scratch for automorphism tests */
    int *gam, *inR, *vmark, *mv, *rl, *rowbuf;
    int vstamp;
    /* generators, sparse: [k, v1, img1, ..., vk, imgk] ... */
    IVec gens;
    long ngens;
} Canon;

static void canon_free(Canon* C) {
    part_free(&C->P);
    free(C->ls);
    free(C->lsz);
    free(C->li);
    free(C->cv);
    free(C->eqf);
    free(C->onf);
    free(C->onb);
    free(C->cmpb);
    free(C->mk);
    free(C->fpv);
    free(C->fplab);
    free(C->fpsing);
    free(C->fpev);
    free(C->fpevoff);
    free(C->fpsingoff);
    free(C->bpv);
    free(C->bplab);
    free(C->bpev.a);
    free(C->bpevoff);
    free(C->cuo);
    free(C->cua);
    free(C->coo);
    free(C->coa);
    free(C->uf);
    free(C->ufs);
    free(C->pmark);
    free(C->gam);
    free(C->inR);
    free(C->vmark);
    free(C->mv);
    free(C->rl);
    free(C->rowbuf);
    free(C->gens.a);
    memset(C, 0, sizeof *C);
}

static int canon_init(Canon* C, const IG* G, Ctl* ctl) {
    int n = G->n, i;
    size_t N = (size_t)n, N1 = (size_t)n + 2;
    memset(C, 0, sizeof *C);
    C->g = G;
    C->ctl = ctl;
    C->n = n;
    if (!part_init(&C->P, G, ctl)) return 0;
    C->ls = (int*)malloc(N1 * sizeof(int));
    C->lsz = (int*)malloc(N1 * sizeof(int));
    C->li = (int*)malloc(N1 * sizeof(int));
    C->cv = (int*)malloc(N1 * sizeof(int));
    C->eqf = (unsigned char*)malloc(N1);
    C->onf = (unsigned char*)malloc(N1);
    C->onb = (unsigned char*)malloc(N1);
    C->cmpb = (signed char*)malloc(N1);
    C->mk = (Mark*)malloc(N1 * sizeof(Mark));
    C->fpv = (int*)malloc(N1 * sizeof(int));
    C->fplab = (int*)malloc(N * sizeof(int));
    C->fpevoff = (long*)malloc(N1 * sizeof(long));
    C->fpsingoff = (long*)malloc(N1 * sizeof(long));
    C->bpv = (int*)malloc(N1 * sizeof(int));
    C->bplab = (int*)malloc(N * sizeof(int));
    C->bpevoff = (long*)malloc(N1 * sizeof(long));
    C->cuo = (int*)malloc((N + 1) * sizeof(int));
    C->coo = (int*)malloc((N + 1) * sizeof(int));
    C->cua = (int*)malloc((size_t)(G->mu > 0 ? G->mu : 1) * sizeof(int));
    C->coa = (int*)malloc((size_t)(G->md > 0 ? G->md : 1) * sizeof(int));
    C->uf = (int*)malloc(N * sizeof(int));
    C->ufs = (int*)malloc(N * sizeof(int));
    C->pmark = (int*)calloc(N, sizeof(int));
    C->gam = (int*)malloc(N * sizeof(int));
    C->inR = (int*)calloc(N, sizeof(int));
    C->vmark = (int*)calloc(N, sizeof(int));
    C->mv = (int*)malloc(2 * N * sizeof(int));
    C->rl = (int*)malloc(N * sizeof(int));
    C->rowbuf = (int*)malloc(N * sizeof(int));
    if (!C->ls || !C->lsz || !C->li || !C->cv || !C->eqf || !C->onf || !C->onb || !C->cmpb ||
        !C->mk || !C->fpv || !C->fplab || !C->fpevoff || !C->fpsingoff || !C->bpv ||
        !C->bplab || !C->bpevoff || !C->cuo || !C->coo || !C->cua || !C->coa || !C->uf ||
        !C->ufs || !C->pmark || !C->gam || !C->inR || !C->vmark || !C->mv || !C->rl ||
        !C->rowbuf)
        return 0;
    for (i = 0; i < n; i++) {
        C->uf[i] = i;
        C->ufs[i] = 1;
        C->gam[i] = -1;
    }
    return 1;
}

static int uf_find(int* uf, int x) {
    while (uf[x] != x) {
        uf[x] = uf[uf[x]];
        x = uf[x];
    }
    return x;
}

/* Merge orbits; keep `covered` (processed part of the current first-path
 * target cell) up to date. */
static void uf_union(Canon* C, int a, int b) {
    int ra = uf_find(C->uf, a), rb = uf_find(C->uf, b), pa, pb;
    if (ra == rb) return;
    pa = C->pmark[ra] == C->stamp;
    pb = C->pmark[rb] == C->stamp;
    if (pa && !pb) C->covered += C->ufs[rb];
    if (pb && !pa) C->covered += C->ufs[ra];
    if (C->ufs[ra] < C->ufs[rb]) {
        int t = ra;
        ra = rb;
        rb = t;
    }
    C->uf[rb] = ra;
    C->ufs[ra] += C->ufs[rb];
    C->pmark[ra] = (pa || pb) ? C->stamp : 0;
}

static int img(const int* gam, int v) { return gam[v] >= 0 ? gam[v] : v; }

/* gamma(R(v)) == R(gamma(v)) for one relation. */
static int check_rel(Canon* C, const int* off, const int* adj, int v, int w) {
    int d = off[v + 1] - off[v];
    long j;
    if (off[w + 1] - off[w] != d) return 0;
    if (d == 0) return 1;
    if (C->vstamp == INT_MAX) {
        memset(C->vmark, 0, (size_t)C->n * sizeof(int));
        C->vstamp = 0;
    }
    C->vstamp++;
    for (j = off[w]; j < off[w + 1]; j++) C->vmark[adj[j]] = C->vstamp;
    for (j = off[v]; j < off[v + 1]; j++)
        if (C->vmark[img(C->gam, adj[j])] != C->vstamp) return 0;
    return 1;
}

/* gamma (gam[], identity where -1) is an automorphism iff every moved vertex
 * keeps its colour and its U, O and I neighbourhoods map onto those of its
 * image: an edge between two fixed vertices is trivially preserved, every
 * other edge is seen from a moved endpoint. */
static int verify_moved(Canon* C, int nm) {
    const IG* g = C->g;
    int i;
    for (i = 0; i < nm; i++) {
        int v = C->mv[i], w = img(C->gam, v);
        if (g->cls[v] != g->cls[w]) return 0;
        if (g->uo && !check_rel(C, g->uo, g->ua, v, w)) return 0;
        if (g->oo && (!check_rel(C, g->oo, g->oa, v, w) || !check_rel(C, g->io, g->ia, v, w)))
            return 0;
    }
    return 1;
}

static int add_gen(Canon* C, int nm) {
    IVec* G = &C->gens;
    int i;
    if (!ivec_grow(G, G->n + 1 + 2L * nm)) return 0;
    G->a[G->n++] = nm;
    for (i = 0; i < nm; i++) {
        G->a[G->n++] = C->mv[i];
        G->a[G->n++] = img(C->gam, C->mv[i]);
    }
    C->ngens++;
    for (i = 0; i < nm; i++) uf_union(C, C->mv[i], img(C->gam, C->mv[i]));
    return 1;
}

/* Current node at level t has the first path's trace and diverged from the
 * first path at level ell. Map the singletons the first path created below
 * ell onto the current singletons at the same positions, close the partial
 * map into a permutation fixing everything else, and verify it.
 * 1 = automorphism found (and recorded), 0 = no, -1 = allocation failure. */
static int try_aut_fp(Canon* C, int ell, int t) {
    Part* P = &C->P;
    long i, a0 = C->fpsingoff[ell], a1 = C->fpsingoff[t];
    int nm = 0, nr = 0, ok = 1, j, res = 0;
    for (i = a0; i < a1; i++) {
        int p = C->fpsing[i], a = C->fplab[p], b = P->lab[p];
        if (P->cst[b] != p || P->csz[p] != 1) {
            ok = 0;
            break;
        }
        if (a != b) {
            C->gam[a] = b;
            C->mv[nm++] = a;
            C->inR[b] = 1;
            C->rl[nr++] = b;
        }
    }
    if (ok) {
        int nd = nm;
        for (j = 0; j < nd; j++) { /* close each path a -> ... -> x into a cycle */
            int a = C->mv[j];
            if (!C->inR[a]) {
                int x = C->gam[a];
                while (C->gam[x] >= 0) x = C->gam[x];
                C->gam[x] = a;
                C->mv[nm++] = x;
            }
        }
        for (j = ell; j < t && ok; j++)
            if (img(C->gam, C->fpv[j]) != C->cv[j]) ok = 0;
        if (ok && nm > 0 && verify_moved(C, nm)) res = add_gen(C, nm) ? 1 : -1;
    }
    for (j = 0; j < nm; j++) C->gam[C->mv[j]] = -1;
    for (j = 0; j < nr; j++) C->inR[C->rl[j]] = 0;
    return res;
}

/* Current leaf has the same relabeled graph as the best leaf. */
static int try_aut_bp(Canon* C) {
    Part* P = &C->P;
    int p, nm = 0, res = 0, j;
    for (p = 0; p < C->n; p++) {
        int a = C->bplab[p], b = P->lab[p];
        if (a != b) {
            C->gam[a] = b;
            C->mv[nm++] = a;
        }
    }
    if (nm > 0 && verify_moved(C, nm)) res = add_gen(C, nm) ? 1 : -1;
    for (j = 0; j < nm; j++) C->gam[C->mv[j]] = -1;
    return res;
}

/* Sorted canonical labels of the R-neighbours of v. */
static int row_sorted(const int* off, const int* adj, const int* inv, int v, int* out) {
    int d = off[v + 1] - off[v], i, j;
    for (i = 0; i < d; i++) out[i] = inv[adj[off[v] + i]];
    if (d > 16) {
        qsort(out, (size_t)d, sizeof(int), cmp_int);
    } else {
        for (i = 1; i < d; i++) {
            int x = out[i];
            for (j = i; j > 0 && out[j - 1] > x; j--) out[j] = out[j - 1];
            out[j] = x;
        }
    }
    return d;
}

/* Compare the graph relabeled by the current leaf with the best one. */
static int compare_leaf(Canon* C) {
    const IG* g = C->g;
    const int *lab = C->P.lab, *inv = C->P.inv;
    int r, p, i;
    for (r = 0; r < 2; r++) {
        const int* off = r == 0 ? g->uo : g->oo;
        const int* adj = r == 0 ? g->ua : g->oa;
        const int* co = r == 0 ? C->cuo : C->coo;
        const int* ca = r == 0 ? C->cua : C->coa;
        if (!off) continue;
        for (p = 0; p < C->n; p++) {
            int d = row_sorted(off, adj, inv, lab[p], C->rowbuf), bd = co[p + 1] - co[p];
            const int* brow = ca + co[p];
            if (d != bd) return d > bd ? 1 : -1;
            for (i = 0; i < d; i++)
                if (C->rowbuf[i] != brow[i]) return C->rowbuf[i] > brow[i] ? 1 : -1;
        }
    }
    return 0;
}

static void store_rows(Canon* C) {
    const IG* g = C->g;
    const int *lab = C->P.lab, *inv = C->P.inv;
    int r, p;
    for (r = 0; r < 2; r++) {
        const int* off = r == 0 ? g->uo : g->oo;
        const int* adj = r == 0 ? g->ua : g->oa;
        int* co = r == 0 ? C->cuo : C->coo;
        int* ca = r == 0 ? C->cua : C->coa;
        co[0] = 0;
        for (p = 0; p < C->n; p++)
            co[p + 1] = co[p] + (off ? row_sorted(off, adj, inv, lab[p], ca + co[p]) : 0);
    }
}

/* The current leaf (level k1) becomes the best leaf. */
static int new_best(Canon* C, int k1) {
    Part* P = &C->P;
    int j;
    C->BL = k1;
    memcpy(C->bpv, C->cv, (size_t)k1 * sizeof(int));
    memcpy(C->bplab, P->lab, (size_t)C->n * sizeof(int));
    if (!uvec_grow(&C->bpev, P->ev.n + 1)) return 0;
    memcpy(C->bpev.a, P->ev.a, (size_t)P->ev.n * sizeof(u64));
    C->bpev.n = P->ev.n;
    for (j = 0; j <= k1; j++) {
        C->bpevoff[j] = C->mk[j].ev;
        C->onb[j] = 1;
        C->cmpb[j] = 0;
    }
    store_rows(C);
    return 1;
}

static void begin_level(Canon* C, int k) {
    int r = uf_find(C->uf, C->fpv[k]);
    C->stamp++;
    C->pmark[r] = C->stamp;
    C->covered = C->ufs[r];
    C->k0 = k;
}

/* Full canonical search. 1 ok, -1 budget/allocation. */
static int canon_run(Canon* C) {
    Part* P = &C->P;
    Ctl* ctl = C->ctl;
    int n = C->n, k, j;
    P->cmpmode = 0;
    if (!ctl_node(ctl) || refine(P) < 0) return -1;
    reset_logs(P);
    P->ev.n = 0;
    get_mark(P, &C->mk[0]);
    if (P->ncells == n) {
        C->L = 0;
        return new_best(C, 0) ? 1 : -1;
    }
    /* first path */
    k = 0;
    for (;;) {
        int s = pick_target(P);
        C->ls[k] = s;
        C->lsz[k] = P->csz[s];
        C->li[k] = 1;
        C->cv[k] = P->lab[s];
        if (!individualize(P, C->cv[k])) return -1;
        if (!ctl_node(ctl) || refine(P) < 0) return -1;
        k++;
        get_mark(P, &C->mk[k]);
        if (P->ncells == n) break;
    }
    C->L = k;
    C->fpev = (u64*)malloc((size_t)(P->ev.n + 1) * sizeof(u64));
    C->fpsing = (int*)malloc((size_t)(P->singlog.n + 1) * sizeof(int));
    if (!C->fpev || !C->fpsing) return -1;
    memcpy(C->fpev, P->ev.a, (size_t)P->ev.n * sizeof(u64));
    memcpy(C->fpsing, P->singlog.a, (size_t)P->singlog.n * sizeof(int));
    for (j = 0; j <= k; j++) {
        C->fpevoff[j] = C->mk[j].ev;
        C->fpsingoff[j] = C->mk[j].sing;
        C->eqf[j] = 1;
        C->onf[j] = 1;
    }
    memcpy(C->fpv, C->cv, (size_t)k * sizeof(int));
    memcpy(C->fplab, P->lab, (size_t)n * sizeof(int));
    if (!new_best(C, k)) return -1;

    /* backtracking over the rest of the tree */
    k = C->L - 1;
    undo_to(P, &C->mk[k]);
    begin_level(C, k);
    P->cmpmode = 1;
    for (;;) {
        int s = C->ls[k], sz = C->lsz[k], c = -1, rt = -1, k1, a, jump, rr;
        if (!C->onf[k] || C->covered < sz) {
            while (C->li[k] < sz) {
                int x = P->lab[s + C->li[k]++];
                if (C->onf[k]) { /* one child per orbit on the first path */
                    rt = uf_find(C->uf, x);
                    if (C->pmark[rt] == C->stamp) {
                        ctl_work(ctl, 1);
                        continue;
                    }
                }
                c = x;
                break;
            }
        }
        if (c < 0) { /* level exhausted */
            int wasfirst = C->onf[k];
            if (k == 0) break;
            k--;
            undo_to(P, &C->mk[k]);
            if (wasfirst) begin_level(C, k);
            continue;
        }
        if (C->onf[k]) {
            C->pmark[rt] = C->stamp;
            C->covered += C->ufs[rt];
        }
        C->cv[k] = c;
        if (!individualize(P, c) || !ctl_node(ctl)) return -1;
        if (C->eqf[k] && k + 1 <= C->L) {
            P->refA = C->fpev + C->fpevoff[k];
            P->lenA = C->fpevoff[k + 1] - C->fpevoff[k];
            P->eqA = 1;
        } else {
            P->eqA = 0;
        }
        if (C->cmpb[k] != 0) {
            P->stB = C->cmpb[k];
        } else if (k + 1 <= C->BL) {
            P->refB = C->bpev.a + C->bpevoff[k];
            P->lenB = C->bpevoff[k + 1] - C->bpevoff[k];
            P->stB = 0;
        } else {
            P->stB = 1;
        }
        rr = refine(P);
        if (rr < 0) return -1;
        if (rr > 0) {
            undo_to(P, &C->mk[k]);
            continue;
        }
        k1 = k + 1;
        get_mark(P, &C->mk[k1]);
        C->eqf[k1] = (unsigned char)P->eqA;
        C->cmpb[k1] = (signed char)P->stB;
        C->onf[k1] = 0;
        C->onb[k1] = (unsigned char)(C->onb[k] && k < C->BL && c == C->bpv[k]);
        jump = -1;
        if (C->eqf[k1]) {
            a = try_aut_fp(C, C->k0, k1);
            if (a < 0) return -1;
            if (a) jump = C->k0;
        }
        if (P->ncells == n) { /* leaf */
            if (jump < 0 && C->cmpb[k1] >= 0) {
                int cmp = C->cmpb[k1] > 0 ? 1 : compare_leaf(C);
                if (cmp > 0) {
                    if (!new_best(C, k1)) return -1;
                } else if (cmp == 0) {
                    a = try_aut_bp(C);
                    if (a < 0) return -1;
                    if (a) {
                        j = k;
                        while (j > 0 && !C->onb[j]) j--;
                        jump = j;
                    }
                }
            }
            undo_to(P, &C->mk[k]);
            if (jump >= 0 && jump < k) {
                k = jump;
                undo_to(P, &C->mk[k]);
            }
            continue;
        }
        if (jump >= 0) {
            k = jump;
            undo_to(P, &C->mk[k]);
            continue;
        }
        k = k1; /* descend */
        s = pick_target(P);
        C->ls[k] = s;
        C->lsz[k] = P->csz[s];
        C->li[k] = 0;
    }
    return 1;
}

/* ========================================================================
 * Direct isomorphism search G -> H
 * ======================================================================== */

typedef struct {
    long maxc;
    int (*cb)(const int* map, void* ctx);
    void* ctx;
    long count;
} EnumCtx;

/* Follow one path in G; search H for paths with identical traces.
 * find mode (en == NULL): 1 found (map filled), 0 not isomorphic,
 * 2 node limit reached, -1 error. enumerate mode: 1 complete/stopped,
 * -1 error (en->count holds the number reported). */
static int direct_search(const IG* G, const IG* H, Ctl* ctl, int* map, long limit,
                         EnumCtx* en) {
    int n = G->n, k, L = 0, res = -1, rr;
    Part Pg, Ph;
    int *gls = NULL, *glsz = NULL, *li = NULL, *mark = NULL;
    long *gevoff = NULL, start;
    Mark* mk = NULL;
    memset(&Pg, 0, sizeof Pg);
    memset(&Ph, 0, sizeof Ph);
    if (!part_init(&Pg, G, ctl) || !part_init(&Ph, H, ctl)) goto done;
    gls = (int*)malloc(((size_t)n + 1) * sizeof(int));
    glsz = (int*)malloc(((size_t)n + 1) * sizeof(int));
    li = (int*)malloc(((size_t)n + 1) * sizeof(int));
    mark = (int*)malloc((size_t)n * sizeof(int));
    gevoff = (long*)malloc(((size_t)n + 2) * sizeof(long));
    mk = (Mark*)malloc(((size_t)n + 1) * sizeof(Mark));
    if (!gls || !glsz || !li || !mark || !gevoff || !mk) goto done;

    /* roots in lockstep */
    Pg.cmpmode = 0;
    if (!ctl_node(ctl) || refine(&Pg) < 0) goto done;
    gevoff[0] = Pg.ev.n;
    Ph.cmpmode = 1;
    Ph.refA = Pg.ev.a;
    Ph.lenA = Pg.ev.n;
    Ph.eqA = 1;
    Ph.stB = -1;
    if (!ctl_node(ctl)) goto done;
    rr = refine(&Ph);
    if (rr < 0) goto done;
    if (rr > 0) {
        res = en ? 1 : 0;
        goto done;
    }
    reset_logs(&Pg);
    reset_logs(&Ph);
    Ph.ev.n = 0;

    /* G's path */
    k = 0;
    while (Pg.ncells < n) {
        int s = pick_target(&Pg);
        gls[k] = s;
        glsz[k] = Pg.csz[s];
        if (!individualize(&Pg, Pg.lab[s]) || !ctl_node(ctl) || refine(&Pg) < 0) goto done;
        k++;
        gevoff[k] = Pg.ev.n;
    }
    L = k;

    /* H's tree */
    start = ctl->nodes;
    get_mark(&Ph, &mk[0]);
    li[0] = 0;
    k = 0;
    for (;;) {
        int s, sz, c;
        if (k == L) { /* leaf (only reached directly when L == 0) */
            c = 0;
        } else {
            s = gls[k];
            sz = glsz[k];
            if (li[k] == 0 && (Ph.cst[Ph.lab[s]] != s || Ph.csz[s] != sz)) li[k] = sz;
            if (li[k] >= sz) {
                if (k == 0) break;
                k--;
                undo_to(&Ph, &mk[k]);
                continue;
            }
            c = Ph.lab[s + li[k]++];
            if (!individualize(&Ph, c) || !ctl_node(ctl)) goto done;
            if (limit > 0 && ctl->nodes - start > limit) {
                res = 2;
                goto done;
            }
            Ph.refA = Pg.ev.a + gevoff[k];
            Ph.lenA = gevoff[k + 1] - gevoff[k];
            Ph.eqA = 1;
            Ph.stB = -1;
            rr = refine(&Ph);
            if (rr < 0) goto done;
            if (rr > 0) {
                undo_to(&Ph, &mk[k]);
                continue;
            }
        }
        if (k == L || k + 1 == L) {
            int p, found = 0;
            if (Ph.ncells == n) {
                for (p = 0; p < n; p++) map[Pg.lab[p]] = Ph.lab[p];
                found = verify_map(G, H, map, mark);
            }
            if (found) {
                if (!en) {
                    res = 1;
                    goto done;
                }
                en->count++;
                if ((en->cb && !en->cb(map, en->ctx)) || (en->maxc > 0 && en->count >= en->maxc)) {
                    res = 1;
                    goto done;
                }
            }
            if (k == L) break; /* L == 0: single leaf */
            undo_to(&Ph, &mk[k]);
            continue;
        }
        k++;
        get_mark(&Ph, &mk[k]);
        li[k] = 0;
    }
    res = en ? 1 : 0;
done:
    part_free(&Pg);
    part_free(&Ph);
    free(gls);
    free(glsz);
    free(li);
    free(mark);
    free(gevoff);
    free(mk);
    return res;
}

/* Compare canonical forms of G and H. 1 (map filled) / 0 / -1. */
static int canon_compare(const IG* G, const IG* H, Ctl* ctl, int* map) {
    Canon A, B;
    int res = -1, n = G->n, p;
    int* mark = NULL;
    memset(&A, 0, sizeof A);
    memset(&B, 0, sizeof B);
    if (!canon_init(&A, G, ctl) || !canon_init(&B, H, ctl)) goto done;
    if (canon_run(&A) < 0 || canon_run(&B) < 0) goto done;
    res = 0;
    for (p = 0; p < n; p++) {
        int ca = G->vcol ? G->vcol[A.bplab[p]] : 0, cb = H->vcol ? H->vcol[B.bplab[p]] : 0;
        if (ca != cb) goto done;
    }
    if (memcmp(A.cuo, B.cuo, ((size_t)n + 1) * sizeof(int)) ||
        memcmp(A.coo, B.coo, ((size_t)n + 1) * sizeof(int)) ||
        (G->mu > 0 && memcmp(A.cua, B.cua, (size_t)G->mu * sizeof(int))) ||
        (G->md > 0 && memcmp(A.coa, B.coa, (size_t)G->md * sizeof(int))))
        goto done;
    mark = (int*)malloc((size_t)n * sizeof(int));
    if (!mark) {
        res = -1;
        goto done;
    }
    for (p = 0; p < n; p++) map[A.bplab[p]] = B.bplab[p];
    res = verify_map(G, H, map, mark); /* always 1 when the forms agree */
done:
    free(mark);
    canon_free(&A);
    canon_free(&B);
    return res;
}

static int find_core(const IG* G, const IG* H, Ctl* ctl, int* map) {
    int r = direct_search(G, H, ctl, map, GALG_ISO_DIRECT_LIMIT(G->n), NULL);
    if (r == 2) r = canon_compare(G, H, ctl, map);
    return r;
}

/* Build both graphs and run the quick tests. 1 go on, 0 not iso, -1 error. */
static int prepare_pair(const GalgIsoGraph* g, const GalgIsoGraph* h, IG* G, IG* H) {
    int r;
    memset(G, 0, sizeof *G);
    memset(H, 0, sizeof *H);
    if (!ig_build(G, g) || !ig_build(H, h)) return -1;
    r = quick_same(G, H);
    return r;
}

/* ========================================================================
 * Public interface
 * ======================================================================== */

int galg_iso_find(const GalgIsoGraph* g, const GalgIsoGraph* h, int* map, long budget) {
    IG G, H;
    Ctl ctl;
    int r;
    if (!g || !h || g->n < 0 || h->n < 0) return -1;
    if (g->n != h->n) return 0;
    if (g->n == 0) return 1;
    if (!map) return -1;
    r = prepare_pair(g, h, &G, &H);
    if (r > 0) {
        memset(&ctl, 0, sizeof ctl);
        ctl.budget = budget;
        r = find_core(&G, &H, &ctl, map);
    }
    ig_free(&G);
    ig_free(&H);
    return r;
}

long galg_iso_enumerate(const GalgIsoGraph* g, const GalgIsoGraph* h, long max_count,
                        int (*cb)(const int* map, void* ctx), void* ctx, long budget) {
    IG G, H;
    Ctl ctl;
    EnumCtx en;
    int r;
    int* map;
    long res;
    if (!g || !h || g->n < 0 || h->n < 0) return -1;
    if (g->n != h->n) return 0;
    if (g->n == 0) {
        int dummy = 0;
        if (cb) cb(&dummy, ctx);
        return 1;
    }
    map = (int*)malloc((size_t)g->n * sizeof(int));
    if (!map) return -1;
    r = prepare_pair(g, h, &G, &H);
    res = r;
    if (r > 0) {
        memset(&ctl, 0, sizeof ctl);
        ctl.budget = budget;
        r = find_core(&G, &H, &ctl, map); /* settles non-isomorphic pairs robustly */
        res = r;
        if (r > 0) {
            en.maxc = max_count;
            en.cb = cb;
            en.ctx = ctx;
            en.count = 0;
            r = direct_search(&G, &H, &ctl, map, 0, &en);
            res = r < 0 ? -1 : en.count;
        }
    }
    free(map);
    ig_free(&G);
    ig_free(&H);
    return res;
}

int galg_iso_canon(const GalgIsoGraph* g, int* lab, long budget) {
    IG G;
    Ctl ctl;
    Canon C;
    int r;
    if (!g || g->n < 0) return -1;
    if (g->n == 0) return 1;
    if (!lab) return -1;
    memset(&C, 0, sizeof C);
    if (!ig_build(&G, g)) {
        ig_free(&G);
        return -1;
    }
    memset(&ctl, 0, sizeof ctl);
    ctl.budget = budget;
    r = canon_init(&C, &G, &ctl) ? canon_run(&C) : -1;
    if (r > 0) memcpy(lab, C.bplab, (size_t)g->n * sizeof(int));
    canon_free(&C);
    ig_free(&G);
    return r > 0 ? 1 : -1;
}

long galg_iso_automorphisms(const GalgIsoGraph* g, int** gens, long budget) {
    IG G;
    Ctl ctl;
    Canon C;
    long res = -1, i, pos;
    int n, v;
    if (!gens) return -1;
    *gens = NULL;
    if (!g || g->n < 0) return -1;
    if (g->n == 0) return 0;
    n = g->n;
    memset(&C, 0, sizeof C);
    if (!ig_build(&G, g)) {
        ig_free(&G);
        return -1;
    }
    memset(&ctl, 0, sizeof ctl);
    ctl.budget = budget;
    if (canon_init(&C, &G, &ctl) && canon_run(&C) > 0) {
        if (C.ngens == 0) {
            res = 0;
        } else if ((size_t)C.ngens <= ((size_t)-1) / sizeof(int) / (size_t)n) {
            int* out = (int*)malloc((size_t)C.ngens * (size_t)n * sizeof(int));
            if (out) {
                pos = 0;
                for (i = 0; i < C.ngens; i++) {
                    int* p = out + (size_t)i * (size_t)n;
                    int nm = C.gens.a[pos++], j;
                    for (v = 0; v < n; v++) p[v] = v;
                    for (j = 0; j < nm; j++) {
                        int a = C.gens.a[pos++], b = C.gens.a[pos++];
                        p[a] = b;
                    }
                }
                *gens = out;
                res = C.ngens;
            }
        }
    }
    canon_free(&C);
    ig_free(&G);
    return res;
}
