/* numberfieldintegralbasis.c — NumberFieldIntegralBasis[a].
 *
 * See numberfieldintegralbasis.h for the contract. All field / maximal-order
 * computation is delegated to flint_qqbar_integral_basis (which builds the
 * algebraic-integer generator, runs the number-field layer's Dedekind + Round 2
 * maximal-order engine, and renders each basis row as a canonical
 * AlgebraicNumber). This file only checks the argument shape and reports a
 * decline; the evaluator re-canonicalises each returned element on its next
 * fixed-point step.
 */

#include "numberfieldintegralbasis.h"

#include "flint_qqbar.h"
#include "symtab.h"
#include "attr.h"
#include "print.h"

#include <stdio.h>
#include <stdlib.h>

Expr* builtin_numberfieldintegralbasis(Expr* res) {
    if (res->type != EXPR_FUNCTION || res->data.function.arg_count != 1)
        return NULL;

    const Expr* a = res->data.function.args[0];
    Expr* basis = flint_qqbar_integral_basis(a);
    if (basis) return basis;

    /* Could not build an integral basis: not a constant algebraic number, degree
     * over the cap, an uncertifiable maximal order, or FLINT compiled out. */
    char* s = expr_to_string((Expr*)a);
    fprintf(stderr,
            "NumberFieldIntegralBasis::nintbas: unable to find an integral "
            "basis for the field generated by %s.\n", s ? s : "?");
    free(s);
    return NULL;
}

void numberfieldintegralbasis_init(void) {
    symtab_add_builtin("NumberFieldIntegralBasis",
                       builtin_numberfieldintegralbasis);
    /* Listable: NumberFieldIntegralBasis[{a1, ..}] threads element-wise, giving
     * one integral basis per generator (each is its own field). */
    symtab_get_def("NumberFieldIntegralBasis")->attributes |=
        ATTR_LISTABLE | ATTR_PROTECTED;
}
