/* numberfieldintegralbasis.h — NumberFieldIntegralBasis[a] builtin.
 *
 * NumberFieldIntegralBasis[a] gives a Z-module basis for the ring of integers
 * O_K of the number field K = Q(a) generated by the algebraic number a: a list
 * of algebraic integers {w1, ..., wn} (n = [K:Q]) that generate O_K over Z.
 *
 * The equation order Z[phi] of the algebraic-integer generator phi of Q(a) is
 * enlarged to the maximal order O_K by Round 2 (Pohst-Zassenhaus) where it is
 * not already maximal, so the basis is correct even for non-monogenic fields
 * (e.g. Q(Sqrt[2] + Sqrt[3])).  Each basis element is returned as a canonical
 * AlgebraicNumber[phi, {..}] (or a plain Integer/Rational when it is rational).
 * The basis is not unique.  Requires FLINT.
 *
 * Attributes: Listable, Protected.  Threads element-wise over a list argument.
 *
 * Ownership: the standard builtin contract — returns a fresh Expr on success
 * (the evaluator frees res), or NULL to leave res unevaluated (a non-algebraic
 * argument, a degree over the cap, an uncertifiable maximal order, or FLINT
 * compiled out), after emitting a NumberFieldIntegralBasis message.
 */
#ifndef MATHILDA_NUMBERFIELDINTEGRALBASIS_H
#define MATHILDA_NUMBERFIELDINTEGRALBASIS_H

#include "expr.h"

Expr* builtin_numberfieldintegralbasis(Expr* res);
void numberfieldintegralbasis_init(void);

#endif /* MATHILDA_NUMBERFIELDINTEGRALBASIS_H */
