/* rootofunity.h — cyclotomic extension support for the Q(α) substrate.
 *
 * Mathilda canonicalises every root of unity into the single surface
 * family `Power[-1, Rational[p, q]]` (with `I` / `Complex[0, ±1]` as the
 * special case q == 2).  Such an atom has value
 *
 *     (-1)^(p/q) = exp(I π p/q) = ζ_{2q}^p,
 *
 * a primitive (2q / gcd(p, 2q))-th root of unity that lives in the
 * cyclotomic field Q(ζ_{2q}) generated by the natural generator
 * ζ_{2q} = (-1)^(1/q), whose minimal polynomial is the cyclotomic
 * polynomial Φ_{2q}(y).
 *
 * This module gives the extension recognizer (`qa_resolve_extension`,
 * `extension_autodetect`) the two primitives it needs to lift such
 * constants into the existing fast Q(α)[x] arithmetic substrate
 * (qa.{c,h} / qaupoly.{c,h}) instead of carrying them as opaque
 * `Power[...]` trees that blow up the rational-over-Q path. */

#ifndef MATHILDA_ROOTOFUNITY_H
#define MATHILDA_ROOTOFUNITY_H

#include <stdbool.h>
#include <stdint.h>

#include "qa.h"

struct Expr;

/* If `e` is a root-of-unity atom — `Power[-1, Rational[p, q]]`,
 * `Power[-1, integer]` (q == 1), the symbol `I`, or `Complex[0, ±1]` —
 * set *p_out and *q_out so that the value equals (-1)^(p/q) with q ≥ 1,
 * and return true.  Returns false for everything else.
 *
 * The natural generator for the atom is ζ_{2q} = (-1)^(1/q); build its
 * field with `qaext_cyclotomic(2 * q)`. */
bool expr_is_root_of_unity_pow(const struct Expr* e,
                               int64_t* p_out, int64_t* q_out);

/* Build the QAExt for the cyclotomic field Q(ζ_n) generated by a
 * primitive n-th root of unity.  Its minimal polynomial is the
 * cyclotomic polynomial Φ_n(y) ∈ Z[y] of degree φ(n), computed by the
 * exact divisor recursion
 *
 *     Φ_n(y) = (y^n − 1) / ∏_{d | n, d < n} Φ_d(y).
 *
 * Returns a fresh QAExt (caller owns: qaext_free).  Returns NULL for
 * n == 0. */
QAExt* qaext_cyclotomic(unsigned long n);

#endif
