# Diophantine examples for §4.2.11. One Mathilda session; codepairs 1..13.
Solve[5 x + 3 y == 1, {x, y}, Integers]
Solve[6 x + 9 y == 5, {x, y}, Integers]
Solve[{x + 2 y + 3 z == 10, x - y + z == 2}, {x, y, z}, Integers]
Solve[x^2 + y^2 == 3 z^2, {x, y, z}, Integers]
Solve[x^3 + y^3 == 1729 && 0 < x <= y, {x, y}, Integers]
Solve[x^3 + y^3 + z^3 == 4, {x, y, z}, Integers]
Solve[y^2 == x^3 - 2, {x, y}, Integers]
Solve[2^n - 7 == x^2 && n > 0 && x > 0, {n, x}, Integers]
Solve[n! + 1 == m^2 && 0 < n < 100 && m > 0, {n, m}, Integers]
Solve[x^a - y^b == 1 && 1 < x < 100 && 1 < y < 100 && a > 1 && b > 1, {x, y, a, b}, Integers]
Solve[x^3 + y^3 == z^3 && x > 0 && y > 0 && z > 0, {x, y, z}, Integers]
Solve[x^3 - 2 y^3 == 1, {x, y}, Integers]
Solve[x^2 - 2 y^2 == 1, {x, y}, Integers]
