PolynomialGCD[x^3 - 1, x^2 - 1]
PolynomialExtendedGCD[x^2 - 1, x^2 + x - 2, x]
PolynomialQuotientRemainder[x^3 - 1, x - 1, x]
PolynomialLCM[x^2 - 1, x^2 + x - 2]
Resultant[x^2 - 2, x^2 - 3, x]
Resultant[x^2 + a x + b, x^2 + c x + d, x]
Discriminant[a x^2 + b x + c, x]
Discriminant[x^3 + p x + q, x]
Eliminate[{x + y == 1, x^2 + y^2 == 4}, y]
