GroebnerBasis[{x^2 + y^2 - 1, x - y}, {x, y}]
GroebnerBasis[{x^2 - y, y^2 - x}, {x, y}]
GroebnerBasis[{x^2 - y, y^2 - x}, {x, y}, MonomialOrder -> DegreeReverseLexicographic]
GroebnerBasis[{x y - 1, x^2 + y^2 - 4}, {x, y}, Modulus -> 7]
GroebnerBasis[{t^2 - x, t^3 - y}, {t, x, y}]
GroebnerBasis[{t^2 - x, t^3 - y}, {x, y}, {t}]
