#!/usr/bin/env python3
"""Generate ``book/generated/builtinlinks.tex`` from the site's builtin index.

The book links every builtin it mentions to that builtin's reference page on the
public documentation site.  The single source of truth for "name -> reference
URL" is ``site/docs/assets/builtins.json`` (the same file the MkDocs site ships),
so this script simply materialises it as a table of ``\\DeclareBuiltinLink``
commands that ``\\B{}`` (defined in ``book/mathilda.sty``) looks up.

It is deterministic and safe to re-run: ``make links`` calls it before every
build.  It invents nothing -- it only re-expresses the JSON the site already
publishes.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]          # repo root
JSON = ROOT / "site" / "docs" / "assets" / "builtins.json"
OUT = ROOT / "book" / "generated" / "builtinlinks.tex"
BASE = "https://stblake.github.io/mathilda/"

# Names we can safely turn into a LaTeX macro key and print with \texttt.
# Covers ordinary names, $-system symbols, and FLINT`Suffix routines.
SAFE = re.compile(r"^[A-Za-z0-9$`]+$")


def tex_key(name):
    """A LaTeX-safe rendering of the name.

    ``$`` is escaped to ``\\$`` so that (a) ``\\detokenize`` yields the same
    string on the declaration and lookup sides, and (b) ``\\texttt`` prints a
    literal dollar sign rather than entering math mode.
    """
    return name.replace("$", r"\$")


def href_url(url_path):
    """Absolute reference URL, made safe to sit inside a LaTeX ``\\href{...}``.

    ``$`` is percent-encoded to ``%24`` for a clean href; then ``%`` and ``#``
    are backslash-escaped, because inside ``\\href`` LaTeX otherwise treats ``%``
    as a comment (swallowing the rest of the line) and ``#`` as a parameter.
    """
    url = (BASE + url_path).replace("$", "%24")
    return url.replace("%", r"\%").replace("#", r"\#")


def main():
    if not JSON.exists():
        sys.exit(f"error: {JSON} not found.")
    data = json.load(open(JSON))
    OUT.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "% AUTO-GENERATED by book/tools/gen_links.py -- do not edit by hand.",
        "% Source of truth: site/docs/assets/builtins.json",
        "",
    ]
    written, skipped = 0, []
    for e in sorted(data, key=lambda e: e["name"]):
        name = e["name"]
        if not SAFE.match(name):
            skipped.append(name)
            continue
        lines.append(r"\DeclareBuiltinLink{%s}{%s}" % (tex_key(name), href_url(e["url"])))
        written += 1

    OUT.write_text("\n".join(lines) + "\n")
    print(f"gen_links: wrote {written} builtin links -> {OUT.relative_to(ROOT)}")
    if skipped:
        head = ", ".join(skipped[:8]) + (" ..." if len(skipped) > 8 else "")
        print(f"gen_links: skipped {len(skipped)} name(s) with unsupported chars: {head}")


if __name__ == "__main__":
    main()
