#!/usr/bin/env python3
"""Generate ``book/generated/version.tex``: the Mathilda version this build used.

The book records, on its title and copyright pages, the exact Mathilda version its
transcripts were produced by. That version is NOT hard-coded -- it is read from the
real ``./Mathilda`` binary at build time (the same binary ``build_examples.py`` runs
the examples through), so the printed version can never drift from the one that
actually generated the transcripts.

The output ``\\def``s ``\\mathildaversion`` (used by the frontmatter); ``mathilda.sty``
provides a fallback in case this file was not generated. It is deterministic and safe
to re-run: ``make version`` (and every ``make pdf``) calls it.
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]          # repo root
BIN = ROOT / "Mathilda"
OUT = ROOT / "book" / "generated" / "version.tex"


def main():
    if not BIN.exists():
        sys.exit(f"error: {BIN} not found -- build it first (make -C .. ).")
    # `--version` prints "Mathilda X.YZ (GCC ..., GMP ..., ...)" to stdout.
    res = subprocess.run([str(BIN), "--version"], capture_output=True, text=True)
    banner = (res.stdout or "") + (res.stderr or "")
    m = re.search(r"Mathilda\s+([0-9]+(?:\.[0-9]+)+)", banner)
    if not m:
        sys.exit(f"error: could not parse a version from: {banner!r}")
    version = m.group(1)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "% AUTO-GENERATED by book/tools/gen_version.py -- do not edit by hand.\n"
        "% The Mathilda version whose binary produced this build's transcripts.\n"
        "\\def\\mathildaversion{" + version + "}\n"
    )
    print(f"gen_version: Mathilda {version} -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
