/* int_rnb.h — RischNormanBlake: parallel Risch-Norman integration over a
 * simple radical extension L = K(y), y^m = q(x), for K = Q(x), Dx = 1.
 *
 * Generalises the parallel Risch-Norman method (Bronstein's pmint,
 * src/calculus/intrischnorman.c) to a single radical of the integration
 * variable, following S. Blake, "Parallel Integration over Simple Radical
 * Extensions".  Where the transcendental pmint declines any algebraic
 * function of x, this engine handles exactly the y^m = q(x) integrands:
 *   - the antiderivative numerator ranges over the integral closure
 *     O = (+)_{i=0}^{m-1} R w_i with the Trager basis w_i = y^i / E_i;
 *   - the logands are the S-units of O (denominator factors, branch-place
 *     divisors, and units at infinity), not merely irreducible polynomials.
 *
 * Exposed as the context-qualified builtin Integrate`RischNormanBlake[f, x]
 * and wired into the Integrate cascade / Method -> "RischNormanBlake".
 *
 * Memory contract: standard Mathilda BuiltinFunc — the evaluator owns the
 * argument; a builtin returns a fresh Expr* on success or NULL on failure.
 */
#ifndef MATHILDA_INT_RNB_H
#define MATHILDA_INT_RNB_H

#include "expr.h"

/* Integrate`RischNormanBlake[f, x]: attempt an elementary antiderivative of
 * f in x over the radical extension generated by a single radical of x that
 * appears in f.  Returns the antiderivative on success, NULL on decline. */
Expr* builtin_rischnormanblake(Expr* res);

/* Register Integrate`RischNormanBlake (attributes + docstring).  Called from
 * integrate_init() during core_init().  Idempotent. */
void int_rnb_init(void);

#endif /* MATHILDA_INT_RNB_H */
