# 10.1 Expression trees: the tagged union behind the surface syntax.
FullForm[a + b c]
FullForm[1/2]
FullForm[3/6]
FullForm[a/b]
FullForm[2 + 3 I]
FullForm[{a, b, c}]
FullForm[x_]
Head[17]
Head[3.5]
Head[x]
Head["text"]
Head[{1, 2}]
Head[a + b]
AtomQ[17]
AtomQ[x]
AtomQ[a + b]
