# FullForm reveals how the parser groups operators by precedence.
FullForm[a + b*c]
FullForm[a*b + c]
FullForm[a/b]
FullForm[-x]
FullForm[a - b]
FullForm[a^b^c]
FullForm[a == b == c]
FullForm[a ;; b]
FullForm[f @ x]
FullForm[x // f]
FullForm[#^2 &]
FullForm[a -> b]
FullForm[a && b || c]
FullForm[a[[1]]]
