#!/usr/bin/env python3
"""extract_inline_cases.py

Extract every commented-out `IntegrateRational[expr, var]` test cell
from IntegrateRational.m and IntegrateRational.nb (both contain the
same set of inline examples in slightly different form), and emit a
List literal of {integrand, var} pairs that the corpus runner can
load via Get[].

Usage:
    python3 tools/extract_inline_cases.py > IntegrateRationalInlineCases.m

Strategy:
    The .m file has lines of the form

        (*IntegrateRational[<args>] <postprocessing_or_comment> *)

    where <args> contains the integrand and integration variable.  We
    extract the inside of IntegrateRational[...], split into integrand
    and variable, and emit as {integrand, variable}.

    Cases using the % reference operator (referring to the previous
    output) are skipped — they require a stateful REPL session, which
    the corpus runner does not provide.

    The .nb file is a notebook in box-form syntax; we extract from the
    .m file only because the .m is the authoritative source and the
    .nb mirrors it.
"""
import re
import sys
import os


M_FILE = "IntegrateRational.m"


def extract_args(call_text):
    """Given the text inside `IntegrateRational[<call_text>]`, find
    the top-level comma that separates integrand from variable.
    Brackets nest, so a naive split fails for things like
    `(a+b)[1, 2]`.  We track bracket depth."""
    depth = 0
    paren_depth = 0
    brace_depth = 0
    in_string = False
    for i, ch in enumerate(call_text):
        if in_string:
            if ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
        elif ch == '[':
            depth += 1
        elif ch == ']':
            depth -= 1
        elif ch == '(':
            paren_depth += 1
        elif ch == ')':
            paren_depth -= 1
        elif ch == '{':
            brace_depth += 1
        elif ch == '}':
            brace_depth -= 1
        elif ch == ',' and depth == 0 and paren_depth == 0 and brace_depth == 0:
            return call_text[:i].strip(), call_text[i + 1:].strip()
    return None


def find_call_close(text, start):
    """Find the matching ] for a call beginning at `start - 1` (which
    is just past the opening [).  Returns the index OF the closing ]."""
    depth = 1
    i = start
    in_string = False
    while i < len(text):
        ch = text[i]
        if in_string:
            if ch == '"':
                in_string = False
        elif ch == '"':
            in_string = True
        elif ch == '[':
            depth += 1
        elif ch == ']':
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return -1


def extract_from_m(path):
    cases = []
    with open(path, "r") as f:
        text = f.read()
    # Look for occurrences of "IntegrateRational[" preceded by "(*"
    # somewhere on the same line — this avoids picking up the function
    # definition itself.
    cursor = 0
    while True:
        m = re.search(r"\(\*\s*IntegrateRational\s*\[", text[cursor:])
        if not m:
            break
        absolute = cursor + m.end()
        close = find_call_close(text, absolute)
        if close < 0:
            cursor = absolute
            continue
        inside = text[absolute:close]
        cursor = close + 1
        if "%" in inside.split(",", 1)[0]:
            # uses prior-result reference, skip
            continue
        parts = extract_args(inside)
        if not parts:
            continue
        integrand, variable = parts
        # Cleanup: trim whitespace and strip any inline `(* comment *)` chunks.
        integrand = re.sub(r"\(\*[^*]*\*\)", "", integrand).strip()
        variable  = re.sub(r"\(\*[^*]*\*\)", "", variable).strip()
        if not integrand or not variable:
            continue
        cases.append((integrand, variable))
    return cases


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.dirname(here)
    m_path = os.path.join(repo, M_FILE)
    cases = extract_from_m(m_path)
    out = ["(* Auto-generated by tools/extract_inline_cases.py *)"]
    out.append("(* Inline test cases extracted from IntegrateRational.m *)")
    out.append("(* Format: List of {integrand, integration_variable}.  *)")
    out.append("")
    out.append("{")
    # picocas's parser does not accept trailing commas in List literals,
    # so the last entry must have no comma.
    for i, (integrand, variable) in enumerate(cases):
        sep = "," if i + 1 < len(cases) else ""
        out.append(f"  {{{integrand}, {variable}}}{sep}")
    out.append("}")
    print("\n".join(out))
    sys.stderr.write(f"Extracted {len(cases)} inline cases from {m_path}\n")


if __name__ == "__main__":
    main()
