#!/usr/bin/env python3
"""Generate src/graphics/hershey_glyphs.inc from the Hershey reference data.

Transcribes the classic Hershey *Roman Simplex* occidental font (single-stroke,
the standard scientific-plotting alphabet) into a C data fragment consumed by
src/graphics/hershey_font.c. The build and runtime never read the raw data file
-- only this generated .inc -- so re-run this script (and rebuild) whenever the
font set changes:

    python3 tools/gen_hershey.py

Reference-file format (Hershey "occidental" dataset):
  * Each glyph record: cols 0-4 = glyph number (right justified), cols 5-7 =
    vertex count, then `count` coordinate pairs. Records WRAP across physical
    lines; continuation lines carry no leading number and must be concatenated.
  * Each pair is 2 chars; coordinate value = ord(char) - ord('R'). A pair whose
    first char is a space (' R') is a PEN-UP (start a new disconnected stroke).
  * Pair[0] is the left/right side bearing (advance bounds), not ink.
  * y increases downward; baseline at y=9, cap top at y=-12.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "hershey.dat")
OUT = os.path.join(HERE, os.pardir, "src", "graphics", "hershey_glyphs.inc")

# Roman Simplex glyph number for each printable ASCII code, 32..126 (95 entries).
# Caps A-Z = 501-526, lowercase a-z = 601-626, digits 0-9 = 700-709, with the
# remaining punctuation/symbol glyphs scattered through the occidental set.
SIMPLEX_MAP = [
    699, 714, 717, 733, 719, 2271, 734, 731, 721, 722, 728, 725, 711, 724, 710, 720,
    700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 712, 713, 2241, 726, 2242, 715,
    2273, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515,
    516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 2223, 804, 2224, 2262, 999,
    730, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615,
    616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 2225, 723, 2226, 2246,
]
assert len(SIMPLEX_MAP) == 95, "map must cover ASCII 32..126"

PEN_UP = -128  # sentinel in the emitted signed-char vertex stream


def parse_hershey(path):
    """Return {glyph_number: [(x, y) or 'PU', ...]}; pair[0] is (left, right)."""
    records = []
    cur = None
    with open(path) as f:
        for line in f:
            line = line.rstrip("\n")
            head = line[0:5]
            if head.strip().isdigit() and len(line) >= 8:
                if cur is not None:
                    records.append(cur)
                cur = [int(line[0:5]), int(line[5:8]), line[8:]]
            elif cur is not None:
                cur[2] += line
    if cur is not None:
        records.append(cur)

    glyphs = {}
    for num, count, data in records:
        chars = data[: 2 * count]
        pairs = []
        for k in range(count):
            a, b = chars[2 * k], chars[2 * k + 1]
            if a == " ":
                pairs.append("PU")
            else:
                pairs.append((ord(a) - ord("R"), ord(b) - ord("R")))
        glyphs[num] = pairs
    return glyphs


def main():
    glyphs = parse_hershey(DATA)
    missing = [g for g in SIMPLEX_MAP if g not in glyphs]
    if missing:
        sys.exit("missing Hershey glyphs: %r" % missing)

    lines = []
    lines.append("/* hershey_glyphs.inc -- GENERATED by tools/gen_hershey.py. DO NOT EDIT.")
    lines.append(" *")
    lines.append(" * Hershey Roman Simplex font, transcribed from tools/hershey.dat.")
    lines.append(" * Raw Hershey integer coordinates (value = char - 'R'), y increases")
    lines.append(" * downward, baseline y=9, cap top y=-12. A vertex with x == HF_PENUP")
    lines.append(" * lifts the pen (next vertex starts a new disconnected stroke).")
    lines.append(" * Regenerate with: python3 tools/gen_hershey.py */")
    lines.append("")
    lines.append("#define HF_PENUP (-128)")
    lines.append("")
    lines.append("typedef struct { signed char x, y; } hf_vtx;")
    lines.append("typedef struct {")
    lines.append("    signed char  left, right;  /* side bearings (advance bounds) */")
    lines.append("    const hf_vtx *verts;       /* stroke vertices (NULL if blank) */")
    lines.append("    short        nverts;")
    lines.append("} hf_glyph;")
    lines.append("")

    # Emit a vertex array per ASCII code that has ink.
    vert_decl = {}
    for i, gnum in enumerate(SIMPLEX_MAP):
        code = 32 + i
        pairs = glyphs[gnum]
        verts = pairs[1:]
        if not verts:
            continue
        toks = []
        for v in verts:
            if v == "PU":
                toks.append("{HF_PENUP,0}")
            else:
                toks.append("{%d,%d}" % (v[0], v[1]))
        name = "hf_v_%d" % code
        vert_decl[code] = name
        # wrap long arrays for readability
        body = ",".join(toks)
        lines.append("static const hf_vtx %s[] = {%s};" % (name, body))
    lines.append("")

    lines.append("/* Indexed by ASCII code - 32 (printable range 32..126). */")
    lines.append("static const hf_glyph hf_ascii[95] = {")
    for i, gnum in enumerate(SIMPLEX_MAP):
        code = 32 + i
        pairs = glyphs[gnum]
        left, right = pairs[0]
        verts = pairs[1:]
        ch = chr(code)
        comment = "' '" if ch == " " else ("'%s'" % ch if ch not in "\\'" else "'\\%s'" % ch)
        if verts:
            name = vert_decl[code]
            lines.append(
                "    {%d,%d,%s,(short)(sizeof(%s)/sizeof(hf_vtx))}, /* %s */"
                % (left, right, name, name, comment)
            )
        else:
            lines.append("    {%d,%d,NULL,0}, /* %s */" % (left, right, comment))
    lines.append("};")
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d glyphs)" % (OUT, len(SIMPLEX_MAP)))


if __name__ == "__main__":
    main()
